/* Generated by tools/kknd_info_gen.c. Do not edit by hand.
   Source data: data/KKND/UNITS.CFG + OpenKKnD MOBD_ID table.
   Sprite names are MOBD member indices into LEVELS/640/SPRITES.LVL. */
#include "engine.h"
#include "info.h"

const char *const sprnames[NUMSPRITES] = {
    "34",  /* UNIT_SURV_INFANTRY */
    "25",  /* UNIT_SURV_FLAMER */
    "76",  /* UNIT_SURV_SWAT */
    "63",  /* UNIT_SURV_SAPPER */
    "62",  /* UNIT_SURV_SABOTEUR */
    "78",  /* UNIT_SURV_TECHNICIAN */
    "59",  /* UNIT_SURV_ROCKETLAUNCHER */
    "71",  /* UNIT_SURV_SNIPER */
    "5",  /* UNIT_MUTE_BERSERKER */
    "55",  /* UNIT_MUTE_PYRO */
    "68",  /* UNIT_MUTE_SHOTGUNNER */
    "58",  /* UNIT_MUTE_RIOTER */
    "81",  /* UNIT_MUTE_VANDAL */
    "41",  /* UNIT_MUTE_TECHNICIAN */
    "60",  /* UNIT_MUTE_ROCKETLAUNCHER */
    "31",  /* UNIT_MUTE_CRAZYHARRY */
    "7",  /* UNIT_SURV_BIKE */
    "54",  /* UNIT_SURV_PICKUP */
    "1",  /* UNIT_SURV_ATV */
    "24",  /* UNIT_SURV_FLAMEATV */
    "77",  /* UNIT_SURV_ANACONDA */
    "2",  /* UNIT_SURV_BARAGECRAFT */
    "11",  /* UNIT_SURV_CANNONTANK */
    "65",  /* UNIT_SURV_DERRICK */
    "73",  /* UNIT_SURV_TANKER */
    "53",  /* UNIT_SURV_MOBILE_BASE */
    "19",  /* UNIT_MUTE_WOLF */
    "70",  /* UNIT_MUTE_SIDECAR */
    "47",  /* UNIT_MUTE_MONTRUCK */
    "64",  /* UNIT_MUTE_SCORPION */
    "38",  /* UNIT_MUTE_MASTODON */
    "4",  /* UNIT_MUTE_BEETLE */
    "16",  /* UNIT_MUTE_CRAB */
    "39",  /* UNIT_MUTE_DERRICK */
    "48",  /* UNIT_MUTE_TANKER */
    "14",  /* UNIT_MUTE_MOBILE_BASE */
    "75",  /* UNIT_SURV_DRILLRIG */
    "74",  /* UNIT_SURV_POWERPLANT */
    "52",  /* UNIT_SURV_OUTPOST */
    "37",  /* UNIT_SURV_MACHINESHOP */
    "56",  /* UNIT_SURV_REPAIRBAY */
    "57",  /* UNIT_SURV_RESEARCHLAB */
    "50",  /* UNIT_MUTE_DRILLRIG */
    "49",  /* UNIT_MUTE_POWERPLANT */
    "13",  /* UNIT_MUTE_CLANHALL */
    "8",  /* UNIT_MUTE_BLACKSMITH */
    "3",  /* UNIT_MUTE_BEASTENCLOSURE */
    "42",  /* UNIT_MUTE_MENAGERIE */
    "0",  /* UNIT_MUTE_ALCHEMYHALL */
    "67",  /* UNIT_SURV_GUARDTOWER */
    "44",  /* UNIT_SURV_MISSILEBATTERY */
    "12",  /* UNIT_SURV_CANNONTOWER */
    "43",  /* UNIT_MUTE_MACHGUNNEST */
    "29",  /* UNIT_MUTE_GRAPESHOT */
    "61",  /* UNIT_MUTE_ROTARYCANNON */
    "83",  /* UNIT_SURV_BOMBER */
    "82",  /* UNIT_MUTE_WASP */
};

const state_t states[NUMSTATES] = {
    { 0, 0, -1, NULL, S_NULL, 0 },  /* S_NULL */
    { SPR_SURV_RIFLEMAN, 0, -1, NULL, S_SURV_RIFLEMAN_STND, 0 },  /* S_SURV_RIFLEMAN_STND */
    { SPR_SURV_FLAMER, 0, -1, NULL, S_SURV_FLAMER_STND, 0 },  /* S_SURV_FLAMER_STND */
    { SPR_SURV_SWAT, 0, -1, NULL, S_SURV_SWAT_STND, 0 },  /* S_SURV_SWAT_STND */
    { SPR_SURV_SAPPER, 0, -1, NULL, S_SURV_SAPPER_STND, 0 },  /* S_SURV_SAPPER_STND */
    { SPR_SURV_SABOTEUR, 0, -1, NULL, S_SURV_SABOTEUR_STND, 0 },  /* S_SURV_SABOTEUR_STND */
    { SPR_SURV_TECHNICIAN, 0, -1, NULL, S_SURV_TECHNICIAN_STND, 0 },  /* S_SURV_TECHNICIAN_STND */
    { SPR_SURV_RPG_LAUNCHER, 0, -1, NULL, S_SURV_RPG_LAUNCHER_STND, 0 },  /* S_SURV_RPG_LAUNCHER_STND */
    { SPR_SURV_SNIPER, 0, -1, NULL, S_SURV_SNIPER_STND, 0 },  /* S_SURV_SNIPER_STND */
    { SPR_MUTE_BERSERKER, 0, -1, NULL, S_MUTE_BERSERKER_STND, 0 },  /* S_MUTE_BERSERKER_STND */
    { SPR_MUTE_PYROMANIAC, 0, -1, NULL, S_MUTE_PYROMANIAC_STND, 0 },  /* S_MUTE_PYROMANIAC_STND */
    { SPR_MUTE_SHOTGUNNER, 0, -1, NULL, S_MUTE_SHOTGUNNER_STND, 0 },  /* S_MUTE_SHOTGUNNER_STND */
    { SPR_MUTE_RIOTER, 0, -1, NULL, S_MUTE_RIOTER_STND, 0 },  /* S_MUTE_RIOTER_STND */
    { SPR_MUTE_VANDAL, 0, -1, NULL, S_MUTE_VANDAL_STND, 0 },  /* S_MUTE_VANDAL_STND */
    { SPR_MUTE_MEKANIK, 0, -1, NULL, S_MUTE_MEKANIK_STND, 0 },  /* S_MUTE_MEKANIK_STND */
    { SPR_MUTE_BAZOOKA, 0, -1, NULL, S_MUTE_BAZOOKA_STND, 0 },  /* S_MUTE_BAZOOKA_STND */
    { SPR_MUTE_CRAZY_HARRY, 0, -1, NULL, S_MUTE_CRAZY_HARRY_STND, 0 },  /* S_MUTE_CRAZY_HARRY_STND */
    { SPR_SURV_DIRT_BIKE, 0, -1, NULL, S_SURV_DIRT_BIKE_STND, 0 },  /* S_SURV_DIRT_BIKE_STND */
    { SPR_SURV_4X4_PICKUP, 0, -1, NULL, S_SURV_4X4_PICKUP_STND, 0 },  /* S_SURV_4X4_PICKUP_STND */
    { SPR_SURV_ATV, 0, -1, NULL, S_SURV_ATV_STND, 0 },  /* S_SURV_ATV_STND */
    { SPR_SURV_ATV_FLAMETHROWER, 0, -1, NULL, S_SURV_ATV_FLAMETHROWER_STND, 0 },  /* S_SURV_ATV_FLAMETHROWER_STND */
    { SPR_SURV_ANACONDA_TANK, 0, -1, NULL, S_SURV_ANACONDA_TANK_STND, 0 },  /* S_SURV_ANACONDA_TANK_STND */
    { SPR_SURV_BARRAGE_CRAFT, 0, -1, NULL, S_SURV_BARRAGE_CRAFT_STND, 0 },  /* S_SURV_BARRAGE_CRAFT_STND */
    { SPR_SURV_AUTOCANNON_TANK, 0, -1, NULL, S_SURV_AUTOCANNON_TANK_STND, 0 },  /* S_SURV_AUTOCANNON_TANK_STND */
    { SPR_SURV_MOBILE_DERRICK, 0, -1, NULL, S_SURV_MOBILE_DERRICK_STND, 0 },  /* S_SURV_MOBILE_DERRICK_STND */
    { SPR_SURV_OIL_TANKER, 0, -1, NULL, S_SURV_OIL_TANKER_STND, 0 },  /* S_SURV_OIL_TANKER_STND */
    { SPR_SURV_MOBILE_OUTPOST, 0, -1, NULL, S_SURV_MOBILE_OUTPOST_STND, 0 },  /* S_SURV_MOBILE_OUTPOST_STND */
    { SPR_MUTE_DIRE_WOLF, 0, -1, NULL, S_MUTE_DIRE_WOLF_STND, 0 },  /* S_MUTE_DIRE_WOLF_STND */
    { SPR_MUTE_BIKE_SIDECAR, 0, -1, NULL, S_MUTE_BIKE_SIDECAR_STND, 0 },  /* S_MUTE_BIKE_SIDECAR_STND */
    { SPR_MUTE_MONSTER_TRUCK, 0, -1, NULL, S_MUTE_MONSTER_TRUCK_STND, 0 },  /* S_MUTE_MONSTER_TRUCK_STND */
    { SPR_MUTE_GIANT_SCORPION, 0, -1, NULL, S_MUTE_GIANT_SCORPION_STND, 0 },  /* S_MUTE_GIANT_SCORPION_STND */
    { SPR_MUTE_WAR_MASTADONT, 0, -1, NULL, S_MUTE_WAR_MASTADONT_STND, 0 },  /* S_MUTE_WAR_MASTADONT_STND */
    { SPR_MUTE_GIANT_BEETLE, 0, -1, NULL, S_MUTE_GIANT_BEETLE_STND, 0 },  /* S_MUTE_GIANT_BEETLE_STND */
    { SPR_MUTE_MISSILE_CRAB, 0, -1, NULL, S_MUTE_MISSILE_CRAB_STND, 0 },  /* S_MUTE_MISSILE_CRAB_STND */
    { SPR_MUTE_MOBILE_DERRICK, 0, -1, NULL, S_MUTE_MOBILE_DERRICK_STND, 0 },  /* S_MUTE_MOBILE_DERRICK_STND */
    { SPR_MUTE_OIL_TANKER, 0, -1, NULL, S_MUTE_OIL_TANKER_STND, 0 },  /* S_MUTE_OIL_TANKER_STND */
    { SPR_MUTE_CLANHALL_WAGON, 0, -1, NULL, S_MUTE_CLANHALL_WAGON_STND, 0 },  /* S_MUTE_CLANHALL_WAGON_STND */
    { SPR_SURV_DRILLRIG, 0, -1, NULL, S_SURV_DRILLRIG_STND, 0 },  /* S_SURV_DRILLRIG_STND */
    { SPR_SURV_POWER_STATION, 0, -1, NULL, S_SURV_POWER_STATION_STND, 0 },  /* S_SURV_POWER_STATION_STND */
    { SPR_SURV_OUTPOST, 0, -1, NULL, S_SURV_OUTPOST_STND, 0 },  /* S_SURV_OUTPOST_STND */
    { SPR_SURV_MACHINE_SHOP, 0, -1, NULL, S_SURV_MACHINE_SHOP_STND, 0 },  /* S_SURV_MACHINE_SHOP_STND */
    { SPR_SURV_REPAIR_BAY, 0, -1, NULL, S_SURV_REPAIR_BAY_STND, 0 },  /* S_SURV_REPAIR_BAY_STND */
    { SPR_SURV_RESEARCH_LAB, 0, -1, NULL, S_SURV_RESEARCH_LAB_STND, 0 },  /* S_SURV_RESEARCH_LAB_STND */
    { SPR_MUTE_DRILLRIG, 0, -1, NULL, S_MUTE_DRILLRIG_STND, 0 },  /* S_MUTE_DRILLRIG_STND */
    { SPR_MUTE_POWER_STATION, 0, -1, NULL, S_MUTE_POWER_STATION_STND, 0 },  /* S_MUTE_POWER_STATION_STND */
    { SPR_MUTE_CLANHALL, 0, -1, NULL, S_MUTE_CLANHALL_STND, 0 },  /* S_MUTE_CLANHALL_STND */
    { SPR_MUTE_BLACKSMITH, 0, -1, NULL, S_MUTE_BLACKSMITH_STND, 0 },  /* S_MUTE_BLACKSMITH_STND */
    { SPR_MUTE_BEAST_ENCLOSURE, 0, -1, NULL, S_MUTE_BEAST_ENCLOSURE_STND, 0 },  /* S_MUTE_BEAST_ENCLOSURE_STND */
    { SPR_MUTE_MENAGERIE, 0, -1, NULL, S_MUTE_MENAGERIE_STND, 0 },  /* S_MUTE_MENAGERIE_STND */
    { SPR_MUTE_ALCHEMY_HALL, 0, -1, NULL, S_MUTE_ALCHEMY_HALL_STND, 0 },  /* S_MUTE_ALCHEMY_HALL_STND */
    { SPR_SURV_GUARD_TOWER, 0, -1, NULL, S_SURV_GUARD_TOWER_STND, 0 },  /* S_SURV_GUARD_TOWER_STND */
    { SPR_SURV_MISSILE_BATTERY, 0, -1, NULL, S_SURV_MISSILE_BATTERY_STND, 0 },  /* S_SURV_MISSILE_BATTERY_STND */
    { SPR_SURV_CANNON_TOWER, 0, -1, NULL, S_SURV_CANNON_TOWER_STND, 0 },  /* S_SURV_CANNON_TOWER_STND */
    { SPR_MUTE_MACHINEGUN_NEST, 0, -1, NULL, S_MUTE_MACHINEGUN_NEST_STND, 0 },  /* S_MUTE_MACHINEGUN_NEST_STND */
    { SPR_MUTE_GRAPESHOT_TOWER, 0, -1, NULL, S_MUTE_GRAPESHOT_TOWER_STND, 0 },  /* S_MUTE_GRAPESHOT_TOWER_STND */
    { SPR_MUTE_ROTARY_CANNON, 0, -1, NULL, S_MUTE_ROTARY_CANNON_STND, 0 },  /* S_MUTE_ROTARY_CANNON_STND */
    { SPR_SURV_BOMBER, 0, -1, NULL, S_SURV_BOMBER_STND, 0 },  /* S_SURV_BOMBER_STND */
    { SPR_MUTE_WASP, 0, -1, NULL, S_MUTE_WASP_STND, 0 },  /* S_MUTE_WASP_STND */
};

/* Stats from UNITS.CFG; doomednum = UNIT_STATS_* id. */
const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {
    { // MT_NULL
        0,
    },
    { // MT_SURV_RIFLEMAN  (UNIT_SURV_INFANTRY)
        .doomednum    = 0,
        .spawnstate   = S_SURV_RIFLEMAN_STND,
        .spawnhealth  = 400,
        .seestate     = S_SURV_RIFLEMAN_STND,
        .missilestate = S_SURV_RIFLEMAN_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_FLAMER  (UNIT_SURV_FLAMER)
        .doomednum    = 2,
        .spawnstate   = S_SURV_FLAMER_STND,
        .spawnhealth  = 400,
        .seestate     = S_SURV_FLAMER_STND,
        .missilestate = S_SURV_FLAMER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 15,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_SWAT  (UNIT_SURV_SWAT)
        .doomednum    = 4,
        .spawnstate   = S_SURV_SWAT_STND,
        .spawnhealth  = 500,
        .seestate     = S_SURV_SWAT_STND,
        .missilestate = S_SURV_SWAT_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 70,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_SAPPER  (UNIT_SURV_SAPPER)
        .doomednum    = 6,
        .spawnstate   = S_SURV_SAPPER_STND,
        .spawnhealth  = 500,
        .seestate     = S_SURV_SAPPER_STND,
        .missilestate = S_SURV_SAPPER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 90,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_SABOTEUR  (UNIT_SURV_SABOTEUR)
        .doomednum    = 10,
        .spawnstate   = S_SURV_SABOTEUR_STND,
        .spawnhealth  = 600,
        .seestate     = S_SURV_SABOTEUR_STND,
        .missilestate = S_SURV_SABOTEUR_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 12, .height = 24, .mass = 100,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_TECHNICIAN  (UNIT_SURV_TECHNICIAN)
        .doomednum    = 12,
        .spawnstate   = S_SURV_TECHNICIAN_STND,
        .spawnhealth  = 500,
        .seestate     = S_SURV_TECHNICIAN_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 12, .height = 24, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_SURV_RPG_LAUNCHER  (UNIT_SURV_ROCKETLAUNCHER)
        .doomednum    = 14,
        .spawnstate   = S_SURV_RPG_LAUNCHER_STND,
        .spawnhealth  = 400,
        .seestate     = S_SURV_RPG_LAUNCHER_STND,
        .missilestate = S_SURV_RPG_LAUNCHER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 80,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_SNIPER  (UNIT_SURV_SNIPER)
        .doomednum    = 16,
        .spawnstate   = S_SURV_SNIPER_STND,
        .spawnhealth  = 600,
        .seestate     = S_SURV_SNIPER_STND,
        .missilestate = S_SURV_SNIPER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 12, .height = 24, .mass = 100,
        .damage = 250,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_BERSERKER  (UNIT_MUTE_BERSERKER)
        .doomednum    = 1,
        .spawnstate   = S_MUTE_BERSERKER_STND,
        .spawnhealth  = 320,
        .seestate     = S_MUTE_BERSERKER_STND,
        .missilestate = S_MUTE_BERSERKER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_PYROMANIAC  (UNIT_MUTE_PYRO)
        .doomednum    = 3,
        .spawnstate   = S_MUTE_PYROMANIAC_STND,
        .spawnhealth  = 400,
        .seestate     = S_MUTE_PYROMANIAC_STND,
        .missilestate = S_MUTE_PYROMANIAC_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 15,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_SHOTGUNNER  (UNIT_MUTE_SHOTGUNNER)
        .doomednum    = 5,
        .spawnstate   = S_MUTE_SHOTGUNNER_STND,
        .spawnhealth  = 500,
        .seestate     = S_MUTE_SHOTGUNNER_STND,
        .missilestate = S_MUTE_SHOTGUNNER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 70,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_RIOTER  (UNIT_MUTE_RIOTER)
        .doomednum    = 7,
        .spawnstate   = S_MUTE_RIOTER_STND,
        .spawnhealth  = 500,
        .seestate     = S_MUTE_RIOTER_STND,
        .missilestate = S_MUTE_RIOTER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 90,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_VANDAL  (UNIT_MUTE_VANDAL)
        .doomednum    = 11,
        .spawnstate   = S_MUTE_VANDAL_STND,
        .spawnhealth  = 600,
        .seestate     = S_MUTE_VANDAL_STND,
        .missilestate = S_MUTE_VANDAL_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 12, .height = 24, .mass = 100,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_MEKANIK  (UNIT_MUTE_TECHNICIAN)
        .doomednum    = 13,
        .spawnstate   = S_MUTE_MEKANIK_STND,
        .spawnhealth  = 500,
        .seestate     = S_MUTE_MEKANIK_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 12, .height = 24, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_MUTE_BAZOOKA  (UNIT_MUTE_ROCKETLAUNCHER)
        .doomednum    = 15,
        .spawnstate   = S_MUTE_BAZOOKA_STND,
        .spawnhealth  = 400,
        .seestate     = S_MUTE_BAZOOKA_STND,
        .missilestate = S_MUTE_BAZOOKA_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 80,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_CRAZY_HARRY  (UNIT_MUTE_CRAZYHARRY)
        .doomednum    = 17,
        .spawnstate   = S_MUTE_CRAZY_HARRY_STND,
        .spawnhealth  = 500,
        .seestate     = S_MUTE_CRAZY_HARRY_STND,
        .missilestate = S_MUTE_CRAZY_HARRY_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 12, .height = 24, .mass = 100,
        .damage = 250,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_DIRT_BIKE  (UNIT_SURV_BIKE)
        .doomednum    = 26,
        .spawnstate   = S_SURV_DIRT_BIKE_STND,
        .spawnhealth  = 500,
        .seestate     = S_SURV_DIRT_BIKE_STND,
        .missilestate = S_SURV_DIRT_BIKE_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 80, .radius = 16, .height = 24, .mass = 200,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_4X4_PICKUP  (UNIT_SURV_PICKUP)
        .doomednum    = 28,
        .spawnstate   = S_SURV_4X4_PICKUP_STND,
        .spawnhealth  = 800,
        .seestate     = S_SURV_4X4_PICKUP_STND,
        .missilestate = S_SURV_4X4_PICKUP_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 70, .radius = 16, .height = 24, .mass = 300,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_ATV  (UNIT_SURV_ATV)
        .doomednum    = 30,
        .spawnstate   = S_SURV_ATV_STND,
        .spawnhealth  = 1200,
        .seestate     = S_SURV_ATV_STND,
        .missilestate = S_SURV_ATV_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 60, .radius = 20, .height = 28, .mass = 400,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_ATV_FLAMETHROWER  (UNIT_SURV_FLAMEATV)
        .doomednum    = 32,
        .spawnstate   = S_SURV_ATV_FLAMETHROWER_STND,
        .spawnhealth  = 1200,
        .seestate     = S_SURV_ATV_FLAMETHROWER_STND,
        .missilestate = S_SURV_ATV_FLAMETHROWER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 55, .radius = 20, .height = 28, .mass = 400,
        .damage = 15,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_ANACONDA_TANK  (UNIT_SURV_ANACONDA)
        .doomednum    = 34,
        .spawnstate   = S_SURV_ANACONDA_TANK_STND,
        .spawnhealth  = 1600,
        .seestate     = S_SURV_ANACONDA_TANK_STND,
        .missilestate = S_SURV_ANACONDA_TANK_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 45, .radius = 24, .height = 32, .mass = 500,
        .damage = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_BARRAGE_CRAFT  (UNIT_SURV_BARAGECRAFT)
        .doomednum    = 36,
        .spawnstate   = S_SURV_BARRAGE_CRAFT_STND,
        .spawnhealth  = 1800,
        .seestate     = S_SURV_BARRAGE_CRAFT_STND,
        .missilestate = S_SURV_BARRAGE_CRAFT_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 24, .height = 32, .mass = 600,
        .damage = 150,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_AUTOCANNON_TANK  (UNIT_SURV_CANNONTANK)
        .doomednum    = 38,
        .spawnstate   = S_SURV_AUTOCANNON_TANK_STND,
        .spawnhealth  = 1700,
        .seestate     = S_SURV_AUTOCANNON_TANK_STND,
        .missilestate = S_SURV_AUTOCANNON_TANK_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 24, .height = 32, .mass = 600,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_MOBILE_DERRICK  (UNIT_SURV_DERRICK)
        .doomednum    = 21,
        .spawnstate   = S_SURV_MOBILE_DERRICK_STND,
        .spawnhealth  = 4000,
        .seestate     = S_SURV_MOBILE_DERRICK_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 24, .height = 32, .mass = 800,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_SURV_OIL_TANKER  (UNIT_SURV_TANKER)
        .doomednum    = 23,
        .spawnstate   = S_SURV_OIL_TANKER_STND,
        .spawnhealth  = 3000,
        .seestate     = S_SURV_OIL_TANKER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 24, .height = 32, .mass = 600,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_SURV_MOBILE_OUTPOST  (UNIT_SURV_MOBILE_BASE)
        .doomednum    = 40,
        .spawnstate   = S_SURV_MOBILE_OUTPOST_STND,
        .spawnhealth  = 6000,
        .seestate     = S_SURV_MOBILE_OUTPOST_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 20, .radius = 32, .height = 40, .mass = 1000,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_MUTE_DIRE_WOLF  (UNIT_MUTE_WOLF)
        .doomednum    = 27,
        .spawnstate   = S_MUTE_DIRE_WOLF_STND,
        .spawnhealth  = 600,
        .seestate     = S_MUTE_DIRE_WOLF_STND,
        .missilestate = S_MUTE_DIRE_WOLF_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 75, .radius = 16, .height = 24, .mass = 200,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_BIKE_SIDECAR  (UNIT_MUTE_SIDECAR)
        .doomednum    = 29,
        .spawnstate   = S_MUTE_BIKE_SIDECAR_STND,
        .spawnhealth  = 700,
        .seestate     = S_MUTE_BIKE_SIDECAR_STND,
        .missilestate = S_MUTE_BIKE_SIDECAR_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 70, .radius = 16, .height = 24, .mass = 300,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_MONSTER_TRUCK  (UNIT_MUTE_MONTRUCK)
        .doomednum    = 31,
        .spawnstate   = S_MUTE_MONSTER_TRUCK_STND,
        .spawnhealth  = 1000,
        .seestate     = S_MUTE_MONSTER_TRUCK_STND,
        .missilestate = S_MUTE_MONSTER_TRUCK_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 55, .radius = 20, .height = 28, .mass = 400,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_GIANT_SCORPION  (UNIT_MUTE_SCORPION)
        .doomednum    = 33,
        .spawnstate   = S_MUTE_GIANT_SCORPION_STND,
        .spawnhealth  = 1000,
        .seestate     = S_MUTE_GIANT_SCORPION_STND,
        .missilestate = S_MUTE_GIANT_SCORPION_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 45, .radius = 20, .height = 28, .mass = 400,
        .damage = 50,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_WAR_MASTADONT  (UNIT_MUTE_MASTODON)
        .doomednum    = 35,
        .spawnstate   = S_MUTE_WAR_MASTADONT_STND,
        .spawnhealth  = 1600,
        .seestate     = S_MUTE_WAR_MASTADONT_STND,
        .missilestate = S_MUTE_WAR_MASTADONT_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 24, .height = 32, .mass = 500,
        .damage = 25,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_GIANT_BEETLE  (UNIT_MUTE_BEETLE)
        .doomednum    = 37,
        .spawnstate   = S_MUTE_GIANT_BEETLE_STND,
        .spawnhealth  = 1200,
        .seestate     = S_MUTE_GIANT_BEETLE_STND,
        .missilestate = S_MUTE_GIANT_BEETLE_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 24, .height = 32, .mass = 600,
        .damage = 50,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_MISSILE_CRAB  (UNIT_MUTE_CRAB)
        .doomednum    = 39,
        .spawnstate   = S_MUTE_MISSILE_CRAB_STND,
        .spawnhealth  = 1800,
        .seestate     = S_MUTE_MISSILE_CRAB_STND,
        .missilestate = S_MUTE_MISSILE_CRAB_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 24, .height = 32, .mass = 600,
        .damage = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_MOBILE_DERRICK  (UNIT_MUTE_DERRICK)
        .doomednum    = 22,
        .spawnstate   = S_MUTE_MOBILE_DERRICK_STND,
        .spawnhealth  = 4000,
        .seestate     = S_MUTE_MOBILE_DERRICK_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 30, .radius = 24, .height = 32, .mass = 800,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_MUTE_OIL_TANKER  (UNIT_MUTE_TANKER)
        .doomednum    = 24,
        .spawnstate   = S_MUTE_OIL_TANKER_STND,
        .spawnhealth  = 3000,
        .seestate     = S_MUTE_OIL_TANKER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 35, .radius = 24, .height = 32, .mass = 600,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_MUTE_CLANHALL_WAGON  (UNIT_MUTE_MOBILE_BASE)
        .doomednum    = 41,
        .spawnstate   = S_MUTE_CLANHALL_WAGON_STND,
        .spawnhealth  = 6000,
        .seestate     = S_MUTE_CLANHALL_WAGON_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 20, .radius = 32, .height = 40, .mass = 1000,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_SURV_DRILLRIG  (UNIT_SURV_DRILLRIG)
        .doomednum    = 46,
        .spawnstate   = S_SURV_DRILLRIG_STND,
        .spawnhealth  = 4000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_SURV_POWER_STATION  (UNIT_SURV_POWERPLANT)
        .doomednum    = 48,
        .spawnstate   = S_SURV_POWER_STATION_STND,
        .spawnhealth  = 4000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_SURV_OUTPOST  (UNIT_SURV_OUTPOST)
        .doomednum    = 58,
        .spawnstate   = S_SURV_OUTPOST_STND,
        .spawnhealth  = 6000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_SURV_MACHINE_SHOP  (UNIT_SURV_MACHINESHOP)
        .doomednum    = 60,
        .spawnstate   = S_SURV_MACHINE_SHOP_STND,
        .spawnhealth  = 4000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_SURV_REPAIR_BAY  (UNIT_SURV_REPAIRBAY)
        .doomednum    = 63,
        .spawnstate   = S_SURV_REPAIR_BAY_STND,
        .spawnhealth  = 3000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_SURV_RESEARCH_LAB  (UNIT_SURV_RESEARCHLAB)
        .doomednum    = 65,
        .spawnstate   = S_SURV_RESEARCH_LAB_STND,
        .spawnhealth  = 3000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_MUTE_DRILLRIG  (UNIT_MUTE_DRILLRIG)
        .doomednum    = 47,
        .spawnstate   = S_MUTE_DRILLRIG_STND,
        .spawnhealth  = 4000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_MUTE_POWER_STATION  (UNIT_MUTE_POWERPLANT)
        .doomednum    = 49,
        .spawnstate   = S_MUTE_POWER_STATION_STND,
        .spawnhealth  = 4000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_MUTE_CLANHALL  (UNIT_MUTE_CLANHALL)
        .doomednum    = 59,
        .spawnstate   = S_MUTE_CLANHALL_STND,
        .spawnhealth  = 6000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_MUTE_BLACKSMITH  (UNIT_MUTE_BLACKSMITH)
        .doomednum    = 61,
        .spawnstate   = S_MUTE_BLACKSMITH_STND,
        .spawnhealth  = 3200,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_MUTE_BEAST_ENCLOSURE  (UNIT_MUTE_BEASTENCLOSURE)
        .doomednum    = 62,
        .spawnstate   = S_MUTE_BEAST_ENCLOSURE_STND,
        .spawnhealth  = 3200,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_MUTE_MENAGERIE  (UNIT_MUTE_MENAGERIE)
        .doomednum    = 64,
        .spawnstate   = S_MUTE_MENAGERIE_STND,
        .spawnhealth  = 3000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_MUTE_ALCHEMY_HALL  (UNIT_MUTE_ALCHEMYHALL)
        .doomednum    = 66,
        .spawnstate   = S_MUTE_ALCHEMY_HALL_STND,
        .spawnhealth  = 3000,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_SURV_GUARD_TOWER  (UNIT_SURV_GUARDTOWER)
        .doomednum    = 52,
        .spawnstate   = S_SURV_GUARD_TOWER_STND,
        .spawnhealth  = 1200,
        .missilestate = S_SURV_GUARD_TOWER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_MISSILE_BATTERY  (UNIT_SURV_MISSILEBATTERY)
        .doomednum    = 56,
        .spawnstate   = S_SURV_MISSILE_BATTERY_STND,
        .spawnhealth  = 1800,
        .missilestate = S_SURV_MISSILE_BATTERY_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 150,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_CANNON_TOWER  (UNIT_SURV_CANNONTOWER)
        .doomednum    = 54,
        .spawnstate   = S_SURV_CANNON_TOWER_STND,
        .spawnhealth  = 2400,
        .missilestate = S_SURV_CANNON_TOWER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 80,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_MACHINEGUN_NEST  (UNIT_MUTE_MACHGUNNEST)
        .doomednum    = 53,
        .spawnstate   = S_MUTE_MACHINEGUN_NEST_STND,
        .spawnhealth  = 1200,
        .missilestate = S_MUTE_MACHINEGUN_NEST_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_GRAPESHOT_TOWER  (UNIT_MUTE_GRAPESHOT)
        .doomednum    = 55,
        .spawnstate   = S_MUTE_GRAPESHOT_TOWER_STND,
        .spawnhealth  = 1800,
        .missilestate = S_MUTE_GRAPESHOT_TOWER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 20,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_MUTE_ROTARY_CANNON  (UNIT_MUTE_ROTARYCANNON)
        .doomednum    = 57,
        .spawnstate   = S_MUTE_ROTARY_CANNON_STND,
        .spawnhealth  = 2500,
        .missilestate = S_MUTE_ROTARY_CANNON_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SURV_BOMBER  (UNIT_SURV_BOMBER)
        .doomednum    = 44,
        .spawnstate   = S_SURV_BOMBER_STND,
        .spawnhealth  = 1500,
        .seestate     = S_SURV_BOMBER_STND,
        .missilestate = S_SURV_BOMBER_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 120, .radius = 20, .height = 16, .mass = 200,
        .damage = 2000,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY,
    },
    { // MT_MUTE_WASP  (UNIT_MUTE_WASP)
        .doomednum    = 43,
        .spawnstate   = S_MUTE_WASP_STND,
        .spawnhealth  = 1500,
        .seestate     = S_MUTE_WASP_STND,
        .missilestate = S_MUTE_WASP_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .speed = 120, .radius = 20, .height = 16, .mass = 200,
        .damage = 2000,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY,
    },
};

const gameinfo_t game_info = {
    sprnames,
    NUMSPRITES,
    states,
    NUMSTATES,
    mobjinfo,
    NUMMOBJTYPES,
    S_NULL,
    RTS_STATE_COORDS_GROUND_OFFSET,
    { .style = SELECTION_STYLE_CIRCLE },
    NULL,
};
