#define OWNER_PRODUCER MT_FG_CONSTRUCTION_CREW
#define PLAYER_PRODUCER MT_FG_CONSTRUCTION_CREW
#define PLAYER_PRODUCT 10001
#define AI_FIRST_UNIT MT_FG_HQ1
#define AI_FIRST_COUNT 1
#define AI_ADVANCED_UNIT MT_FG_MEDIUM_TANK
#define AI_ADVANCED_COUNT 2
#include "../production_regression.h"
