/* Authored gameplay tables; FIN animation extraction lives in tools/dc_info_conv/. */
#include "engine.h"
#include "info.h"

const char *const sprnames[NUMSPRITES] = {
    "DROP3", "DROP4", "ACAR", "ACOM", "AIRD", "ALBU", "ALIEN1", "ARTILER2",
    "ARTY", "ATRIL", "ATTACK2", "AVII", "BARR", "BBIT", "BEAC", "BEES",
    "BEON", "BIGC", "BITS", "BLAH", "BLAM", "BLAZ", "BLOO", "BOIG", "BRIT",
    "BUILDNG", "CAMM", "CENT", "CHAA", "CHAB", "CHOA", "CHOB", "CHOC", "CHOD",
    "CLOC", "CLOD", "CRYO", "CURS", "CYBORG", "DCSS", "DCUK", "DCUT", "DISH",
    "DOTT", "DROA", "DROP", "DSTY", "DUTS", "EGG", "ENCA", "ENCB", "ENCC",
    "ENCD", "ENCE", "ENCF", "ENGI", "EXPL", "FACT", "FETU", "FILL", "FIRA",
    "FIRB", "FIRE", "FLUCTION", "FRIEGHT", "FUEL", "GASY", "GLAT", "GLIT",
    "GLOT", "GRAY", "GRND", "GRUB", "HCAR", "HCOM", "HITA", "HITB", "HITC",
    "HITD", "HITE", "HITF", "HITG", "HITH", "HITT", "HUBU", "HYYK", "IT",
    "KNOBE", "LEFT", "LENS", "LEVEL", "LLLL", "LUNA", "LUNY", "MAKT",
    "MATATRAC", "MISA", "MISB", "MISC", "MISD", "MISE", "MISF", "MISG",
    "MISH", "MORE", "MSLS", "MUZA", "MWIA", "MWIB", "MWIC", "MWID", "NETA",
    "NETB", "NETC", "NETD", "NETE", "NUKE", "ORTU", "PCFO", "PLASMA", "POPP",
    "POPPPAEN", "PORT", "PSYC", "PUFF", "PUSB", "REAP", "RNAT", "SALA",
    "SALY", "SARG", "SAUC", "SCGM", "SCOU", "SCOUT1", "SCUT", "SCYT", "SERA",
    "SERB", "SERC", "SERD", "SERE", "SHOK", "SHORTCIT", "SHRI", "SIDE",
    "SLOM", "SLUG", "SMAE", "SMAY", "SMOA", "SMOK", "SMSP", "SONIC", "SPAC",
    "SPAK", "SPAR", "SPED", "SPID", "SPIKE", "SPON", "SPOT", "SPUC", "SRCH",
    "SSSS", "TEKT", "TEKTARA", "TIMEMIS", "TONG", "TORT", "TOWR", "TOXX",
    "TROOPER1", "TROOPER2", "TRSC", "TRUK", "TURR", "VCAL", "VCEA", "VENT",
    "VENT2", "WATC", "WEATH", "WINA", "WINB", "WINC", "WIND", "WINE", "WINF",
    "XENO", "YABA", "ZISP", "BURN", "BURN2",
};

#define A_None NULL

const state_t states[NUMSTATES] = {
    { 0, 0, -1, A_None, S_NULL, 0 },
    /* EXCOPODSTAND0: complete native FIN sequence. */
    { SPR_HUBU, 19, 5, A_DC_BuildingStand, S_EXCOPOD_STND_2, 1 },
    { SPR_HUBU, 20, 4, A_DC_BuildingStand, S_EXCOPOD_STND_3, 1 },
    { SPR_HUBU, 21, 5, A_DC_BuildingStand, S_EXCOPOD_STND_4, 1 },
    { SPR_HUBU, 22, 5, A_DC_BuildingStand, S_EXCOPOD_STND_5, 1 },
    { SPR_HUBU, 23, 5, A_DC_BuildingStand, S_EXCOPOD_STND_6, 1 },
    { SPR_HUBU, 24, 4, A_DC_BuildingStand, S_EXCOPOD_STND_7, 1 },
    { SPR_HUBU, 25, 5, A_DC_BuildingStand, S_EXCOPOD_STND_8, 1 },
    { SPR_HUBU, 26, 5, A_DC_BuildingStand, S_EXCOPOD_STND, 1 },
    /* BRRKPODSTAND0: complete native FIN sequence. */
    { SPR_HUBU, 38, 5, A_DC_ProductionReady, S_BRRKPOD_STND_2, 1 },
    { SPR_HUBU, 39, 4, A_DC_BuildingStand, S_BRRKPOD_STND, 1 },
    /* TOWRSTAND0: complete native FIN frame. */
    { SPR_TOWR, 1, -1, A_None, S_TOWR_STND, 1 },
    /* TRSCBUILD0: complete FIN sequence at the native 66 ms tick. */
    { SPR_HUBU, 45, 2, A_None, S_BRRKPOD_BUILD_TRSC2, 6 },
    { SPR_HUBU, 46, 2, A_None, S_BRRKPOD_BUILD_TRSC3, 6 },
    { SPR_HUBU, 47, 2, A_None, S_BRRKPOD_BUILD_TRSC4, 6 },
    { SPR_HUBU, 48, 2, A_None, S_BRRKPOD_BUILD_TRSC5, 6 },
    { SPR_HUBU, 49, 2, A_None, S_BRRKPOD_BUILD_TRSC6, 6 },
    { SPR_HUBU, 50, 2, A_None, S_BRRKPOD_BUILD_TRSC7, 6 },
    { SPR_HUBU, 51, 2, A_None, S_BRRKPOD_BUILD_TRSC8, 6 },
    { SPR_HUBU, 52, 2, A_None, S_BRRKPOD_BUILD_TRSC9, 6 },
    { SPR_HUBU, 53, 2, A_None, S_BRRKPOD_BUILD_TRSC10, 6 },
    { SPR_HUBU, 54, 2, A_None, S_BRRKPOD_BUILD_TRSC11, 6 },
    { SPR_HUBU, 55, 2, A_None, S_BRRKPOD_BUILD_TRSC12, 6 },
    { SPR_HUBU, 56, 2, A_None, S_BRRKPOD_BUILD_TRSC13, 6 },
    { SPR_HUBU, 57, 2, A_None, S_BRRKPOD_BUILD_TRSC14, 6 },
    { SPR_HUBU, 58, 2, A_None, S_BRRKPOD_BUILD_TRSC15, 6 },
    { SPR_HUBU, 59, 2, A_None, S_BRRKPOD_BUILD_TRSC16, 6 },
    { SPR_HUBU, 60, 2, A_None, S_BRRKPOD_BUILD_TRSC17, 6 },
    { SPR_HUBU, 61, 2, A_None, S_BRRKPOD_BUILD_TRSC18, 6 },
    { SPR_HUBU, 62, 2, A_None, S_BRRKPOD_BUILD_TRSC19, 6 },
    { SPR_HUBU, 63, 2, A_None, S_BRRKPOD_BUILD_TRSC20, 6 },
    { SPR_HUBU, 64, 2, A_None, S_BRRKPOD_BUILD_TRSC21, 6 },
    { SPR_HUBU, 65, 2, A_None, S_BRRKPOD_BUILD_TRSC22, 6 },
    { SPR_HUBU, 66, 2, A_None, S_BRRKPOD_STND, 6 },
    { SPR_TRSC, 209, 1, A_Look, S_TRSC_STND, 1 },
    { SPR_TRSC, 225, 3, A_Chase, S_TRSC_RUN2, 2 },
    { SPR_TRSC, 226, 3, A_Chase, S_TRSC_RUN3, 2 },
    { SPR_TRSC, 227, 3, A_Chase, S_TRSC_RUN4, 2 },
    { SPR_TRSC, 228, 3, A_Chase, S_TRSC_RUN5, 2 },
    { SPR_TRSC, 229, 3, A_Chase, S_TRSC_RUN6, 2 },
    { SPR_TRSC, 230, 3, A_Chase, S_TRSC_RUN7, 2 },
    { SPR_TRSC, 231, 3, A_Chase, S_TRSC_RUN8, 2 },
    { SPR_TRSC, 232, 3, A_Chase, S_TRSC_RUN1, 2 },
    { SPR_TRSC, 297, 2, A_None, S_TRSC_ATK2, 3 },
    { SPR_TRSC, 298, 2, A_None, S_TRSC_ATK3, 3 },
    { SPR_TRSC, 299, 2, A_Attack, S_TRSC_ATK4, 3 },
    { SPR_TRSC, 300, 2, A_None, S_TRSC_ATK5, 3 },
    { SPR_TRSC, 301, 2, A_None, S_TRSC_ATK6, 3 },
    { SPR_TRSC, 302, 2, A_None, S_TRSC_STND, 3 },
    /* Complete TRSCDIEA14 FIN timeline, including its repeated decay frame. */
    { SPR_TRSC, 432, 5, A_None, S_TRSC_DIE2, 4 },
    { SPR_TRSC, 433, 4, A_None, S_TRSC_DIE3, 4 },
    { SPR_TRSC, 434, 5, A_None, S_TRSC_DIE4, 4 },
    { SPR_TRSC, 435, 5, A_None, S_TRSC_DIE5, 4 },
    { SPR_TRSC, 436, 5, A_None, S_TRSC_DIE6, 4 },
    { SPR_TRSC, 437, 4, A_None, S_TRSC_DIE7, 4 },
    { SPR_TRSC, 438, 76, A_None, S_TRSC_DIE8, 4 },
    { SPR_TRSC, 439, 76, A_None, S_TRSC_DIE9, 4 },
    { SPR_TRSC, 440, 43, A_None, S_TRSC_DIE10, 4 },
    { SPR_TRSC, 441, 42, A_None, S_TRSC_DIE11, 4 },
    { SPR_TRSC, 442, 43, A_None, S_TRSC_CORPSE, 4 },
    { SPR_TRSC, 442, -1, A_None, S_NULL, 4 },
    { SPR_GRAY, 292, 1, A_Look, S_GRAY_STND, 1 },
    { SPR_GRAY, 308, 3, A_Chase, S_GRAY_RUN2, 2 },
    { SPR_GRAY, 309, 3, A_Chase, S_GRAY_RUN3, 2 },
    { SPR_GRAY, 310, 3, A_Chase, S_GRAY_RUN4, 2 },
    { SPR_GRAY, 311, 3, A_Chase, S_GRAY_RUN5, 2 },
    { SPR_GRAY, 312, 3, A_Chase, S_GRAY_RUN6, 2 },
    { SPR_GRAY, 313, 3, A_Chase, S_GRAY_RUN7, 2 },
    { SPR_GRAY, 314, 3, A_Chase, S_GRAY_RUN8, 2 },
    { SPR_GRAY, 314, 3, A_Chase, S_GRAY_RUN1, 2 },
    { SPR_GRAY, 370, 2, A_None, S_GRAY_ATK2, 3 },
    { SPR_GRAY, 371, 2, A_None, S_GRAY_ATK3, 3 },
    { SPR_GRAY, 372, 2, A_Attack, S_GRAY_ATK4, 3 },
    { SPR_GRAY, 373, 2, A_None, S_GRAY_ATK5, 3 },
    { SPR_GRAY, 374, 2, A_None, S_GRAY_ATK6, 3 },
    { SPR_GRAY, 375, 2, A_None, S_GRAY_STND, 3 },
    { SPR_GRAY, 376, 2, A_None, S_GRAY_STND, 3 },
    { SPR_GRAY, 377, 2, A_None, S_GRAY_STND, 3 },
    /* Complete GRAYDIEB14 FIN timeline, including all decay holds. */
    { SPR_GRAY, 594, 2, A_None, S_GRAY_DIE2, 4 },
    { SPR_GRAY, 595, 1, A_None, S_GRAY_DIE3, 4 },
    { SPR_GRAY, 596, 2, A_None, S_GRAY_DIE4, 4 },
    { SPR_GRAY, 597, 1, A_None, S_GRAY_DIE5, 4 },
    { SPR_GRAY, 598, 2, A_None, S_GRAY_DIE6, 4 },
    { SPR_GRAY, 599, 1, A_None, S_GRAY_DIE7, 4 },
    { SPR_GRAY, 600, 2, A_None, S_GRAY_DIE8, 4 },
    { SPR_GRAY, 601, 2, A_None, S_GRAY_DIE9, 4 },
    { SPR_GRAY, 602, 75, A_None, S_GRAY_DIE10, 4 },
    { SPR_GRAY, 603, 76, A_None, S_GRAY_DIE11, 4 },
    { SPR_GRAY, 604, 76, A_None, S_GRAY_ROT1, 4 },
    { SPR_GRAY, 605, 43, A_None, S_GRAY_ROT2, 4 },
    { SPR_GRAY, 606, 42, A_None, S_GRAY_ROT3, 4 },
    { SPR_GRAY, 607, 43, A_None, S_GRAY_CORPSE, 4 },
    { SPR_GRAY, 607, -1, A_None, S_NULL, 4 },
    { SPR_REAP, 108, -1, A_None, S_REAP_STND, 1 },
    { SPR_REAP, 124, 4, A_Chase, S_REAP_RUN2, 2 },
    { SPR_REAP, 125, 3, A_Chase, S_REAP_RUN3, 2 },
    { SPR_REAP, 126, 3, A_Chase, S_REAP_RUN4, 2 },
    { SPR_REAP, 127, 4, A_Chase, S_REAP_RUN5, 2 },
    { SPR_REAP, 128, 1, A_Chase, S_REAP_RUN6, 2 },
    { SPR_REAP, 129, 3, A_Chase, S_REAP_RUN7, 2 },
    { SPR_REAP, 130, 3, A_Chase, S_REAP_RUN8, 2 },
    { SPR_REAP, 131, 1, A_Chase, S_REAP_RUN1, 2 },
    { SPR_REAP, 267, 2, A_None, S_REAP_ATK2, 3 },
    { SPR_REAP, 268, 2, A_None, S_REAP_ATK3, 3 },
    { SPR_REAP, 269, 2, A_Attack, S_REAP_ATK4, 3 },
    { SPR_REAP, 270, 2, A_None, S_REAP_ATK5, 3 },
    { SPR_REAP, 271, 2, A_None, S_REAP_STND, 3 },
    { SPR_REAP, 0, 0, A_DC_ReaperDeath, S_NULL, 4 },
    { SPR_REAP, 336, 30, A_None, S_REAP_DIEA14_2, 4 },
    { SPR_REAP, 337, 5, A_None, S_REAP_DIEA14_3, 4 },
    { SPR_REAP, 338, 4, A_None, S_REAP_DIEA14_4, 4 },
    { SPR_REAP, 339, 5, A_None, S_REAP_DIEA14_5, 4 },
    { SPR_REAP, 340, 5, A_None, S_REAP_DIEA14_6, 4 },
    { SPR_REAP, 341, 5, A_None, S_REAP_DIEA14_7, 4 },
    { SPR_REAP, 342, 4, A_None, S_REAP_DIEA14_8, 4 },
    { SPR_REAP, 343, 5, A_None, S_REAP_DIEA14_9, 4 },
    { SPR_REAP, 344, 5, A_None, S_REAP_DIEA14_10, 4 },
    { SPR_REAP, 345, 5, A_None, S_REAP_DIEA14_11, 4 },
    { SPR_REAP, 346, 4, A_None, S_REAP_DIEA14_12, 4 },
    { SPR_REAP, 347, 5, A_None, S_REAP_DIEA14_13, 4 },
    { SPR_REAP, 348, 5, A_None, S_REAP_DIEA14_14, 4 },
    { SPR_REAP, 349, 5, A_None, S_REAP_DIEA14_15, 4 },
    { SPR_REAP, 350, 4, A_None, S_REAP_DIEA14_16, 4 },
    { SPR_REAP, 351, 5, A_None, S_REAP_DIEA14_17, 4 },
    { SPR_REAP, 352, 5, A_None, S_REAP_DIEA14_18, 4 },
    { SPR_REAP, 353, 5, A_None, S_REAP_DIEA14_19, 4 },
    { SPR_REAP, 354, 4, A_None, S_REAP_DIEA14_20, 4 },
    { SPR_REAP, 355, 76, A_None, S_REAP_DIEA14_21, 4 },
    { SPR_REAP, 356, 76, A_None, S_REAP_DIEA14_22, 4 },
    { SPR_REAP, 357, 60, A_None, S_REAP_DIEA14_23, 4 },
    { SPR_REAP, 358, 76, A_None, S_REAP_DIEA14_24, 4 },
    { SPR_REAP, 359, 60, A_None, S_REAP_DIEA14_25, 4 },
    { SPR_REAP, 360, 75, A_None, S_REAP_DIEA14_26, 4 },
    { SPR_REAP, 361, 60, A_None, S_REAP_DIEA14_27, 4 },
    { SPR_REAP, 362, 76, A_None, S_REAP_DIEA14_CORPSE, 4 },
    { SPR_REAP, 362, -1, A_None, S_NULL, 4 },
    { SPR_REAP, 238, 5, A_None, S_REAP_DIEA10_2, 4 },
    { SPR_REAP, 239, 4, A_None, S_REAP_DIEA10_3, 4 },
    { SPR_REAP, 240, 5, A_None, S_REAP_DIEA10_4, 4 },
    { SPR_REAP, 241, 5, A_None, S_REAP_DIEA10_5, 4 },
    { SPR_REAP, 242, 5, A_None, S_REAP_DIEA10_6, 4 },
    { SPR_REAP, 243, 4, A_None, S_REAP_DIEA10_7, 4 },
    { SPR_REAP, 244, 5, A_None, S_REAP_DIEA10_8, 4 },
    { SPR_REAP, 245, 5, A_None, S_REAP_DIEA10_9, 4 },
    { SPR_REAP, 246, 5, A_None, S_REAP_DIEA10_10, 4 },
    { SPR_REAP, 247, 75, A_None, S_REAP_DIEA10_11, 4 },
    { SPR_REAP, 248, 76, A_None, S_REAP_DIEA10_12, 4 },
    { SPR_REAP, 249, 43, A_None, S_REAP_DIEA10_13, 4 },
    { SPR_REAP, 250, 42, A_None, S_REAP_DIEA10_14, 4 },
    { SPR_REAP, 251, 43, A_None, S_REAP_DIEA10_CORPSE, 4 },
    { SPR_REAP, 251, -1, A_None, S_NULL, 4 },
    { SPR_REAP, 363, 30, A_None, S_REAP_DIEA6_2, 4 },
    { SPR_REAP, 364, 5, A_None, S_REAP_DIEA6_3, 4 },
    { SPR_REAP, 365, 4, A_None, S_REAP_DIEA6_4, 4 },
    { SPR_REAP, 366, 5, A_None, S_REAP_DIEA6_5, 4 },
    { SPR_REAP, 367, 5, A_None, S_REAP_DIEA6_6, 4 },
    { SPR_REAP, 368, 5, A_None, S_REAP_DIEA6_7, 4 },
    { SPR_REAP, 369, 4, A_None, S_REAP_DIEA6_8, 4 },
    { SPR_REAP, 370, 5, A_None, S_REAP_DIEA6_9, 4 },
    { SPR_REAP, 371, 5, A_None, S_REAP_DIEA6_10, 4 },
    { SPR_REAP, 372, 5, A_None, S_REAP_DIEA6_11, 4 },
    { SPR_REAP, 373, 4, A_None, S_REAP_DIEA6_12, 4 },
    { SPR_REAP, 374, 5, A_None, S_REAP_DIEA6_13, 4 },
    { SPR_REAP, 375, 5, A_None, S_REAP_DIEA6_14, 4 },
    { SPR_REAP, 376, 5, A_None, S_REAP_DIEA6_15, 4 },
    { SPR_REAP, 377, 4, A_None, S_REAP_DIEA6_16, 4 },
    { SPR_REAP, 378, 5, A_None, S_REAP_DIEA6_17, 4 },
    { SPR_REAP, 379, 5, A_None, S_REAP_DIEA6_18, 4 },
    { SPR_REAP, 380, 5, A_None, S_REAP_DIEA6_19, 4 },
    { SPR_REAP, 381, 75, A_None, S_REAP_DIEA6_20, 4 },
    { SPR_REAP, 382, 76, A_None, S_REAP_DIEA6_21, 4 },
    { SPR_REAP, 383, 76, A_None, S_REAP_DIEA6_22, 4 },
    { SPR_REAP, 384, 76, A_None, S_REAP_DIEA6_23, 4 },
    { SPR_REAP, 385, 75, A_None, S_REAP_DIEA6_24, 4 },
    { SPR_REAP, 386, 76, A_None, S_REAP_DIEA6_25, 4 },
    { SPR_REAP, 387, 76, A_None, S_REAP_DIEA6_26, 4 },
    { SPR_REAP, 388, 76, A_None, S_REAP_DIEA6_CORPSE, 4 },
    { SPR_REAP, 388, -1, A_None, S_NULL, 4 },
    { SPR_REAP, 252, 5, A_None, S_REAP_DIEA2_2, 4 },
    { SPR_REAP, 253, 4, A_None, S_REAP_DIEA2_3, 4 },
    { SPR_REAP, 254, 5, A_None, S_REAP_DIEA2_4, 4 },
    { SPR_REAP, 255, 5, A_None, S_REAP_DIEA2_5, 4 },
    { SPR_REAP, 256, 5, A_None, S_REAP_DIEA2_6, 4 },
    { SPR_REAP, 257, 4, A_None, S_REAP_DIEA2_7, 4 },
    { SPR_REAP, 258, 5, A_None, S_REAP_DIEA2_8, 4 },
    { SPR_REAP, 259, 5, A_None, S_REAP_DIEA2_9, 4 },
    { SPR_REAP, 260, 5, A_None, S_REAP_DIEA2_10, 4 },
    { SPR_REAP, 261, 75, A_None, S_REAP_DIEA2_11, 4 },
    { SPR_REAP, 262, 76, A_None, S_REAP_DIEA2_12, 4 },
    { SPR_REAP, 263, 76, A_None, S_REAP_DIEA2_13, 4 },
    { SPR_REAP, 264, 43, A_None, S_REAP_DIEA2_14, 4 },
    { SPR_REAP, 265, 42, A_None, S_REAP_DIEA2_15, 4 },
    { SPR_REAP, 266, 43, A_None, S_REAP_DIEA2_CORPSE, 4 },
    { SPR_REAP, 266, -1, A_None, S_NULL, 4 },
    { SPR_BARR, 106, -1, A_None, S_BARR_STND, 1 },
    { SPR_BARR, 122, 3, A_Chase, S_BARR_RUN2, 2 },
    { SPR_BARR, 123, 3, A_Chase, S_BARR_RUN3, 2 },
    { SPR_BARR, 124, 3, A_Chase, S_BARR_RUN4, 2 },
    { SPR_BARR, 125, 3, A_Chase, S_BARR_RUN5, 2 },
    { SPR_BARR, 126, 3, A_Chase, S_BARR_RUN6, 2 },
    { SPR_BARR, 127, 3, A_Chase, S_BARR_RUN7, 2 },
    { SPR_BARR, 128, 3, A_Chase, S_BARR_RUN8, 2 },
    { SPR_BARR, 129, 3, A_Chase, S_BARR_RUN9, 2 },
    { SPR_BARR, 130, 3, A_Chase, S_BARR_RUN10, 2 },
    { SPR_BARR, 131, 3, A_Chase, S_BARR_RUN11, 2 },
    { SPR_BARR, 132, 3, A_Chase, S_BARR_RUN12, 2 },
    { SPR_BARR, 133, 3, A_Chase, S_BARR_RUN13, 2 },
    { SPR_BARR, 134, 3, A_Chase, S_BARR_RUN1, 2 },
    { SPR_BARR, 195, 2, A_None, S_BARR_ATK2, 3 },
    { SPR_BARR, 196, 2, A_None, S_BARR_ATK3, 3 },
    { SPR_BARR, 197, 2, A_None, S_BARR_ATK4, 3 },
    { SPR_BARR, 198, 2, A_None, S_BARR_ATK5, 3 },
    { SPR_BARR, 199, 2, A_None, S_BARR_ATK6, 3 },
    { SPR_BARR, 200, 2, A_None, S_BARR_ATK7, 3 },
    { SPR_BARR, 201, 2, A_None, S_BARR_ATK8, 3 },
    { SPR_BARR, 202, 2, A_None, S_BARR_STND, 3 },
    /* BARRDIE14: complete native FIN sequence. */
    { SPR_BARR, 246, 5, A_None, S_BARR_DIE2, 4 },
    { SPR_BARR, 247, 4, A_None, S_BARR_DIE3, 4 },
    { SPR_BARR, 248, 5, A_None, S_BARR_DIE4, 4 },
    { SPR_BARR, 249, 5, A_None, S_BARR_DIE5, 4 },
    { SPR_BARR, 250, 5, A_None, S_BARR_DIE6, 4 },
    { SPR_BARR, 251, 4, A_None, S_BARR_DIE7, 4 },
    { SPR_BARR, 252, 5, A_None, S_BARR_DIE8, 4 },
    { SPR_BARR, 253, 5, A_None, S_BARR_DIE9, 4 },
    { SPR_BARR, 254, 5, A_None, S_BARR_DIE10, 4 },
    { SPR_BARR, 255, 75, A_None, S_BARR_DIE11, 4 },
    { SPR_BARR, 256, 76, A_None, S_BARR_DIE12, 4 },
    { SPR_BARR, 257, 76, A_None, S_BARR_DIE13, 4 },
    { SPR_BARR, 258, 43, A_None, S_BARR_DIE14, 4 },
    { SPR_BARR, 259, 42, A_None, S_BARR_DIE15, 4 },
    { SPR_BARR, 260, 43, A_None, S_BARR_CORPSE, 4 },
    { SPR_BARR, 260, -1, A_None, S_NULL, 4 },
    { SPR_SARG, 663, 1, A_Look, S_SARG_STND, 1 },
    { SPR_SARG, 198, 3, A_Chase, S_SARG_RUN2, 2 },
    { SPR_SARG, 199, 3, A_Chase, S_SARG_RUN3, 2 },
    { SPR_SARG, 200, 3, A_Chase, S_SARG_RUN4, 2 },
    { SPR_SARG, 201, 3, A_Chase, S_SARG_RUN5, 2 },
    { SPR_SARG, 202, 3, A_Chase, S_SARG_RUN6, 2 },
    { SPR_SARG, 203, 3, A_Chase, S_SARG_RUN7, 2 },
    { SPR_SARG, 204, 3, A_Chase, S_SARG_RUN8, 2 },
    { SPR_SARG, 205, 3, A_Chase, S_SARG_RUN1, 2 },
    { SPR_SARG, 270, 2, A_None, S_SARG_ATK2, 3 },
    { SPR_SARG, 271, 2, A_None, S_SARG_ATK3, 3 },
    { SPR_SARG, 272, 2, A_None, S_SARG_STND, 3 },
    /* SARGDIE14: complete native FIN sequence. */
    { SPR_SARG, 390, 9, A_None, S_SARG_DIE2, 4 },
    { SPR_SARG, 391, 8, A_None, S_SARG_DIE3, 4 },
    { SPR_SARG, 392, 8, A_None, S_SARG_DIE4, 4 },
    { SPR_SARG, 393, 10, A_None, S_SARG_DIE5, 4 },
    { SPR_SARG, 394, 9, A_None, S_SARG_DIE6, 4 },
    { SPR_SARG, 395, 10, A_None, S_SARG_DIE7, 4 },
    { SPR_SARG, 396, 9, A_None, S_SARG_DIE8, 4 },
    { SPR_SARG, 397, 10, A_None, S_SARG_DIE9, 4 },
    { SPR_SARG, 398, 9, A_None, S_SARG_DIE10, 4 },
    { SPR_SARG, 399, 10, A_None, S_SARG_DIE11, 4 },
    { SPR_SARG, 400, 9, A_None, S_SARG_DIE12, 4 },
    { SPR_SARG, 401, 10, A_None, S_SARG_DIE13, 4 },
    { SPR_SARG, 402, 9, A_None, S_SARG_DIE14, 4 },
    { SPR_SARG, 403, 9, A_None, S_SARG_DIE15, 4 },
    { SPR_SARG, 404, 10, A_None, S_SARG_DIE16, 4 },
    { SPR_SARG, 405, 5, A_None, S_SARG_DIE17, 4 },
    { SPR_SARG, 406, 4, A_None, S_SARG_DIE18, 4 },
    { SPR_SARG, 407, 5, A_None, S_SARG_DIE19, 4 },
    { SPR_SARG, 408, 5, A_None, S_SARG_DIE20, 4 },
    { SPR_SARG, 409, 5, A_None, S_SARG_DIE21, 4 },
    { SPR_SARG, 410, 4, A_None, S_SARG_DIE22, 4 },
    { SPR_SARG, 411, 5, A_None, S_SARG_DIE23, 4 },
    { SPR_SARG, 412, 5, A_None, S_SARG_DIE24, 4 },
    { SPR_SARG, 413, 5, A_None, S_SARG_DIE25, 4 },
    { SPR_SARG, 414, 4, A_None, S_SARG_DIE26, 4 },
    { SPR_SARG, 415, 5, A_None, S_SARG_DIE27, 4 },
    { SPR_SARG, 416, 5, A_None, S_SARG_DIE28, 4 },
    { SPR_SARG, 417, 5, A_None, S_SARG_DIE29, 4 },
    { SPR_SARG, 418, 4, A_None, S_SARG_DIE30, 4 },
    { SPR_SARG, 419, 5, A_None, S_SARG_DIE31, 4 },
    { SPR_SARG, 420, 5, A_None, S_SARG_DIE32, 4 },
    { SPR_SARG, 421, 4, A_None, S_SARG_DIE33, 4 },
    { SPR_SARG, 422, 5, A_None, S_SARG_DIE34, 4 },
    { SPR_SARG, 423, 5, A_None, S_SARG_DIE35, 4 },
    { SPR_SARG, 424, 5, A_None, S_SARG_DIE36, 4 },
    { SPR_SARG, 425, 75, A_None, S_SARG_DIE37, 4 },
    { SPR_SARG, 426, 76, A_None, S_SARG_CORPSE, 4 },
    { SPR_SARG, 426, -1, A_None, S_NULL, 4 },
    { SPR_SCGM, 62, 1, A_Look, S_SCGM_STND, 1 },
    { SPR_SCGM, 30, 3, A_Chase, S_SCGM_RUN2, 2 },
    { SPR_SCGM, 31, 3, A_Chase, S_SCGM_RUN3, 2 },
    { SPR_SCGM, 32, 3, A_Chase, S_SCGM_RUN4, 2 },
    { SPR_SCGM, 33, 3, A_Chase, S_SCGM_RUN1, 2 },
    /* SCGMDIE0: complete native FIN sequence. */
    { SPR_SCGM, 102, 2, A_None, S_SCGM_DIE2, 4 },
    { SPR_SCGM, 103, 1, A_None, S_SCGM_DIE3, 4 },
    { SPR_SCGM, 104, 2, A_None, S_SCGM_DIE4, 4 },
    { SPR_SCGM, 105, 1, A_None, S_SCGM_DIE5, 4 },
    { SPR_SCGM, 106, 2, A_None, S_SCGM_DIE6, 4 },
    { SPR_SCGM, 107, 1, A_None, S_SCGM_DIE7, 4 },
    { SPR_SCGM, 108, 2, A_None, S_SCGM_DIE8, 4 },
    { SPR_SCGM, 109, 2, A_None, S_SCGM_DIE9, 4 },
    { SPR_SCGM, 110, 1, A_None, S_SCGM_DIE10, 4 },
    { SPR_SCGM, 111, 2, A_None, S_SCGM_DIE11, 4 },
    { SPR_SCGM, 112, 1, A_None, S_SCGM_DIE12, 4 },
    { SPR_SCGM, 113, 2, A_None, S_SCGM_DIE13, 4 },
    { SPR_SCGM, 114, 2, A_None, S_SCGM_DIE14, 4 },
    { SPR_SCGM, 115, 1, A_None, S_SCGM_DIE15, 4 },
    { SPR_SCGM, 116, 2, A_None, S_SCGM_DIE16, 4 },
    { SPR_SCGM, 117, 1, A_None, S_SCGM_DIE17, 4 },
    { SPR_SCGM, 118, 2, A_None, S_SCGM_DIE18, 4 },
    { SPR_SCGM, 119, 1, A_None, S_SCGM_DIE19, 4 },
    { SPR_SCGM, 120, 2, A_None, S_SCGM_DIE20, 4 },
    { SPR_SCGM, 121, 2, A_None, S_SCGM_DIE21, 4 },
    { SPR_SCGM, 122, 1, A_None, S_SCGM_DIE22, 4 },
    { SPR_SCGM, 123, 2, A_None, S_SCGM_DIE23, 4 },
    { SPR_SCGM, 124, 1, A_None, S_SCGM_DIE24, 4 },
    { SPR_SCGM, 125, 2, A_None, S_SCGM_DIE25, 4 },
    { SPR_SCGM, 126, 1, A_None, S_SCGM_DIE26, 4 },
    { SPR_SCGM, 127, 2, A_None, S_SCGM_DIE27, 4 },
    { SPR_SCGM, 128, 2, A_None, S_SCGM_DIE28, 4 },
    { SPR_SCGM, 129, 1, A_None, S_SCGM_DIE29, 4 },
    { SPR_SCGM, 130, 2, A_None, S_SCGM_DIE30, 4 },
    { SPR_SCGM, 131, 1, A_None, S_SCGM_CORPSE, 4 },
    { SPR_SCGM, 131, -1, A_None, S_NULL, 4 },
    { SPR_EXPL, 50, -1, A_None, S_EXPL_STND, 1 },
    { SPR_EXPL, 66, 3, A_Chase, S_EXPL_RUN2, 2 },
    { SPR_EXPL, 67, 3, A_Chase, S_EXPL_RUN1, 2 },
    /* EXPLDEPLOY14: complete native FIN sequence. */
    { SPR_EXPL, 82, 5, A_None, S_EXPL_DEPLOY2, 5 },
    { SPR_EXPL, 83, 4, A_None, S_EXPL_DEPLOY3, 5 },
    { SPR_EXPL, 84, 5, A_None, S_EXPL_DEPLOY4, 5 },
    { SPR_EXPL, 85, 5, A_None, S_EXPL_DEPLOY5, 5 },
    { SPR_EXPL, 86, 5, A_None, S_EXPL_DEPLOY6, 5 },
    { SPR_EXPL, 87, 4, A_None, S_EXPL_DEPLOY7, 5 },
    { SPR_EXPL, 88, 5, A_None, S_EXPL_DEPLOY8, 5 },
    { SPR_EXPL, 89, 5, A_None, S_EXPL_DEPLOY9, 5 },
    { SPR_EXPL, 90, 5, A_None, S_EXPL_DEPLOY10, 5 },
    { SPR_EXPL, 91, 4, A_None, S_EXPL_DEPLOY11, 5 },
    { SPR_EXPL, 92, 5, A_None, S_EXPL_DEPLOY12, 5 },
    { SPR_EXPL, 93, 5, A_None, S_EXPL_DEPLOY13, 5 },
    { SPR_EXPL, 94, 5, A_None, S_EXPL_DEPLOY14, 5 },
    { SPR_EXPL, 95, 4, A_None, S_EXPL_DEPLOY15, 5 },
    { SPR_EXPL, 96, 5, A_None, S_EXPL_DEPLOY16, 5 },
    { SPR_EXPL, 97, 5, A_None, S_EXPL_DEPLOY17, 5 },
    { SPR_EXPL, 98, 5, A_None, S_EXPL_DEPLOY18, 5 },
    { SPR_EXPL, 99, 4, A_None, S_EXPL_DEPLOY19, 5 },
    { SPR_EXPL, 100, 5, A_None, S_EXPL_DEPLOY20, 5 },
    { SPR_EXPL, 101, 5, A_None, S_EXPL_WORK1, 5 },
    /* EDPLYSTAND14 final FIN frame: static body; work light remains unverified. */
    { SPR_EXPL, 103, 2, A_None, S_EXPL_WORK2, 5 },
    { SPR_EXPL, 103, 4, A_None, S_EXPL_WORK1, 5 },
    /* EXPLDIE0: complete native FIN sequence. */
    { SPR_EXPL, 104, 5, A_None, S_EXPL_DIE2, 4 },
    { SPR_EXPL, 105, 4, A_None, S_EXPL_DIE3, 4 },
    { SPR_EXPL, 106, 5, A_None, S_EXPL_DIE4, 4 },
    { SPR_EXPL, 107, 5, A_None, S_EXPL_DIE5, 4 },
    { SPR_EXPL, 108, 5, A_None, S_EXPL_DIE6, 4 },
    { SPR_EXPL, 109, 4, A_None, S_EXPL_DIE7, 4 },
    { SPR_EXPL, 110, 5, A_None, S_EXPL_DIE8, 4 },
    { SPR_EXPL, 111, 5, A_None, S_EXPL_DIE9, 4 },
    { SPR_EXPL, 112, 5, A_None, S_EXPL_DIE10, 4 },
    { SPR_EXPL, 113, 4, A_None, S_EXPL_DIE11, 4 },
    { SPR_EXPL, 114, 5, A_None, S_EXPL_DIE12, 4 },
    { SPR_EXPL, 115, 5, A_None, S_EXPL_CORPSE, 4 },
    { SPR_EXPL, 115, -1, A_None, S_NULL, 4 },
    { SPR_ORTU, 240, -1, A_None, S_ORTU_STND, 1 },
    { SPR_ORTU, 86, 3, A_Chase, S_ORTU_RUN2, 2 },
    { SPR_ORTU, 87, 3, A_Chase, S_ORTU_RUN3, 2 },
    { SPR_ORTU, 88, 3, A_Chase, S_ORTU_RUN4, 2 },
    { SPR_ORTU, 89, 3, A_Chase, S_ORTU_RUN5, 2 },
    { SPR_ORTU, 90, 3, A_Chase, S_ORTU_RUN6, 2 },
    { SPR_ORTU, 91, 3, A_Chase, S_ORTU_RUN7, 2 },
    { SPR_ORTU, 92, 3, A_Chase, S_ORTU_RUN1, 2 },
    /* ORTUDIE14: complete native FIN sequence. */
    { SPR_ORTU, 212, 6, A_None, S_ORTU_DIE2, 4 },
    { SPR_ORTU, 213, 7, A_None, S_ORTU_DIE3, 4 },
    { SPR_ORTU, 214, 6, A_None, S_ORTU_DIE4, 4 },
    { SPR_ORTU, 215, 6, A_None, S_ORTU_DIE5, 4 },
    { SPR_ORTU, 216, 7, A_None, S_ORTU_DIE6, 4 },
    { SPR_ORTU, 217, 6, A_None, S_ORTU_DIE7, 4 },
    { SPR_ORTU, 218, 6, A_None, S_ORTU_CORPSE, 4 },
    { SPR_ORTU, 218, -1, A_None, S_NULL, 4 },
    { SPR_SLUG, 90, -1, A_None, S_SLUG_STND, 1 },
    { SPR_SLUG, 106, 3, A_Chase, S_SLUG_RUN2, 2 },
    { SPR_SLUG, 107, 3, A_Chase, S_SLUG_RUN3, 2 },
    { SPR_SLUG, 108, 3, A_Chase, S_SLUG_RUN4, 2 },
    { SPR_SLUG, 109, 3, A_Chase, S_SLUG_RUN5, 2 },
    { SPR_SLUG, 110, 3, A_Chase, S_SLUG_RUN6, 2 },
    { SPR_SLUG, 111, 3, A_Chase, S_SLUG_RUN7, 2 },
    { SPR_SLUG, 112, 3, A_Chase, S_SLUG_RUN1, 2 },
    /* SLUGDIE14: complete native FIN sequence. */
    { SPR_SLUG, 161, 5, A_None, S_SLUG_DIE2, 4 },
    { SPR_SLUG, 162, 4, A_None, S_SLUG_DIE3, 4 },
    { SPR_SLUG, 163, 5, A_None, S_SLUG_DIE4, 4 },
    { SPR_SLUG, 164, 5, A_None, S_SLUG_DIE5, 4 },
    { SPR_SLUG, 165, 5, A_None, S_SLUG_DIE6, 4 },
    { SPR_SLUG, 166, 12, A_None, S_SLUG_DIE7, 4 },
    { SPR_SLUG, 167, 43, A_None, S_SLUG_DIE8, 4 },
    { SPR_SLUG, 168, 43, A_None, S_SLUG_DIE9, 4 },
    { SPR_SLUG, 169, 42, A_None, S_SLUG_CORPSE, 4 },
    { SPR_SLUG, 169, -1, A_None, S_NULL, 4 },
    /* SLUGDEPLOY14: complete native FIN sequence. */
    { SPR_SLUG, 237, 5, A_None, S_SLUG_DEPLOY2, 5 },
    { SPR_SLUG, 238, 4, A_None, S_SLUG_DEPLOY3, 5 },
    { SPR_SLUG, 239, 5, A_None, S_SLUG_DEPLOY4, 5 },
    { SPR_SLUG, 240, 5, A_None, S_SLUG_DEPLOY5, 5 },
    { SPR_SLUG, 241, 5, A_None, S_SLUG_DEPLOY6, 5 },
    { SPR_SLUG, 242, 4, A_None, S_SLUG_DEPLOY7, 5 },
    { SPR_SLUG, 243, 5, A_None, S_SLUG_DEPLOY8, 5 },
    { SPR_SLUG, 244, 5, A_None, S_SLUG_DEPLOY9, 5 },
    { SPR_SLUG, 245, 5, A_None, S_SLUG_DEPLOY10, 5 },
    { SPR_SLUG, 246, 4, A_None, S_SLUG_DEPLOY11, 5 },
    { SPR_SLUG, 247, 5, A_None, S_SLUG_DEPLOY12, 5 },
    { SPR_SLUG, 248, 5, A_None, S_SLUG_DEPLOY13, 5 },
    { SPR_SLUG, 249, 5, A_None, S_SLUG_DEPLOY14, 5 },
    { SPR_SLUG, 250, 4, A_None, S_SLUG_DEPLOY1, 5 },
    /* SLUGRETRACT14: complete native FIN sequence. */
    { SPR_SLUG, 251, 5, A_None, S_SLUG_RETRACT2, 5 },
    { SPR_SLUG, 252, 4, A_None, S_SLUG_RETRACT3, 5 },
    { SPR_SLUG, 253, 5, A_None, S_SLUG_RETRACT4, 5 },
    { SPR_SLUG, 254, 5, A_None, S_SLUG_RETRACT5, 5 },
    { SPR_SLUG, 255, 5, A_None, S_SLUG_RETRACT6, 5 },
    { SPR_SLUG, 256, 4, A_None, S_SLUG_RETRACT7, 5 },
    { SPR_SLUG, 257, 5, A_None, S_SLUG_RETRACT8, 5 },
    { SPR_SLUG, 258, 5, A_None, S_SLUG_RETRACT9, 5 },
    { SPR_SLUG, 259, 5, A_None, S_SLUG_RETRACT10, 5 },
    { SPR_SLUG, 260, 4, A_None, S_SLUG_RETRACT11, 5 },
    { SPR_SLUG, 261, 5, A_None, S_SLUG_RETRACT12, 5 },
    { SPR_SLUG, 262, 5, A_None, S_SLUG_RETRACT13, 5 },
    { SPR_SLUG, 263, 5, A_None, S_SLUG_RETRACT14, 5 },
    { SPR_SLUG, 264, 4, A_None, S_NULL, 5 },
    { SPR_TURR, 60, -1, A_None, S_TURR_STND, 1 },
    { SPR_TURR, 111, 2, A_Attack, S_TURR_STND, 3 },
    /* TURRDIE0: complete native FIN sequence. */
    { SPR_TURR, 125, 5, A_None, S_TURR_DIE2, 4 },
    { SPR_TURR, 126, 4, A_None, S_TURR_DIE3, 4 },
    { SPR_TURR, 127, 5, A_None, S_TURR_DIE4, 4 },
    { SPR_TURR, 128, 5, A_None, S_TURR_DIE5, 4 },
    { SPR_TURR, 129, 5, A_None, S_TURR_DIE6, 4 },
    { SPR_TURR, 130, 4, A_None, S_TURR_DIE7, 4 },
    { SPR_TURR, 131, 5, A_None, S_TURR_DIE8, 4 },
    { SPR_TURR, 132, 5, A_None, S_TURR_DIE9, 4 },
    { SPR_TURR, 133, 5, A_None, S_TURR_DIE10, 4 },
    { SPR_TURR, 134, 4, A_None, S_TURR_DIE11, 4 },
    { SPR_TURR, 135, 5, A_None, S_TURR_DIE12, 4 },
    { SPR_TURR, 136, 5, A_None, S_TURR_DIE13, 4 },
    { SPR_TURR, 137, 5, A_None, S_TURR_DIE14, 4 },
    { SPR_TURR, 138, 4, A_None, S_TURR_DIE15, 4 },
    { SPR_TURR, 139, 5, A_None, S_TURR_DIE16, 4 },
    { SPR_TURR, 140, 5, A_None, S_NULL, 4 },
    /* TONGSTAND0: complete native FIN sequence. */
    { SPR_TONG, 10, 16, A_None, S_TONG_STND2, 1 },
    { SPR_TONG, 11, 14, A_None, S_TONG_STND3, 1 },
    { SPR_TONG, 12, 13, A_None, S_TONG_STND4, 1 },
    { SPR_TONG, 13, 9, A_None, S_TONG_STND5, 1 },
    { SPR_TONG, 14, 8, A_None, S_TONG_STND6, 1 },
    { SPR_TONG, 15, 6, A_None, S_TONG_STND7, 1 },
    { SPR_TONG, 16, 5, A_None, S_TONG_STND8, 1 },
    { SPR_TONG, 17, 2, A_None, S_TONG_STND9, 1 },
    { SPR_TONG, 18, 1, A_None, S_TONG_STND10, 1 },
    { SPR_TONG, 19, 2, A_None, S_TONG_STND11, 1 },
    { SPR_TONG, 20, 1, A_None, S_TONG_STND12, 1 },
    { SPR_TONG, 21, 2, A_None, S_TONG_STND13, 1 },
    { SPR_TONG, 22, 2, A_None, S_TONG_STND14, 1 },
    { SPR_TONG, 23, 1, A_None, S_TONG_STND15, 1 },
    { SPR_TONG, 24, 2, A_None, S_TONG_STND16, 1 },
    { SPR_TONG, 25, 1, A_None, S_TONG_STND17, 1 },
    { SPR_TONG, 26, 2, A_None, S_TONG_STND18, 1 },
    { SPR_TONG, 27, 1, A_None, S_TONG_STND1, 1 },
    /* TONGDIE0: complete native FIN sequence. */
    { SPR_TONG, 29, 5, A_None, S_TONG_DIE2, 4 },
    { SPR_TONG, 30, 4, A_None, S_TONG_DIE3, 4 },
    { SPR_TONG, 31, 5, A_None, S_TONG_DIE4, 4 },
    { SPR_TONG, 32, 5, A_None, S_TONG_DIE5, 4 },
    { SPR_TONG, 33, 5, A_None, S_TONG_DIE6, 4 },
    { SPR_TONG, 34, 4, A_None, S_TONG_DIE7, 4 },
    { SPR_TONG, 35, 5, A_None, S_TONG_DIE8, 4 },
    { SPR_TONG, 36, 5, A_None, S_TONG_DIE9, 4 },
    { SPR_TONG, 37, 5, A_None, S_TONG_DIE10, 4 },
    { SPR_TONG, 38, 4, A_None, S_TONG_DIE11, 4 },
    { SPR_TONG, 39, 5, A_None, S_TONG_DIE12, 4 },
    { SPR_TONG, 40, 5, A_None, S_TONG_DIE13, 4 },
    { SPR_TONG, 41, 5, A_None, S_TONG_DIE14, 4 },
    { SPR_TONG, 42, 4, A_None, S_TONG_DIE15, 4 },
    { SPR_TONG, 43, 5, A_None, S_TONG_DIE16, 4 },
    { SPR_TONG, 44, 5, A_None, S_TONG_DIE17, 4 },
    { SPR_TONG, 45, 5, A_None, S_TONG_DIE18, 4 },
    { SPR_TONG, 46, 4, A_None, S_TONG_DIE19, 4 },
    { SPR_TONG, 47, 5, A_None, S_TONG_DIE20, 4 },
    { SPR_TONG, 48, 5, A_None, S_NULL, 4 },
    /* CENTSTAND0: complete native FIN sequence. */
    { SPR_CENT, 65, 5, A_None, S_CENT_STND2, 1 },
    { SPR_CENT, 66, 4, A_None, S_CENT_STND3, 1 },
    { SPR_CENT, 67, 5, A_None, S_CENT_STND4, 1 },
    { SPR_CENT, 68, 5, A_None, S_CENT_STND5, 1 },
    { SPR_CENT, 69, 5, A_None, S_CENT_STND6, 1 },
    { SPR_CENT, 70, 4, A_None, S_CENT_STND7, 1 },
    { SPR_CENT, 71, 5, A_None, S_CENT_STND8, 1 },
    { SPR_CENT, 72, 5, A_None, S_CENT_STND9, 1 },
    { SPR_CENT, 73, 5, A_None, S_CENT_STND10, 1 },
    { SPR_CENT, 74, 4, A_None, S_CENT_STND11, 1 },
    { SPR_CENT, 75, 5, A_None, S_CENT_STND12, 1 },
    { SPR_CENT, 76, 5, A_None, S_CENT_STND13, 1 },
    { SPR_CENT, 77, 5, A_None, S_CENT_STND14, 1 },
    { SPR_CENT, 78, 4, A_None, S_CENT_STND15, 1 },
    { SPR_CENT, 79, 5, A_None, S_CENT_STND16, 1 },
    { SPR_CENT, 80, 5, A_None, S_CENT_STND17, 1 },
    { SPR_CENT, 81, 5, A_None, S_CENT_STND18, 1 },
    { SPR_CENT, 82, 4, A_None, S_CENT_STND19, 1 },
    { SPR_CENT, 83, 5, A_None, S_CENT_STND20, 1 },
    { SPR_CENT, 84, 5, A_None, S_CENT_STND21, 1 },
    { SPR_CENT, 85, 4, A_None, S_CENT_STND22, 1 },
    { SPR_CENT, 86, 5, A_None, S_CENT_STND23, 1 },
    { SPR_CENT, 87, 5, A_None, S_CENT_STND24, 1 },
    { SPR_CENT, 88, 5, A_None, S_CENT_STND1, 1 },
    /* CENTDIE0: complete native FIN sequence. */
    { SPR_CENT, 24, 5, A_None, S_CENT_DIE2, 4 },
    { SPR_CENT, 25, 4, A_None, S_CENT_DIE3, 4 },
    { SPR_CENT, 26, 5, A_None, S_CENT_DIE4, 4 },
    { SPR_CENT, 27, 5, A_None, S_CENT_DIE5, 4 },
    { SPR_CENT, 28, 5, A_None, S_CENT_DIE6, 4 },
    { SPR_CENT, 29, 4, A_None, S_CENT_DIE7, 4 },
    { SPR_CENT, 30, 5, A_None, S_CENT_DIE8, 4 },
    { SPR_CENT, 31, 5, A_None, S_CENT_DIE9, 4 },
    { SPR_CENT, 32, 5, A_None, S_CENT_DIE10, 4 },
    { SPR_CENT, 33, 4, A_None, S_CENT_DIE11, 4 },
    { SPR_CENT, 34, 5, A_None, S_CENT_DIE12, 4 },
    { SPR_CENT, 35, 5, A_None, S_CENT_DIE13, 4 },
    { SPR_CENT, 36, 5, A_None, S_CENT_DIE14, 4 },
    { SPR_CENT, 37, 4, A_None, S_CENT_DIE15, 4 },
    { SPR_CENT, 38, 5, A_None, S_CENT_DIE16, 4 },
    { SPR_CENT, 39, 5, A_None, S_CENT_DIE17, 4 },
    { SPR_CENT, 40, 5, A_None, S_CENT_DIE18, 4 },
    { SPR_CENT, 41, 4, A_None, S_CENT_DIE19, 4 },
    { SPR_CENT, 42, 5, A_None, S_CENT_DIE20, 4 },
    { SPR_CENT, 43, 5, A_None, S_CENT_DIE21, 4 },
    { SPR_CENT, 44, 4, A_None, S_CENT_DIE22, 4 },
    { SPR_CENT, 45, 5, A_None, S_CENT_DIE23, 4 },
    { SPR_CENT, 46, 5, A_None, S_CENT_DIE24, 4 },
    { SPR_CENT, 47, 5, A_None, S_CENT_DIE25, 4 },
    { SPR_CENT, 48, 4, A_None, S_CENT_DIE26, 4 },
    { SPR_CENT, 49, 5, A_None, S_CENT_DIE27, 4 },
    { SPR_CENT, 50, 5, A_None, S_CENT_DIE28, 4 },
    { SPR_CENT, 51, 5, A_None, S_CENT_DIE29, 4 },
    { SPR_CENT, 52, 4, A_None, S_CENT_DIE30, 4 },
    { SPR_CENT, 53, 5, A_None, S_CENT_DIE31, 4 },
    { SPR_CENT, 54, 5, A_None, S_CENT_DIE32, 4 },
    { SPR_CENT, 55, 5, A_None, S_CENT_DIE33, 4 },
    { SPR_CENT, 56, 4, A_None, S_CENT_DIE34, 4 },
    { SPR_CENT, 57, 5, A_None, S_CENT_DIE35, 4 },
    { SPR_CENT, 58, 5, A_None, S_CENT_DIE36, 4 },
    { SPR_CENT, 59, 5, A_None, S_CENT_DIE37, 4 },
    { SPR_CENT, 60, 4, A_None, S_CENT_DIE38, 4 },
    { SPR_CENT, 61, 5, A_None, S_CENT_DIE39, 4 },
    { SPR_CENT, 62, 5, A_None, S_CENT_DIE40, 4 },
    { SPR_CENT, 63, 4, A_None, S_CENT_DIE41, 4 },
    { SPR_CENT, 64, 5, A_None, S_NULL, 4 },
    /* DOTTSTAND0: complete native FIN frame. */
    { SPR_DOTT, 1, -1, A_None, S_DOTT_STND, 1 },
    /* MINDHIVSTAND0: complete native FIN sequence. */
    { SPR_ALBU, 33, 8, A_None, S_ALIEN_MINDHIVE_STND_2, 1 },
    { SPR_ALBU, 34, 8, A_None, S_ALIEN_MINDHIVE_STND, 1 },
    /* WARHIVESTAND0: complete native FIN sequence. */
    { SPR_ALBU, 43, 5, A_None, S_ALIEN_WARHIVE_STND_2, 1 },
    { SPR_ALBU, 44, 4, A_None, S_ALIEN_WARHIVE_STND_3, 1 },
    { SPR_ALBU, 45, 5, A_None, S_ALIEN_WARHIVE_STND_4, 1 },
    { SPR_ALBU, 46, 5, A_None, S_ALIEN_WARHIVE_STND, 1 },
    /* BRDRHIVSTAND0: complete native FIN sequence. */
    { SPR_ALBU, 41, 8, A_None, S_ALIEN_BRDRHIVE_STND_2, 1 },
    { SPR_ALBU, 42, 8, A_None, S_ALIEN_BRDRHIVE_STND, 1 },
    /* BRDRHIV2STAND0: complete native FIN sequence. */
    { SPR_ALBU, 47, 8, A_None, S_ALIEN_BRDRHIVE2_STND_2, 1 },
    { SPR_ALBU, 48, 5, A_None, S_ALIEN_BRDRHIVE2_STND_3, 1 },
    { SPR_ALBU, 49, 6, A_None, S_ALIEN_BRDRHIVE2_STND_4, 1 },
    { SPR_ALBU, 50, 9, A_None, S_ALIEN_BRDRHIVE2_STND, 1 },
    /* MNDHIV2STAND0: complete native FIN sequence. */
    { SPR_ALBU, 35, 8, A_None, S_ALIEN_MINDHIVE2_STND_2, 1 },
    { SPR_ALBU, 36, 8, A_None, S_ALIEN_MINDHIVE2_STND, 1 },
    /* MINDHIVSTAND0: complete native FIN sequence. */
    { SPR_ALBU, 33, 8, A_None, S_ALIEN_MINDHIVE3_STND_2, 1 },
    { SPR_ALBU, 34, 8, A_None, S_ALIEN_MINDHIVE3_STND, 1 },
    /* Preserve the existing research-hive corpse placeholder with its FIN offset.
     * Retail standing-label selection remains unverified. */
    { SPR_ALBU, 40, -1, A_None, S_ALIEN_RSCHIVE_STND, 1 },
    { SPR_DROP, 86, 5, A_DC_Fly, S_DROP_MOVE2, 2 },
    { SPR_DROP, 87, 4, A_DC_Fly, S_DROP_MOVE3, 2 },
    { SPR_DROP, 88, 5, A_DC_Fly, S_DROP_MOVE4, 2 },
    { SPR_DROP, 89, 5, A_DC_Fly, S_DROP_MOVE5, 2 },
    { SPR_DROP, 90, 5, A_DC_Fly, S_DROP_MOVE6, 2 },
    { SPR_DROP, 91, 4, A_DC_Fly, S_DROP_MOVE7, 2 },
    { SPR_DROP, 92, 5, A_DC_Fly, S_DROP_MOVE8, 2 },
    { SPR_DROP, 93, 5, A_DC_Fly, S_DROP_MOVE9, 2 },
    { SPR_DROP, 94, 5, A_DC_Fly, S_DROP_MOVE10, 2 },
    { SPR_DROP, 95, 4, A_DC_Fly, S_DROP_MOVE1, 2 },
    { SPR_DROP, 2, 5, A_None, S_DROP_UNLOAD2, 6 },
    { SPR_DROP, 3, 4, A_None, S_DROP_UNLOAD3, 6 },
    { SPR_DROP, 4, 5, A_None, S_DROP_UNLOAD4, 6 },
    { SPR_DROP, 5, 5, A_None, S_DROP_UNLOAD5, 6 },
    { SPR_DROP, 6, 5, A_None, S_DROP_UNLOAD6, 6 },
    { SPR_DROP, 7, 4, A_None, S_DROP_UNLOAD7, 6 },
    { SPR_DROP, 8, 5, A_None, S_DROP_UNLOAD8, 6 },
    { SPR_DROP, 9, 5, A_None, S_DROP_UNLOAD9, 6 },
    { SPR_DROP, 10, 5, A_None, S_DROP_UNLOAD10, 6 },
    { SPR_DROP, 11, 4, A_None, S_DROP_RELEASE, 6 },
    { SPR_DROP, 96, 5, A_None, S_SCNCPOD_BUILD2, 6 },
    { SPR_DROP, 97, 4, A_None, S_SCNCPOD_BUILD3, 6 },
    { SPR_DROP, 98, 5, A_None, S_SCNCPOD_BUILD4, 6 },
    { SPR_DROP, 99, 5, A_None, S_SCNCPOD_BUILD5, 6 },
    { SPR_DROP, 100, 5, A_None, S_SCNCPOD_BUILD6, 6 },
    { SPR_DROP, 101, 4, A_None, S_SCNCPOD_BUILD7, 6 },
    { SPR_DROP, 102, 5, A_None, S_SCNCPOD_BUILD8, 6 },
    { SPR_DROP, 103, 5, A_None, S_SCNCPOD_BUILD9, 6 },
    { SPR_DROP, 104, 5, A_None, S_SCNCPOD_BUILD10, 6 },
    { SPR_DROP, 105, 4, A_None, S_SCNCPOD_BUILD11, 6 },
    { SPR_DROP, 106, 5, A_None, S_SCNCPOD_BUILD12, 6 },
    { SPR_DROP, 107, 5, A_None, S_SCNCPOD_BUILD13, 6 },
    { SPR_DROP, 108, 5, A_None, S_SCNCPOD_BUILD14, 6 },
    { SPR_DROP, 109, 4, A_None, S_SCNCPOD_BUILD15, 6 },
    { SPR_DROP, 110, 5, A_None, S_SCNCPOD_BUILD16, 6 },
    { SPR_DROP, 111, 5, A_None, S_SCNCPOD_BUILD17, 6 },
    { SPR_DROP, 112, 5, A_None, S_SCNCPOD_BUILD18, 6 },
    { SPR_DROP, 113, 4, A_None, S_SCNCPOD_BUILD19, 6 },
    { SPR_DROP, 114, 5, A_None, S_SCNCPOD_BUILD20, 6 },
    { SPR_DROP, 115, 5, A_None, S_SCNCPOD_BUILD21, 6 },
    { SPR_DROP, 116, 4, A_None, S_SCNCPOD_BUILD22, 6 },
    { SPR_DROP, 117, 5, A_None, S_SCNCPOD_BUILD23, 6 },
    { SPR_DROP, 118, 5, A_None, S_SCNCPOD_BUILD24, 6 },
    { SPR_DROP, 119, 5, A_None, S_SCNCPOD_BUILD25, 6 },
    { SPR_DROP, 120, 4, A_None, S_SCNCPOD_BUILD26, 6 },
    { SPR_DROP, 121, 5, A_None, S_SCNCPOD_BUILD27, 6 },
    { SPR_DROP, 122, 5, A_None, S_SCNCPOD_BUILD28, 6 },
    { SPR_DROP, 123, 5, A_None, S_SCNCPOD_BUILD29, 6 },
    { SPR_DROP, 124, 4, A_None, S_SCNCPOD_BUILD30, 6 },
    { SPR_DROP, 125, 5, A_None, S_SCNCPOD_BUILD31, 6 },
    { SPR_DROP, 126, 5, A_None, S_SCNCPOD_BUILD32, 6 },
    { SPR_DROP, 127, 5, A_None, S_SCNCPOD_BUILD33, 6 },
    { SPR_DROP, 128, 4, A_None, S_SCNCPOD_BUILD34, 6 },
    { SPR_DROP, 129, 5, A_None, S_SCNCPOD_BUILD35, 6 },
    { SPR_DROP, 130, 5, A_None, S_SCNCPOD_BUILD36, 6 },
    { SPR_DROP, 131, 5, A_None, S_SCNCPOD_BUILD37, 6 },
    { SPR_DROP, 132, 4, A_None, S_SCNCPOD_BUILD38, 6 },
    { SPR_DROP, 133, 5, A_None, S_SCNCPOD_BUILD39, 6 },
    { SPR_DROP, 134, 5, A_None, S_SCNCPOD_BUILD40, 6 },
    { SPR_DROP, 135, 4, A_None, S_SCNCPOD_BUILD41, 6 },
    { SPR_DROP, 136, 5, A_None, S_SCNCPOD_BUILD42, 6 },
    { SPR_DROP, 137, 5, A_None, S_SCNCPOD_STND1, 6 },
    { SPR_DROP3, 0, 5, A_None, S_SCNCPOD2_BUILD2, 6 },
    { SPR_DROP3, 1, 4, A_None, S_SCNCPOD2_BUILD3, 6 },
    { SPR_DROP3, 2, 5, A_None, S_SCNCPOD2_BUILD4, 6 },
    { SPR_DROP3, 3, 5, A_None, S_SCNCPOD2_BUILD5, 6 },
    { SPR_DROP3, 4, 5, A_None, S_SCNCPOD2_BUILD6, 6 },
    { SPR_DROP3, 5, 4, A_None, S_SCNCPOD2_BUILD7, 6 },
    { SPR_DROP3, 6, 5, A_None, S_SCNCPOD2_BUILD8, 6 },
    { SPR_DROP3, 7, 5, A_None, S_SCNCPOD2_BUILD9, 6 },
    { SPR_DROP3, 8, 5, A_None, S_SCNCPOD2_BUILD10, 6 },
    { SPR_DROP3, 9, 4, A_None, S_SCNCPOD2_BUILD11, 6 },
    { SPR_DROP3, 10, 5, A_None, S_SCNCPOD2_BUILD12, 6 },
    { SPR_DROP3, 11, 5, A_None, S_SCNCPOD2_BUILD13, 6 },
    { SPR_DROP3, 12, 5, A_None, S_SCNCPOD2_BUILD14, 6 },
    { SPR_DROP3, 13, 4, A_None, S_SCNCPOD2_BUILD15, 6 },
    { SPR_DROP3, 14, 5, A_None, S_SCNCPOD2_BUILD16, 6 },
    { SPR_DROP3, 15, 5, A_None, S_SCNCPOD2_BUILD17, 6 },
    { SPR_DROP3, 16, 5, A_None, S_SCNCPOD2_BUILD18, 6 },
    { SPR_DROP3, 17, 4, A_None, S_SCNCPOD2_BUILD19, 6 },
    { SPR_DROP3, 18, 5, A_None, S_SCNCPOD2_BUILD20, 6 },
    { SPR_DROP3, 19, 5, A_None, S_SCNCPOD2_BUILD21, 6 },
    { SPR_DROP3, 20, 4, A_None, S_SCNCPOD2_BUILD22, 6 },
    { SPR_DROP3, 21, 5, A_None, S_SCNCPOD2_BUILD23, 6 },
    { SPR_DROP3, 22, 5, A_None, S_SCNCPOD2_BUILD24, 6 },
    { SPR_DROP3, 23, 5, A_None, S_SCNCPOD2_BUILD25, 6 },
    { SPR_DROP3, 24, 4, A_None, S_SCNCPOD2_BUILD26, 6 },
    { SPR_DROP3, 25, 5, A_None, S_SCNCPOD2_BUILD27, 6 },
    { SPR_DROP3, 26, 5, A_None, S_SCNCPOD2_BUILD28, 6 },
    { SPR_DROP3, 27, 5, A_None, S_SCNCPOD2_BUILD29, 6 },
    { SPR_DROP3, 28, 4, A_None, S_SCNCPOD2_BUILD30, 6 },
    { SPR_DROP3, 29, 5, A_None, S_SCNCPOD2_BUILD31, 6 },
    { SPR_DROP3, 30, 5, A_None, S_SCNCPOD2_BUILD32, 6 },
    { SPR_DROP3, 31, 5, A_None, S_SCNCPOD2_BUILD33, 6 },
    { SPR_DROP3, 32, 4, A_None, S_SCNCPOD2_BUILD34, 6 },
    { SPR_DROP3, 33, 5, A_None, S_SCNCPOD2_BUILD35, 6 },
    { SPR_DROP3, 34, 5, A_None, S_SCNCPOD2_BUILD36, 6 },
    { SPR_DROP3, 35, 5, A_None, S_SCNCPOD2_BUILD37, 6 },
    { SPR_DROP3, 36, 4, A_None, S_SCNCPOD2_STND1, 6 },
    { SPR_DROP4, 0, 5, A_None, S_ROBOPOD2_BUILD2, 6 },
    { SPR_DROP4, 1, 4, A_None, S_ROBOPOD2_BUILD3, 6 },
    { SPR_DROP4, 2, 5, A_None, S_ROBOPOD2_BUILD4, 6 },
    { SPR_DROP4, 3, 5, A_None, S_ROBOPOD2_BUILD5, 6 },
    { SPR_DROP4, 4, 5, A_None, S_ROBOPOD2_BUILD6, 6 },
    { SPR_DROP4, 5, 4, A_None, S_ROBOPOD2_BUILD7, 6 },
    { SPR_DROP4, 6, 5, A_None, S_ROBOPOD2_BUILD8, 6 },
    { SPR_DROP4, 7, 5, A_None, S_ROBOPOD2_BUILD9, 6 },
    { SPR_DROP4, 8, 5, A_None, S_ROBOPOD2_BUILD10, 6 },
    { SPR_DROP4, 9, 4, A_None, S_ROBOPOD2_BUILD11, 6 },
    { SPR_DROP4, 10, 5, A_None, S_ROBOPOD2_BUILD12, 6 },
    { SPR_DROP4, 11, 5, A_None, S_ROBOPOD2_BUILD13, 6 },
    { SPR_DROP4, 12, 5, A_None, S_ROBOPOD2_BUILD14, 6 },
    { SPR_DROP4, 13, 4, A_None, S_ROBOPOD2_BUILD15, 6 },
    { SPR_DROP4, 14, 5, A_None, S_ROBOPOD2_BUILD16, 6 },
    { SPR_DROP4, 15, 5, A_None, S_ROBOPOD2_BUILD17, 6 },
    { SPR_DROP4, 16, 5, A_None, S_ROBOPOD2_BUILD18, 6 },
    { SPR_DROP4, 17, 4, A_None, S_ROBOPOD2_BUILD19, 6 },
    { SPR_DROP4, 18, 5, A_None, S_ROBOPOD2_BUILD20, 6 },
    { SPR_DROP4, 19, 5, A_None, S_ROBOPOD2_BUILD21, 6 },
    { SPR_DROP4, 20, 4, A_None, S_ROBOPOD2_BUILD22, 6 },
    { SPR_DROP4, 21, 5, A_None, S_ROBOPOD2_BUILD23, 6 },
    { SPR_DROP4, 22, 5, A_None, S_ROBOPOD2_STND1, 6 },
    { SPR_HUBU, 41, -1, A_DC_BuildingStand, S_SCNCPOD_STND1, 1 },
    { SPR_HUBU, 43, 5, A_DC_BuildingStand, S_SCNCPOD2_STND2, 1 },
    { SPR_HUBU, 44, 4, A_DC_BuildingStand, S_SCNCPOD2_STND1, 1 },
    { SPR_HUBU, 87, 5, A_DC_BuildingStand, S_ROBOPOD2_STND2, 1 },
    { SPR_HUBU, 88, 4, A_DC_BuildingStand, S_ROBOPOD2_STND3, 1 },
    { SPR_HUBU, 89, 5, A_DC_BuildingStand, S_ROBOPOD2_STND4, 1 },
    { SPR_HUBU, 90, 5, A_DC_BuildingStand, S_ROBOPOD2_STND5, 1 },
    { SPR_HUBU, 91, 5, A_DC_BuildingStand, S_ROBOPOD2_STND6, 1 },
    { SPR_HUBU, 92, 4, A_DC_BuildingStand, S_ROBOPOD2_STND7, 1 },
    { SPR_HUBU, 93, 5, A_DC_BuildingStand, S_ROBOPOD2_STND8, 1 },
    { SPR_HUBU, 94, 5, A_DC_BuildingStand, S_ROBOPOD2_STND9, 1 },
    { SPR_HUBU, 95, 5, A_DC_BuildingStand, S_ROBOPOD2_STND10, 1 },
    { SPR_HUBU, 96, 4, A_DC_BuildingStand, S_ROBOPOD2_STND11, 1 },
    { SPR_HUBU, 97, 5, A_DC_BuildingStand, S_ROBOPOD2_STND12, 1 },
    { SPR_HUBU, 98, 5, A_DC_BuildingStand, S_ROBOPOD2_STND13, 1 },
    { SPR_HUBU, 99, 5, A_DC_BuildingStand, S_ROBOPOD2_STND14, 1 },
    { SPR_HUBU, 100, 4, A_DC_BuildingStand, S_ROBOPOD2_STND15, 1 },
    { SPR_HUBU, 101, 5, A_DC_BuildingStand, S_ROBOPOD2_STND16, 1 },
    { SPR_HUBU, 102, 5, A_DC_BuildingStand, S_ROBOPOD2_STND17, 1 },
    { SPR_HUBU, 103, 5, A_DC_BuildingStand, S_ROBOPOD2_STND18, 1 },
    { SPR_HUBU, 104, 4, A_DC_BuildingStand, S_ROBOPOD2_STND19, 1 },
    { SPR_HUBU, 105, 5, A_DC_BuildingStand, S_ROBOPOD2_STND20, 1 },
    { SPR_HUBU, 106, 5, A_DC_BuildingStand, S_ROBOPOD2_STND1, 1 },
    { SPR_DROP, 11, 0, A_DC_Drop, S_DROP_MOVE1, 6 },
    /* VENTSTAND0: complete FIN frames 19–38, at the native 66 ms tick. */
    { SPR_VENT, 23, 8, A_DC_Vent, S_VENT_ACTIVE2, 0 },
    { SPR_VENT, 24, 8, A_DC_Vent, S_VENT_ACTIVE3, 0 },
    { SPR_VENT, 25, 4, A_DC_Vent, S_VENT_ACTIVE4, 0 },
    { SPR_VENT, 26, 4, A_DC_Vent, S_VENT_ACTIVE5, 0 },
    { SPR_VENT, 27, 4, A_DC_Vent, S_VENT_ACTIVE6, 0 },
    { SPR_VENT, 28, 4, A_DC_Vent, S_VENT_ACTIVE7, 0 },
    { SPR_VENT, 29, 4, A_DC_Vent, S_VENT_ACTIVE8, 0 },
    { SPR_VENT, 30, 4, A_DC_Vent, S_VENT_ACTIVE9, 0 },
    { SPR_VENT, 31, 4, A_DC_Vent, S_VENT_ACTIVE10, 0 },
    { SPR_VENT, 32, 4, A_DC_Vent, S_VENT_ACTIVE11, 0 },
    { SPR_VENT, 33, 3, A_DC_Vent, S_VENT_ACTIVE12, 0 },
    { SPR_VENT, 34, 4, A_DC_Vent, S_VENT_ACTIVE13, 0 },
    { SPR_VENT, 35, 4, A_DC_Vent, S_VENT_ACTIVE14, 0 },
    { SPR_VENT, 36, 4, A_DC_Vent, S_VENT_ACTIVE15, 0 },
    { SPR_VENT, 37, 4, A_DC_Vent, S_VENT_ACTIVE16, 0 },
    { SPR_VENT, 38, 4, A_DC_Vent, S_VENT_ACTIVE17, 0 },
    { SPR_VENT, 39, 4, A_DC_Vent, S_VENT_ACTIVE18, 0 },
    { SPR_VENT, 40, 4, A_DC_Vent, S_VENT_ACTIVE19, 0 },
    { SPR_VENT, 41, 4, A_DC_Vent, S_VENT_ACTIVE20, 0 },
    { SPR_VENT, 42, 4, A_DC_Vent, S_VENT_ACTIVE1, 0 },
    /* BEACSTAND2: base, then base plus the authored light command. */
    { SPR_BEAC, 2, 2, A_None, S_BEAC_STAND2, 0 },
    { SPR_BEAC, 3, 4, A_None, S_BEAC_STAND1, 0 },
    /* Hidden states retain the terrain crater and poll for reactivation. */
    { SPR_VENT, 23, 1, A_DC_Vent, S_VENT_ATTACHED, 0 },
    { SPR_VENT, 23, 1, A_DC_Vent, S_VENT_EXHAUSTED, 0 },
    /* ROBOPODSTAND0: complete native FIN sequence, 66 ms native ticks. */
    { SPR_HUBU, 67, 4, A_DC_BuildingStand, S_ROBOPOD_STND2, 1 },
    { SPR_HUBU, 68, 4, A_DC_BuildingStand, S_ROBOPOD_STND3, 1 },
    { SPR_HUBU, 69, 4, A_DC_BuildingStand, S_ROBOPOD_STND4, 1 },
    { SPR_HUBU, 70, 4, A_DC_BuildingStand, S_ROBOPOD_STND5, 1 },
    { SPR_HUBU, 71, 4, A_DC_BuildingStand, S_ROBOPOD_STND6, 1 },
    { SPR_HUBU, 72, 4, A_DC_BuildingStand, S_ROBOPOD_STND7, 1 },
    { SPR_HUBU, 73, 4, A_DC_BuildingStand, S_ROBOPOD_STND8, 1 },
    { SPR_HUBU, 74, 4, A_DC_BuildingStand, S_ROBOPOD_STND9, 1 },
    { SPR_HUBU, 75, 4, A_DC_BuildingStand, S_ROBOPOD_STND10, 1 },
    { SPR_HUBU, 76, 4, A_DC_BuildingStand, S_ROBOPOD_STND11, 1 },
    { SPR_HUBU, 77, 4, A_DC_BuildingStand, S_ROBOPOD_STND12, 1 },
    { SPR_HUBU, 78, 4, A_DC_BuildingStand, S_ROBOPOD_STND13, 1 },
    { SPR_HUBU, 79, 3, A_DC_BuildingStand, S_ROBOPOD_STND14, 1 },
    { SPR_HUBU, 80, 4, A_DC_BuildingStand, S_ROBOPOD_STND15, 1 },
    { SPR_HUBU, 81, 4, A_DC_BuildingStand, S_ROBOPOD_STND16, 1 },
    { SPR_HUBU, 82, 4, A_DC_BuildingStand, S_ROBOPOD_STND17, 1 },
    { SPR_HUBU, 83, 4, A_DC_BuildingStand, S_ROBOPOD_STND18, 1 },
    { SPR_HUBU, 84, 4, A_DC_BuildingStand, S_ROBOPOD_STND19, 1 },
    { SPR_HUBU, 85, 4, A_DC_BuildingStand, S_ROBOPOD_STND20, 1 },
    { SPR_HUBU, 86, 4, A_DC_BuildingStand, S_ROBOPOD_STND1, 1 },
    /* RSCHPODSTAND0: complete native FIN sequence, 66 ms native ticks. */
    { SPR_HUBU, 28, 4, A_DC_BuildingStand, S_RSCHPOD_STND2, 1 },
    { SPR_HUBU, 29, 4, A_DC_BuildingStand, S_RSCHPOD_STND3, 1 },
    { SPR_HUBU, 30, 4, A_DC_BuildingStand, S_RSCHPOD_STND4, 1 },
    { SPR_HUBU, 31, 4, A_DC_BuildingStand, S_RSCHPOD_STND5, 1 },
    { SPR_HUBU, 32, 4, A_DC_BuildingStand, S_RSCHPOD_STND6, 1 },
    { SPR_HUBU, 33, 4, A_DC_BuildingStand, S_RSCHPOD_STND7, 1 },
    { SPR_HUBU, 34, 4, A_DC_BuildingStand, S_RSCHPOD_STND8, 1 },
    { SPR_HUBU, 35, 4, A_DC_BuildingStand, S_RSCHPOD_STND9, 1 },
    { SPR_HUBU, 36, 23, A_DC_BuildingStand, S_RSCHPOD_STND1, 1 },
    { SPR_DISH, 3, 4, A_None, S_DISH_STND2, 1 },
    { SPR_DISH, 4, 4, A_None, S_DISH_STND3, 1 },
    { SPR_DISH, 5, 4, A_None, S_DISH_STND4, 1 },
    { SPR_DISH, 6, 4, A_None, S_DISH_STND5, 1 },
    { SPR_DISH, 7, 4, A_None, S_DISH_STND6, 1 },
    { SPR_DISH, 8, 4, A_None, S_DISH_STND7, 1 },
    { SPR_DISH, 9, 4, A_None, S_DISH_STND8, 1 },
    { SPR_DISH, 10, 4, A_None, S_DISH_STND9, 1 },
    { SPR_DISH, 11, 4, A_None, S_DISH_STND10, 1 },
    { SPR_DISH, 12, 4, A_None, S_DISH_STND11, 1 },
    { SPR_DISH, 13, 4, A_None, S_DISH_STND12, 1 },
    { SPR_DISH, 14, 4, A_None, S_DISH_STND13, 1 },
    { SPR_DISH, 15, 3, A_None, S_DISH_STND14, 1 },
    { SPR_DISH, 16, 4, A_None, S_DISH_STND15, 1 },
    { SPR_DISH, 17, 4, A_None, S_DISH_STND16, 1 },
    { SPR_DISH, 18, 4, A_None, S_DISH_STND17, 1 },
    { SPR_DISH, 19, 4, A_None, S_DISH_STND1, 1 },
#define DC_BLOOD_LABEL(name, state)
#define DC_BLOOD_STATE(id, sprite, frame, tics, next) { sprite, frame, tics, NULL, next, 0 },
#include "blood_states.inc"
#define DC_BUILDING_LABEL(type, action, first, last)
#define DC_BUILDING_STATE(id, sprite, frame, tics, action, next, group) \
    { sprite, frame, tics, action, next, group },
#include "building_states.inc"
#undef DC_BUILDING_STATE
#undef DC_BUILDING_LABEL
#undef DC_BLOOD_STATE
#undef DC_BLOOD_LABEL
};

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {
    { // MT_NULL
        0,
    },
    { // MT_TROOPER
        .doomednum = 1,
        .spawnstate = S_TRSC_STND,
        .spawnhealth = 800,
        .seestate = S_TRSC_RUN1,
        .missilestate = S_TRSC_ATK1,
        .deathstate = S_TRSC_DIE1,
        .xdeathstate = S_TRSC_DIE1,
        .speed = 5,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .damage = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_GREY
        .doomednum = 2,
        .spawnstate = S_GRAY_STND,
        .spawnhealth = 800,
        .seestate = S_GRAY_RUN1,
        .missilestate = S_GRAY_ATK1,
        .deathstate = S_GRAY_DIE1,
        .xdeathstate = S_GRAY_DIE1,
        .speed = 5,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .damage = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_EXPLOITER
        .doomednum = 3,
        .spawnstate = S_EXPL_STND,
        .spawnhealth = 800,
        .seestate = S_EXPL_RUN1,
        .deathstate = S_EXPL_DIE1,
        .xdeathstate = S_EXPL_DIE1,
        .speed = 5,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_REAPER
        .doomednum = 2,
        .spawnstate = S_REAP_STND,
        .spawnhealth = 800,
        .seestate = S_REAP_RUN1,
        .missilestate = S_REAP_ATK1,
        .deathstate = S_REAP_DIE_SELECT,
        .xdeathstate = S_REAP_DIE_SELECT,
        .speed = 6,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .damage = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_THUNDERBOLT
        .doomednum = 3,
        .spawnstate = S_BARR_STND,
        .spawnhealth = 400,
        .seestate = S_BARR_RUN1,
        .deathstate = S_BARR_DIE1,
        .xdeathstate = S_BARR_DIE1,
        .speed = 3,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_CYBORG
        .doomednum = 4,
        .spawnstate = S_SARG_STND,
        .spawnhealth = 800,
        .seestate = S_SARG_RUN1,
        .deathstate = S_SARG_DIE1,
        .xdeathstate = S_SARG_DIE1,
        .speed = 9,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_SCOUT
        .doomednum = 5,
        .spawnstate = S_SCGM_STND,
        .spawnhealth = 800,
        .seestate = S_SCGM_RUN1,
        .deathstate = S_SCGM_DIE1,
        .xdeathstate = S_SCGM_DIE1,
        .speed = 9,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_ORTU
        .spawnstate = S_ORTU_STND,
        .spawnhealth = 800,
        .seestate = S_ORTU_RUN1,
        .deathstate = S_ORTU_DIE1,
        .xdeathstate = S_ORTU_DIE1,
        .speed = 5,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_SLUG
        .spawnstate = S_SLUG_STND,
        .spawnhealth = 800,
        .seestate = S_SLUG_RUN1,
        .deathstate = S_SLUG_DIE1,
        .xdeathstate = S_SLUG_DIE1,
        .speed = 5,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_MOBILE_TOWER
        .spawnstate = S_TURR_STND,
        .spawnhealth = 800,
        .missilestate = S_TURR_FIRE,
        .deathstate = S_TURR_DIE1,
        .xdeathstate = S_TURR_DIE1,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_DROP_LINK
        .spawnstate = S_CENT_STND1,
        .spawnhealth = 800,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_RENDERABLE,
    },
    { // MT_ALIEN_COM
        .spawnstate = S_TONG_STND1,
        .spawnhealth = 800,
        .deathstate = S_TONG_DIE1,
        .xdeathstate = S_TONG_DIE1,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_VISION_SIGHT
        .spawnstate = S_DOTT_STND,
        .spawnhealth = 300,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_RENDERABLE,
    },
    { // MT_DROPSHIP
        .spawnstate = S_DROP_MOVE1,
        .spawnhealth = 800,
        .speed = 1,
        .radius = 16,
        .height = 32,
        .mass = 100,
        .flags = MF_RENDERABLE|MF_FLY,
        .spawnz = 50 * FIXED_ONE / 32, /* Requested 50 px altitude; DC cells are 32 px. */
    },
    { // MT_BLOOD
        .spawnstate = S_NULL,
        .flags = MF_RENDERABLE|MF_NOBLOCKMAP,
    },
    { // MT_VENT
        .spawnstate = S_VENT_EXHAUSTED,
        .flags = MF_RENDERABLE|MF_NOBLOCKMAP,
    },
    { // MT_BEACON
        .spawnstate = S_BEAC_STAND1,
        .spawnhealth = 800,
        .flags = MF_RENDERABLE|MF_NOBLOCKMAP,
    },
    [MT_EXCOPOD] = { .doomednum = 16, .spawnstate = S_EXCOPOD_STND,
        .deathstate = S_EXCOPODDIE0_191,
        .spawnhealth = 4800, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_BRRKPOD] = { .doomednum = 17, .spawnstate = S_BRRKPOD_STND,
        .deathstate = S_BRRKPODDIE0_112,
        .spawnhealth = 2400, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ROBOPOD] = { .doomednum = 18, .spawnstate = S_ROBOPOD_STND1,
        .deathstate = S_ROBOPODDIE0_147,
        .spawnhealth = 2400, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ROBOPOD2] = { .doomednum = 19, .spawnstate = S_ROBOPOD2_STND1,
        .deathstate = S_ROBOPOD2DIE0_217,
        .spawnhealth = 3600, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_SCNCPOD] = { .doomednum = 20, .spawnstate = S_SCNCPOD_STND1,
        .deathstate = S_SCNCPODDIE0_321,
        .spawnhealth = 2400, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_SCNCPOD2] = { .doomednum = 21, .spawnstate = S_SCNCPOD2_STND1,
        .deathstate = S_SCNCPOD2DIE0_353,
        .spawnhealth = 3600, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_RSCHPOD] = { .doomednum = 22, .spawnstate = S_RSCHPOD_STND1,
        .deathstate = S_RSCHPODDIE0_182,
        .spawnhealth = 3600, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ALIEN_MINDHIVE] = { .doomednum = 28, .spawnstate = S_ALIEN_MINDHIVE_STND,
        .spawnhealth = 4800, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ALIEN_WARHIVE] = { .doomednum = 29, .spawnstate = S_ALIEN_WARHIVE_STND,
        .spawnhealth = 2400, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ALIEN_BRDRHIVE] = { .doomednum = 30, .spawnstate = S_ALIEN_BRDRHIVE_STND,
        .spawnhealth = 2400, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ALIEN_BRDRHIVE2] = { .doomednum = 31, .spawnstate = S_ALIEN_BRDRHIVE2_STND,
        .spawnhealth = 3600, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ALIEN_MINDHIVE2] = { .doomednum = 32, .spawnstate = S_ALIEN_MINDHIVE2_STND,
        .spawnhealth = 2400, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ALIEN_MINDHIVE3] = { .doomednum = 33, .spawnstate = S_ALIEN_MINDHIVE3_STND,
        .spawnhealth = 3600, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_ALIEN_RSCHIVE] = { .doomednum = 34, .spawnstate = S_ALIEN_RSCHIVE_STND,
        .spawnhealth = 3600, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_COMMS_DISH] = { .doomednum = 86, .spawnstate = S_DISH_STND1,
        .spawnhealth = 1200, .flags = MF_SELECTABLE | MF_RENDERABLE },
    [MT_CITY_TOWER] = { .doomednum = 81, .spawnstate = S_TOWR_STND,
        .spawnhealth = 1600, .flags = MF_RENDERABLE },
};

const gameinfo_t game_info = {
    sprnames,
    NUMSPRITES,
    states,
    NUMSTATES,
    mobjinfo,
    NUMMOBJTYPES,
    S_NULL,
    RTS_STATE_COORDS_FIN_TOP_LEFT,
    { .style = SELECTION_STYLE_SPRITE, .image = "INTRFACE/CLIENT.SPR",
      .healthy_frame = 0, .wounded_frame = 1, .critical_frame = 3, .top_offset_y = -3 },
    NULL,
};
