/* Generated from retail DEFTXT and the OpenDR sprite catalog. Do not edit by hand. */
#include "engine.h"
#include "dark-reign.h"
#include "info.h"

const char *const sprnames[NUMSPRITES] = {
    "ucfcnst0.spr",
    "ucfrgst0.spr",
    "uchfrst0.spr",
    "ufradst0.spr",
    "ufmrcst0.spr",
    "ufsnpst0.spr",
    "ufsctst0.spr",
    "ufmedst0.spr",
    "ufsabst0.spr",
    "ufmecst0.spr",
    "ufmtrst0.spr",
    "ucinfst0.spr",
    "ufspbst0.spr",
    "ufratst0.spr",
    "ufsktst0.spr",
    "ufthnst0.spr",
    "ufphtst0.spr",
    "ufflkst0.spr",
    "uftrtst0.spr",
    "uffarst0.spr",
    "ufskbst0.spr",
    "ufoutst0.spr",
    "ufswvst0.spr",
    "ucwcost0.spr",
    "ufphrst0.spr",
    "ufbamst0.spr",
    "uigrdst0.spr",
    "uibonst0.spr",
    "uiextst0.spr",
    "uisttst0.spr",
    "uiittst0.spr",
    "uipltst0.spr",
    "uiampst0.spr",
    "uimadst0.spr",
    "uirdrst0.spr",
    "uishrst0.spr",
    "uihosst0.spr",
    "uitctst0.spr",
    "uiiarst0.spr",
    "uicycst0.spr",
    "uiskyst0.spr",
    "ucfcnst0.spr",
    "ucfrgst0.spr",
    "uchfrst0.spr",
    "ucinfst0.spr",
    "ufmtrst0.spr",
    "ucwcost0.spr",
    "uiittst0.spr",
    "uipltst0.spr",
    "uitctst0.spr",
    "uimadst0.spr",
    "uishrst0.spr",
    "uiiarst0.spr",
    "uocvmst0.spr",
    "uorcmst0.spr",
    "uocspst0.spr",
    "uocvmst0.spr",
    "uorcmst0.spr",
    "uocspst0.spr",
    "uocvmst0.spr",
    "uowtrst0.spr",
    "uohtrst0.spr",
    "nfhqt1l0.spr",
    "nfhqt2l0.spr",
    "nfhqt3l0.spr",
    "nfutf1l0.spr",
    "nfutf2l0.spr",
    "nfvcy1l0.spr",
    "nfvcy2l0.spr",
    "nfhsp1l0.spr",
    "nfrep1l0.spr",
    "nfphf1l0.spr",
    "nfphf2l0.spr",
    "nccam1l0.spr",
    "nclnc1l0.spr",
    "ncpow1l0.spr",
    "nfrrm1l0.spr",
    "ncsbh1l0.spr",
    "ncsbv1l0.spr",
    "ncsbc1l0.spr",
    "nfgdt1l0.spr",
    "nfagt1l0.spr",
    "nfaar1l0.spr",
    "nihqt1l0.spr",
    "nihqt2l0.spr",
    "nihqt3l0.spr",
    "niutf1l0.spr",
    "niutf2l0.spr",
    "nivcy1l0.spr",
    "nivcy2l0.spr",
    "nihsp1l0.spr",
    "nirep1l0.spr",
    "nitgt1l0.spr",
    "nirrm1l0.spr",
    "nitrc1l0.spr",
    "nigdt1l0.spr",
    "niagt1l0.spr",
    "niaar1l0.spr",
    "nccam1l0.spr",
    "nclnc1l0.spr",
    "ncpow1l0.spr",
    "ncsbh1l0.spr",
    "ncsbv1l0.spr",
    "ncsbc1l0.spr",
    "ncswl1l0.spr",
    "ncswm1l0.spr",
    "ncbwl1l0.spr",
    "ncbwm1l0.spr",
    "nfvcy1l0.spr",
    "nfvcy2l0.spr",
    "nfphf1l0.spr",
    "nfphf2l0.spr",
    "nfhqt1l0.spr",
    "nfhqt2l0.spr",
    "nfhqt3l0.spr",
    "nfutf2l0.spr",
    "nfhsp1l0.spr",
    "nfrep1l0.spr",
    "nfrrm1l0.spr",
    "ncpow1l0.spr",
    "nfutf1l0.spr",
    "nocen1l0.spr",
    "ncwel1l0.spr",
    "ncmin1l0.spr",
    "nowat1l0.spr",
    "nohov1l0.spr",
    "nodes1l0.spr",
    "nomdr1l0.spr",
    "noshl1l0.spr",
    "nosub1l0.spr",
    "notcn1l0.spr",
    "notyh1l0.spr",
    "nothq1l0.spr",
    "nomlt1l0.spr",
    "notdr1l0.spr",
    "norvp1l0.spr",
    "nopld1l0.spr",
    "nocbs1l0.spr",
    "nowar1l0.spr",
    "nopri1l0.spr",
    "nochm4l0.spr",
    "nofrm1l0.spr",
    "nofrm1l1.spr",
    "nofrm1l2.spr",
    "nobrd1l0.spr",
    "nobrd1l1.spr",
    "ncsbh1l0.spr",
    "ncsbv1l0.spr",
    "ncsbc1l0.spr",
};

const state_t states[NUMSTATES] = {
    { 0, 0, 0, -1, NULL, S_NULL, 0, NULL },
    [S_UCFCNST0_STND] = { SPR_UCFCNST0, 6, 1, -1, NULL, S_UCFCNST0_STND, 0, NULL },
    [S_UCFCNST0_RUN1] = { SPR_UCFCNST0, 0, 6, 4, NULL, S_UCFCNST0_RUN1, 2, NULL },
    [S_UCFRGST0_STND] = { SPR_UCFRGST0, 0, 1, -1, NULL, S_UCFRGST0_STND, 0, NULL },
    [S_UCFRGST0_RUN1] = { SPR_UCFRGST0, 0, 3, 6, NULL, S_UCFRGST0_RUN1, 2, NULL },
    [S_UCFRGST0_HARVEST1] = { SPR_UCFRGST0, 3, 15, 0, NULL, S_UCFRGST0_STND, 5, TICS(4,3,4,3,3,4,3,3,4,3,4,3,3,4,3) },
    [S_UCHFRST0_STND] = { SPR_UCHFRST0, 0, 1, 20, A_Look, S_UCHFRST0_STND, 0, NULL },
    [S_UCHFRST0_RUN1] = { SPR_UCHFRST0, 0, 1, 6, A_Chase, S_UCHFRST0_RUN1, 2, NULL },
    [S_UCHFRST0_HARVEST1] = { SPR_UCHFRST0, 1, 15, 0, NULL, S_UCHFRST0_STND, 5, TICS(4,3,4,3,3,4,3,3,4,3,4,3,3,4,3) },
    [S_UCHFRST0_FIRE] = { SPR_UCHFRST0, 0, 1, 1, A_Attack, S_UCHFRST0_STND, 3, NULL },
    [S_UFRADST0_STND] = { SPR_UFRADST0, 15, 1, 20, A_Look, S_UFRADST0_STND, 0, NULL },
    [S_UFRADST0_RUN1] = { SPR_UFRADST0, 0, 1, 2, A_Chase, S_UFRADST0_RUN2, 2, NULL },
    [S_UFRADST0_RUN2] = { SPR_UFRADST0, 1, 5, 2, NULL, S_UFRADST0_RUN1, 2, NULL },
    [S_UFRADST0_SHOOT1] = { SPR_UFRADST0, 6, 1, 2, A_Attack, S_UFRADST0_SHOOT2, 3, NULL },
    [S_UFRADST0_SHOOT2] = { SPR_UFRADST0, 7, 1, 2, NULL, S_UFRADST0_STND, 3, NULL },
    [S_UFRADST0_IDLE1] = { SPR_UFRADST0, 8, 7, 10, NULL, S_UFRADST0_IDLE1, 0, NULL },
    [S_UFMRCST0_STND] = { SPR_UFMRCST0, 18, 1, 20, A_Look, S_UFMRCST0_STND, 0, NULL },
    [S_UFMRCST0_RUN1] = { SPR_UFMRCST0, 0, 1, 2, A_Chase, S_UFMRCST0_RUN2, 2, NULL },
    [S_UFMRCST0_RUN2] = { SPR_UFMRCST0, 1, 5, 2, NULL, S_UFMRCST0_RUN1, 2, NULL },
    [S_UFMRCST0_SHOOT1] = { SPR_UFMRCST0, 6, 1, 2, A_Attack, S_UFMRCST0_SHOOT2, 3, NULL },
    [S_UFMRCST0_SHOOT2] = { SPR_UFMRCST0, 7, 1, 2, NULL, S_UFMRCST0_STND, 3, NULL },
    [S_UFMRCST0_IDLE1] = { SPR_UFMRCST0, 8, 5, 10, NULL, S_UFMRCST0_IDLE1, 0, NULL },
    [S_UFSNPST0_STND] = { SPR_UFSNPST0, 30, 1, 20, A_Look, S_UFSNPST0_STND, 0, NULL },
    [S_UFSNPST0_RUN1] = { SPR_UFSNPST0, 0, 1, 6, A_Chase, S_UFSNPST0_RUN2, 2, NULL },
    [S_UFSNPST0_RUN2] = { SPR_UFSNPST0, 1, 5, 6, NULL, S_UFSNPST0_RUN1, 2, NULL },
    [S_UFSNPST0_SHOOT1] = { SPR_UFSNPST0, 9, 1, 6, A_Attack, S_UFSNPST0_SHOOT2, 3, NULL },
    [S_UFSNPST0_SHOOT2] = { SPR_UFSNPST0, 10, 3, 6, NULL, S_UFSNPST0_STND, 3, NULL },
    [S_UFSNPST0_IDLE1] = { SPR_UFSNPST0, 30, 1, 10, NULL, S_UFSNPST0_IDLE1, 0, NULL },
    [S_UFSCTST0_STND] = { SPR_UFSCTST0, 19, 1, -1, NULL, S_UFSCTST0_STND, 0, NULL },
    [S_UFSCTST0_RUN1] = { SPR_UFSCTST0, 0, 8, 6, NULL, S_UFSCTST0_RUN1, 2, NULL },
    [S_UFSCTST0_SHOOT1] = { SPR_UFSCTST0, 8, 3, 6, NULL, S_UFSCTST0_STND, 3, NULL },
    [S_UFSCTST0_IDLE1] = { SPR_UFSCTST0, 19, 1, 10, NULL, S_UFSCTST0_IDLE1, 0, NULL },
    [S_UFMEDST0_STND] = { SPR_UFMEDST0, 22, 1, 20, A_Look, S_UFMEDST0_STND, 0, NULL },
    [S_UFMEDST0_RUN1] = { SPR_UFMEDST0, 0, 1, 6, A_Chase, S_UFMEDST0_RUN2, 2, NULL },
    [S_UFMEDST0_RUN2] = { SPR_UFMEDST0, 1, 5, 6, NULL, S_UFMEDST0_RUN1, 2, NULL },
    [S_UFMEDST0_SHOOT1] = { SPR_UFMEDST0, 6, 1, 6, A_Attack, S_UFMEDST0_SHOOT2, 3, NULL },
    [S_UFMEDST0_SHOOT2] = { SPR_UFMEDST0, 7, 9, 6, NULL, S_UFMEDST0_STND, 3, NULL },
    [S_UFMEDST0_IDLE1] = { SPR_UFMEDST0, 16, 6, 10, NULL, S_UFMEDST0_IDLE1, 0, NULL },
    [S_UFSABST0_STND] = { SPR_UFSABST0, 8, 1, -1, NULL, S_UFSABST0_STND, 0, NULL },
    [S_UFSABST0_RUN1] = { SPR_UFSABST0, 0, 8, 6, NULL, S_UFSABST0_RUN1, 2, NULL },
    [S_UFMECST0_STND] = { SPR_UFMECST0, 24, 1, 20, A_Look, S_UFMECST0_STND, 0, NULL },
    [S_UFMECST0_RUN1] = { SPR_UFMECST0, 0, 1, 6, A_Chase, S_UFMECST0_RUN2, 2, NULL },
    [S_UFMECST0_RUN2] = { SPR_UFMECST0, 1, 7, 6, NULL, S_UFMECST0_RUN1, 2, NULL },
    [S_UFMECST0_SHOOT1] = { SPR_UFMECST0, 8, 1, 6, A_Attack, S_UFMECST0_SHOOT2, 3, NULL },
    [S_UFMECST0_SHOOT2] = { SPR_UFMECST0, 9, 7, 6, NULL, S_UFMECST0_STND, 3, NULL },
    [S_UFMTRST0_STND] = { SPR_UFMTRST0, 25, 1, 20, A_Look, S_UFMTRST0_STND, 0, NULL },
    [S_UFMTRST0_RUN1] = { SPR_UFMTRST0, 0, 1, 6, A_Chase, S_UFMTRST0_RUN2, 2, NULL },
    [S_UFMTRST0_RUN2] = { SPR_UFMTRST0, 1, 5, 6, NULL, S_UFMTRST0_RUN1, 2, NULL },
    [S_UFMTRST0_SHOOT1] = { SPR_UFMTRST0, 6, 1, 6, A_Attack, S_UFMTRST0_SHOOT2, 3, NULL },
    [S_UFMTRST0_SHOOT2] = { SPR_UFMTRST0, 7, 15, 6, NULL, S_UFMTRST0_STND, 3, NULL },
    [S_UFMTRST0_IDLE1] = { SPR_UFMTRST0, 22, 4, 10, NULL, S_UFMTRST0_IDLE1, 0, NULL },
    [S_UCINFST0_STND] = { SPR_UCINFST0, 8, 1, -1, NULL, S_UCINFST0_STND, 0, NULL },
    [S_UCINFST0_RUN1] = { SPR_UCINFST0, 0, 8, 6, NULL, S_UCINFST0_RUN1, 2, NULL },
    [S_UCINFST0_IDLE1] = { SPR_UCINFST0, 8, 3, 10, NULL, S_UCINFST0_IDLE1, 0, NULL },
    [S_UFSPBST0_STND] = { SPR_UFSPBST0, 4, 1, 20, A_Look, S_UFSPBST0_STND, 0, NULL },
    [S_UFSPBST0_RUN1] = { SPR_UFSPBST0, 0, 1, 6, A_Chase, S_UFSPBST0_RUN2, 2, NULL },
    [S_UFSPBST0_RUN2] = { SPR_UFSPBST0, 1, 2, 6, NULL, S_UFSPBST0_RUN1, 2, NULL },
    [S_UFSPBST0_SHOOT1] = { SPR_UFSPBST0, 3, 1, 6, A_Attack, S_UFSPBST0_STND, 3, NULL },
    [S_UFRATST0_STND] = { SPR_UFRATST0, 0, 1, -1, NULL, S_UFRATST0_STND, 0, NULL },
    [S_UFRATST0_RUN1] = { SPR_UFRATST0, 0, 3, 6, NULL, S_UFRATST0_RUN1, 2, NULL },
    [S_UFSKTST0_STND] = { SPR_UFSKTST0, 0, 1, 20, A_Look, S_UFSKTST0_STND, 0, NULL },
    [S_UFSKTST0_RUN1] = { SPR_UFSKTST0, 0, 1, 6, A_Chase, S_UFSKTST0_RUN2, 2, NULL },
    [S_UFSKTST0_RUN2] = { SPR_UFSKTST0, 1, 2, 6, NULL, S_UFSKTST0_RUN1, 2, NULL },
    [S_UFSKTST0_FIRE] = { SPR_UFSKTST0, 0, 1, 1, A_Attack, S_UFSKTST0_STND, 3, NULL },
    [S_UFTHNST0_STND] = { SPR_UFTHNST0, 0, 1, 20, A_Look, S_UFTHNST0_STND, 0, NULL },
    [S_UFTHNST0_RUN1] = { SPR_UFTHNST0, 0, 1, 6, A_Chase, S_UFTHNST0_RUN2, 2, NULL },
    [S_UFTHNST0_RUN2] = { SPR_UFTHNST0, 1, 2, 6, NULL, S_UFTHNST0_RUN1, 2, NULL },
    [S_UFTHNST0_SHOOT1] = { SPR_UFTHNST0, 3, 1, 6, A_Attack, S_UFTHNST0_SHOOT2, 3, NULL },
    [S_UFTHNST0_SHOOT2] = { SPR_UFTHNST0, 4, 3, 6, NULL, S_UFTHNST0_STND, 3, NULL },
    [S_UFPHTST0_STND] = { SPR_UFPHTST0, 0, 1, 20, A_Look, S_UFPHTST0_STND, 0, NULL },
    [S_UFPHTST0_RUN1] = { SPR_UFPHTST0, 0, 1, 6, A_Chase, S_UFPHTST0_RUN2, 2, NULL },
    [S_UFPHTST0_RUN2] = { SPR_UFPHTST0, 1, 2, 6, NULL, S_UFPHTST0_RUN1, 2, NULL },
    [S_UFPHTST0_SHOOT1] = { SPR_UFPHTST0, 3, 1, 6, A_Attack, S_UFPHTST0_STND, 3, NULL },
    [S_UFFLKST0_STND] = { SPR_UFFLKST0, 0, 1, 20, A_Look, S_UFFLKST0_STND, 0, NULL },
    [S_UFFLKST0_RUN1] = { SPR_UFFLKST0, 0, 1, 3, A_Chase, S_UFFLKST0_RUN2, 2, NULL },
    [S_UFFLKST0_RUN2] = { SPR_UFFLKST0, 1, 7, 3, NULL, S_UFFLKST0_RUN1, 2, NULL },
    [S_UFFLKST0_SHOOT1] = { SPR_UFFLKST0, 8, 1, 6, A_Attack, S_UFFLKST0_SHOOT2, 3, NULL },
    [S_UFFLKST0_SHOOT2] = { SPR_UFFLKST0, 9, 2, 6, NULL, S_UFFLKST0_STND, 3, NULL },
    [S_UFTRTST0_STND] = { SPR_UFTRTST0, 0, 1, 20, A_Look, S_UFTRTST0_STND, 0, NULL },
    [S_UFTRTST0_RUN1] = { SPR_UFTRTST0, 0, 1, 6, A_Chase, S_UFTRTST0_RUN1, 2, NULL },
    [S_UFTRTST0_FIRE] = { SPR_UFTRTST0, 0, 1, 1, A_Attack, S_UFTRTST0_STND, 3, NULL },
    [S_UFFARST0_STND] = { SPR_UFFARST0, 0, 1, 20, A_Look, S_UFFARST0_STND, 0, NULL },
    [S_UFFARST0_RUN1] = { SPR_UFFARST0, 0, 1, 6, A_Chase, S_UFFARST0_RUN2, 2, NULL },
    [S_UFFARST0_RUN2] = { SPR_UFFARST0, 1, 2, 6, NULL, S_UFFARST0_RUN1, 2, NULL },
    [S_UFFARST0_SHOOT1] = { SPR_UFFARST0, 3, 1, 6, A_Attack, S_UFFARST0_SHOOT2, 3, NULL },
    [S_UFFARST0_SHOOT2] = { SPR_UFFARST0, 4, 1, 6, NULL, S_UFFARST0_STND, 3, NULL },
    [S_UFSKBST0_STND] = { SPR_UFSKBST0, 0, 1, 20, A_Look, S_UFSKBST0_STND, 0, NULL },
    [S_UFSKBST0_RUN1] = { SPR_UFSKBST0, 0, 1, 6, A_Chase, S_UFSKBST0_RUN1, 2, NULL },
    [S_UFSKBST0_FIRE] = { SPR_UFSKBST0, 0, 1, 1, A_Attack, S_UFSKBST0_STND, 3, NULL },
    [S_UFOUTST0_STND] = { SPR_UFOUTST0, 0, 1, 20, A_Look, S_UFOUTST0_STND, 0, NULL },
    [S_UFOUTST0_RUN1] = { SPR_UFOUTST0, 0, 1, 6, A_Chase, S_UFOUTST0_RUN1, 2, NULL },
    [S_UFOUTST0_FIRE] = { SPR_UFOUTST0, 0, 1, 1, A_Attack, S_UFOUTST0_STND, 3, NULL },
    [S_UFSWVST0_STND] = { SPR_UFSWVST0, 0, 1, 20, A_Look, S_UFSWVST0_STND, 0, NULL },
    [S_UFSWVST0_RUN1] = { SPR_UFSWVST0, 0, 1, 6, A_Chase, S_UFSWVST0_RUN2, 2, NULL },
    [S_UFSWVST0_RUN2] = { SPR_UFSWVST0, 1, 2, 6, NULL, S_UFSWVST0_RUN1, 2, NULL },
    [S_UFSWVST0_FIRE] = { SPR_UFSWVST0, 0, 1, 1, A_Attack, S_UFSWVST0_STND, 3, NULL },
    [S_UCWCOST0_STND] = { SPR_UCWCOST0, 0, 1, 20, A_Look, S_UCWCOST0_STND, 0, NULL },
    [S_UCWCOST0_RUN1] = { SPR_UCWCOST0, 0, 1, 6, A_Chase, S_UCWCOST0_RUN2, 2, NULL },
    [S_UCWCOST0_RUN2] = { SPR_UCWCOST0, 1, 3, 6, NULL, S_UCWCOST0_RUN1, 2, NULL },
    [S_UCWCOST0_FIRE] = { SPR_UCWCOST0, 0, 1, 1, A_Attack, S_UCWCOST0_STND, 3, NULL },
    [S_UFPHRST0_STND] = { SPR_UFPHRST0, 0, 1, -1, NULL, S_UFPHRST0_STND, 0, NULL },
    [S_UFPHRST0_RUN1] = { SPR_UFPHRST0, 0, 3, 6, NULL, S_UFPHRST0_RUN1, 2, NULL },
    [S_UFBAMST0_STND] = { SPR_UFBAMST0, 0, 1, -1, NULL, S_UFBAMST0_STND, 0, NULL },
    [S_UFBAMST0_RUN1] = { SPR_UFBAMST0, 0, 1, 6, NULL, S_UFBAMST0_RUN1, 2, NULL },
    [S_UIGRDST0_STND] = { SPR_UIGRDST0, 8, 1, 20, A_Look, S_UIGRDST0_STND, 0, NULL },
    [S_UIGRDST0_RUN1] = { SPR_UIGRDST0, 0, 1, 6, A_Chase, S_UIGRDST0_RUN2, 2, NULL },
    [S_UIGRDST0_RUN2] = { SPR_UIGRDST0, 1, 5, 6, NULL, S_UIGRDST0_RUN1, 2, NULL },
    [S_UIGRDST0_SHOOT1] = { SPR_UIGRDST0, 6, 1, 6, A_Attack, S_UIGRDST0_SHOOT2, 3, NULL },
    [S_UIGRDST0_SHOOT2] = { SPR_UIGRDST0, 7, 1, 6, NULL, S_UIGRDST0_STND, 3, NULL },
    [S_UIGRDST0_IDLE1] = { SPR_UIGRDST0, 8, 1, 10, NULL, S_UIGRDST0_IDLE1, 0, NULL },
    [S_UIBONST0_STND] = { SPR_UIBONST0, 25, 1, 20, A_Look, S_UIBONST0_STND, 0, NULL },
    [S_UIBONST0_RUN1] = { SPR_UIBONST0, 0, 1, 6, A_Chase, S_UIBONST0_RUN2, 2, NULL },
    [S_UIBONST0_RUN2] = { SPR_UIBONST0, 1, 7, 6, NULL, S_UIBONST0_RUN1, 2, NULL },
    [S_UIBONST0_SHOOT1] = { SPR_UIBONST0, 8, 1, 6, A_Attack, S_UIBONST0_SHOOT2, 3, NULL },
    [S_UIBONST0_SHOOT2] = { SPR_UIBONST0, 9, 2, 6, NULL, S_UIBONST0_STND, 3, NULL },
    [S_UIBONST0_IDLE1] = { SPR_UIBONST0, 11, 8, 10, NULL, S_UIBONST0_IDLE1, 0, NULL },
    [S_UIEXTST0_STND] = { SPR_UIEXTST0, 0, 1, 20, A_Look, S_UIEXTST0_STND, 0, NULL },
    [S_UIEXTST0_RUN1] = { SPR_UIEXTST0, 0, 1, 6, A_Chase, S_UIEXTST0_RUN1, 2, NULL },
    [S_UIEXTST0_SHOOT1] = { SPR_UIEXTST0, 1, 1, 6, A_Attack, S_UIEXTST0_SHOOT2, 3, NULL },
    [S_UIEXTST0_SHOOT2] = { SPR_UIEXTST0, 2, 1, 6, NULL, S_UIEXTST0_STND, 3, NULL },
    [S_UIEXTST0_IDLE1] = { SPR_UIEXTST0, 0, 1, 10, NULL, S_UIEXTST0_IDLE1, 0, NULL },
    [S_UISTTST0_STND] = { SPR_UISTTST0, 0, 1, 20, A_Look, S_UISTTST0_STND, 0, NULL },
    [S_UISTTST0_RUN1] = { SPR_UISTTST0, 0, 1, 6, A_Chase, S_UISTTST0_RUN1, 2, NULL },
    [S_UISTTST0_FIRE] = { SPR_UISTTST0, 0, 1, 1, A_Attack, S_UISTTST0_STND, 3, NULL },
    [S_UIITTST0_STND] = { SPR_UIITTST0, 0, 1, 20, A_Look, S_UIITTST0_STND, 0, NULL },
    [S_UIITTST0_RUN1] = { SPR_UIITTST0, 0, 1, 6, A_Chase, S_UIITTST0_RUN1, 2, NULL },
    [S_UIITTST0_FIRE] = { SPR_UIITTST0, 0, 1, 1, A_Attack, S_UIITTST0_STND, 3, NULL },
    [S_UIPLTST0_STND] = { SPR_UIPLTST0, 0, 1, 20, A_Look, S_UIPLTST0_STND, 0, NULL },
    [S_UIPLTST0_RUN1] = { SPR_UIPLTST0, 0, 1, 6, A_Chase, S_UIPLTST0_RUN1, 2, NULL },
    [S_UIPLTST0_FIRE] = { SPR_UIPLTST0, 0, 1, 1, A_Attack, S_UIPLTST0_STND, 3, NULL },
    [S_UIAMPST0_STND] = { SPR_UIAMPST0, 15, 1, -1, NULL, S_UIAMPST0_STND, 0, NULL },
    [S_UIAMPST0_RUN1] = { SPR_UIAMPST0, 0, 6, 6, NULL, S_UIAMPST0_RUN1, 2, NULL },
    [S_UIAMPST0_SHOOT1] = { SPR_UIAMPST0, 6, 3, 6, NULL, S_UIAMPST0_STND, 3, NULL },
    [S_UIAMPST0_IDLE1] = { SPR_UIAMPST0, 9, 3, 10, NULL, S_UIAMPST0_IDLE1, 0, NULL },
    [S_UIMADST0_STND] = { SPR_UIMADST0, 0, 1, 20, A_Look, S_UIMADST0_STND, 0, NULL },
    [S_UIMADST0_RUN1] = { SPR_UIMADST0, 0, 1, 6, A_Chase, S_UIMADST0_RUN1, 2, NULL },
    [S_UIMADST0_FIRE] = { SPR_UIMADST0, 0, 1, 1, A_Attack, S_UIMADST0_STND, 3, NULL },
    [S_UIRDRST0_STND] = { SPR_UIRDRST0, 0, 1, -1, NULL, S_UIRDRST0_STND, 0, NULL },
    [S_UIRDRST0_RUN1] = { SPR_UIRDRST0, 0, 1, 6, NULL, S_UIRDRST0_RUN1, 2, NULL },
    [S_UISHRST0_STND] = { SPR_UISHRST0, 0, 1, 20, A_Look, S_UISHRST0_STND, 0, NULL },
    [S_UISHRST0_RUN1] = { SPR_UISHRST0, 0, 1, 6, A_Chase, S_UISHRST0_RUN2, 2, NULL },
    [S_UISHRST0_RUN2] = { SPR_UISHRST0, 1, 3, 6, NULL, S_UISHRST0_RUN1, 2, NULL },
    [S_UISHRST0_FIRE] = { SPR_UISHRST0, 0, 1, 1, A_Attack, S_UISHRST0_STND, 3, NULL },
    [S_UIHOSST0_STND] = { SPR_UIHOSST0, 0, 1, -1, NULL, S_UIHOSST0_STND, 0, NULL },
    [S_UIHOSST0_RUN1] = { SPR_UIHOSST0, 0, 3, 6, NULL, S_UIHOSST0_RUN1, 2, NULL },
    [S_UITCTST0_STND] = { SPR_UITCTST0, 0, 1, 20, A_Look, S_UITCTST0_STND, 0, NULL },
    [S_UITCTST0_RUN1] = { SPR_UITCTST0, 0, 1, 6, A_Chase, S_UITCTST0_RUN1, 2, NULL },
    [S_UITCTST0_FIRE] = { SPR_UITCTST0, 0, 1, 1, A_Attack, S_UITCTST0_STND, 3, NULL },
    [S_UIIARST0_STND] = { SPR_UIIARST0, 0, 1, 20, A_Look, S_UIIARST0_STND, 0, NULL },
    [S_UIIARST0_RUN1] = { SPR_UIIARST0, 0, 1, 6, A_Chase, S_UIIARST0_RUN1, 2, NULL },
    [S_UIIARST0_SHOOT1] = { SPR_UIIARST0, 1, 1, 6, A_Attack, S_UIIARST0_SHOOT2, 3, NULL },
    [S_UIIARST0_SHOOT2] = { SPR_UIIARST0, 2, 2, 6, NULL, S_UIIARST0_STND, 3, NULL },
    [S_UICYCST0_STND] = { SPR_UICYCST0, 0, 1, 20, A_Look, S_UICYCST0_STND, 0, NULL },
    [S_UICYCST0_RUN1] = { SPR_UICYCST0, 0, 1, 6, A_Chase, S_UICYCST0_RUN1, 2, NULL },
    [S_UICYCST0_SHOOT1] = { SPR_UICYCST0, 1, 1, 6, A_Attack, S_UICYCST0_STND, 3, NULL },
    [S_UISKYST0_STND] = { SPR_UISKYST0, 0, 1, 20, A_Look, S_UISKYST0_STND, 0, NULL },
    [S_UISKYST0_RUN1] = { SPR_UISKYST0, 0, 1, 6, A_Chase, S_UISKYST0_RUN1, 2, NULL },
    [S_UISKYST0_SHOOT1] = { SPR_UISKYST0, 0, 1, 6, A_Attack, S_UISKYST0_SHOOT2, 3, NULL },
    [S_UISKYST0_SHOOT2] = { SPR_UISKYST0, 1, 2, 6, NULL, S_UISKYST0_STND, 3, NULL },
    [S_UCFNST0_IMP_STND] = { SPR_UCFNST0_IMP, 6, 1, -1, NULL, S_UCFNST0_IMP_STND, 0, NULL },
    [S_UCFNST0_IMP_RUN1] = { SPR_UCFNST0_IMP, 0, 6, 4, NULL, S_UCFNST0_IMP_RUN1, 2, NULL },
    [S_UCFRGST0_IMP_STND] = { SPR_UCFRGST0_IMP, 0, 1, -1, NULL, S_UCFRGST0_IMP_STND, 0, NULL },
    [S_UCFRGST0_IMP_RUN1] = { SPR_UCFRGST0_IMP, 0, 3, 6, NULL, S_UCFRGST0_IMP_RUN1, 2, NULL },
    [S_UCFRGST0_IMP_HARVEST1] = { SPR_UCFRGST0_IMP, 3, 15, 0, NULL, S_UCFRGST0_IMP_STND, 5, TICS(4,3,4,3,3,4,3,3,4,3,4,3,3,4,3) },
    [S_UCHFRST0_IMP_STND] = { SPR_UCHFRST0_IMP, 0, 1, 20, A_Look, S_UCHFRST0_IMP_STND, 0, NULL },
    [S_UCHFRST0_IMP_RUN1] = { SPR_UCHFRST0_IMP, 0, 1, 6, A_Chase, S_UCHFRST0_IMP_RUN1, 2, NULL },
    [S_UCHFRST0_IMP_HARVEST1] = { SPR_UCHFRST0_IMP, 1, 15, 0, NULL, S_UCHFRST0_IMP_STND, 5, TICS(4,3,4,3,3,4,3,3,4,3,4,3,3,4,3) },
    [S_UCHFRST0_IMP_FIRE] = { SPR_UCHFRST0_IMP, 0, 1, 1, A_Attack, S_UCHFRST0_IMP_STND, 3, NULL },
    [S_UCINFST0_IMP_STND] = { SPR_UCINFST0_IMP, 8, 1, -1, NULL, S_UCINFST0_IMP_STND, 0, NULL },
    [S_UCINFST0_IMP_RUN1] = { SPR_UCINFST0_IMP, 0, 8, 6, NULL, S_UCINFST0_IMP_RUN1, 2, NULL },
    [S_UCINFST0_IMP_IDLE1] = { SPR_UCINFST0_IMP, 8, 3, 10, NULL, S_UCINFST0_IMP_IDLE1, 0, NULL },
    [S_UFMTRST0_IMP_STND] = { SPR_UFMTRST0_IMP, 25, 1, 20, A_Look, S_UFMTRST0_IMP_STND, 0, NULL },
    [S_UFMTRST0_IMP_RUN1] = { SPR_UFMTRST0_IMP, 0, 1, 6, A_Chase, S_UFMTRST0_IMP_RUN2, 2, NULL },
    [S_UFMTRST0_IMP_RUN2] = { SPR_UFMTRST0_IMP, 1, 5, 6, NULL, S_UFMTRST0_IMP_RUN1, 2, NULL },
    [S_UFMTRST0_IMP_SHOOT1] = { SPR_UFMTRST0_IMP, 6, 1, 6, A_Attack, S_UFMTRST0_IMP_SHOOT2, 3, NULL },
    [S_UFMTRST0_IMP_SHOOT2] = { SPR_UFMTRST0_IMP, 7, 15, 6, NULL, S_UFMTRST0_IMP_STND, 3, NULL },
    [S_UFMTRST0_IMP_IDLE1] = { SPR_UFMTRST0_IMP, 22, 4, 10, NULL, S_UFMTRST0_IMP_IDLE1, 0, NULL },
    [S_UCWCOST0_IMP_STND] = { SPR_UCWCOST0_IMP, 0, 1, 20, A_Look, S_UCWCOST0_IMP_STND, 0, NULL },
    [S_UCWCOST0_IMP_RUN1] = { SPR_UCWCOST0_IMP, 0, 1, 6, A_Chase, S_UCWCOST0_IMP_RUN2, 2, NULL },
    [S_UCWCOST0_IMP_RUN2] = { SPR_UCWCOST0_IMP, 1, 3, 6, NULL, S_UCWCOST0_IMP_RUN1, 2, NULL },
    [S_UCWCOST0_IMP_FIRE] = { SPR_UCWCOST0_IMP, 0, 1, 1, A_Attack, S_UCWCOST0_IMP_STND, 3, NULL },
    [S_UIITTST0_D_STND] = { SPR_UIITTST0_D, 0, 1, -1, NULL, S_UIITTST0_D_STND, 0, NULL },
    [S_UIITTST0_D_RUN1] = { SPR_UIITTST0_D, 0, 1, 6, NULL, S_UIITTST0_D_RUN1, 2, NULL },
    [S_UIPLTST0_D_STND] = { SPR_UIPLTST0_D, 0, 1, -1, NULL, S_UIPLTST0_D_STND, 0, NULL },
    [S_UIPLTST0_D_RUN1] = { SPR_UIPLTST0_D, 0, 1, 6, NULL, S_UIPLTST0_D_RUN1, 2, NULL },
    [S_UITCTST0_D_STND] = { SPR_UITCTST0_D, 0, 1, -1, NULL, S_UITCTST0_D_STND, 0, NULL },
    [S_UITCTST0_D_RUN1] = { SPR_UITCTST0_D, 0, 1, 6, NULL, S_UITCTST0_D_RUN1, 2, NULL },
    [S_UIMADST0_D_STND] = { SPR_UIMADST0_D, 0, 1, -1, NULL, S_UIMADST0_D_STND, 0, NULL },
    [S_UIMADST0_D_RUN1] = { SPR_UIMADST0_D, 0, 1, 6, NULL, S_UIMADST0_D_RUN1, 2, NULL },
    [S_UISHRST0_D_STND] = { SPR_UISHRST0_D, 0, 1, 20, A_Look, S_UISHRST0_D_STND, 0, NULL },
    [S_UISHRST0_D_RUN1] = { SPR_UISHRST0_D, 0, 1, 6, A_Chase, S_UISHRST0_D_RUN2, 2, NULL },
    [S_UISHRST0_D_RUN2] = { SPR_UISHRST0_D, 1, 3, 6, NULL, S_UISHRST0_D_RUN1, 2, NULL },
    [S_UISHRST0_D_FIRE] = { SPR_UISHRST0_D, 0, 1, 1, A_Attack, S_UISHRST0_D_STND, 3, NULL },
    [S_UIIARST0_D_STND] = { SPR_UIIARST0_D, 0, 1, -1, NULL, S_UIIARST0_D_STND, 0, NULL },
    [S_UIIARST0_D_RUN1] = { SPR_UIIARST0_D, 0, 1, 6, NULL, S_UIIARST0_D_RUN1, 2, NULL },
    [S_UOCVMST0_STND] = { SPR_UOCVMST0, 22, 1, -1, NULL, S_UOCVMST0_STND, 0, NULL },
    [S_UOCVMST0_RUN1] = { SPR_UOCVMST0, 0, 6, 2, NULL, S_UOCVMST0_RUN1, 2, NULL },
    [S_UORCMST0_STND] = { SPR_UORCMST0, 23, 1, 20, A_Look, S_UORCMST0_STND, 0, NULL },
    [S_UORCMST0_RUN1] = { SPR_UORCMST0, 0, 1, 2, A_Chase, S_UORCMST0_RUN2, 2, NULL },
    [S_UORCMST0_RUN2] = { SPR_UORCMST0, 1, 7, 2, NULL, S_UORCMST0_RUN1, 2, NULL },
    [S_UORCMST0_SHOOT1] = { SPR_UORCMST0, 8, 1, 4, A_Attack, S_UORCMST0_SHOOT2, 3, NULL },
    [S_UORCMST0_SHOOT2] = { SPR_UORCMST0, 9, 2, 4, NULL, S_UORCMST0_STND, 3, NULL },
    [S_UOCSPST0_STND] = { SPR_UOCSPST0, 0, 1, -1, NULL, S_UOCSPST0_STND, 0, NULL },
    [S_UOCSPST0_RUN1] = { SPR_UOCSPST0, 0, 4, 2, NULL, S_UOCSPST0_RUN1, 2, NULL },
    [S_UOCVMST0_CPR_STND] = { SPR_UOCVMST0_CPR, 22, 1, -1, NULL, S_UOCVMST0_CPR_STND, 0, NULL },
    [S_UOCVMST0_CPR_RUN1] = { SPR_UOCVMST0_CPR, 0, 6, 2, NULL, S_UOCVMST0_CPR_RUN1, 2, NULL },
    [S_UORCMST0_CJR_STND] = { SPR_UORCMST0_CJR, 23, 1, 20, A_Look, S_UORCMST0_CJR_STND, 0, NULL },
    [S_UORCMST0_CJR_RUN1] = { SPR_UORCMST0_CJR, 0, 1, 2, A_Chase, S_UORCMST0_CJR_RUN2, 2, NULL },
    [S_UORCMST0_CJR_RUN2] = { SPR_UORCMST0_CJR, 1, 7, 2, NULL, S_UORCMST0_CJR_RUN1, 2, NULL },
    [S_UORCMST0_CJR_SHOOT1] = { SPR_UORCMST0_CJR, 8, 1, 4, A_Attack, S_UORCMST0_CJR_SHOOT2, 3, NULL },
    [S_UORCMST0_CJR_SHOOT2] = { SPR_UORCMST0_CJR, 9, 2, 4, NULL, S_UORCMST0_CJR_STND, 3, NULL },
    [S_UOCSPST0_CK_STND] = { SPR_UOCSPST0_CK, 0, 1, 20, A_Look, S_UOCSPST0_CK_STND, 0, NULL },
    [S_UOCSPST0_CK_RUN1] = { SPR_UOCSPST0_CK, 0, 1, 2, A_Chase, S_UOCSPST0_CK_RUN2, 2, NULL },
    [S_UOCSPST0_CK_RUN2] = { SPR_UOCSPST0_CK, 1, 3, 2, NULL, S_UOCSPST0_CK_RUN1, 2, NULL },
    [S_UOCSPST0_CK_FIRE] = { SPR_UOCSPST0_CK, 0, 1, 1, A_Attack, S_UOCSPST0_CK_STND, 3, NULL },
    [S_UOCVMST0_CCM_STND] = { SPR_UOCVMST0_CCM, 22, 1, -1, NULL, S_UOCVMST0_CCM_STND, 0, NULL },
    [S_UOCVMST0_CCM_RUN1] = { SPR_UOCVMST0_CCM, 0, 6, 2, NULL, S_UOCVMST0_CCM_RUN1, 2, NULL },
    [S_UOWTRST0_STND] = { SPR_UOWTRST0, 0, 1, -1, NULL, S_UOWTRST0_STND, 0, NULL },
    [S_UOWTRST0_RUN1] = { SPR_UOWTRST0, 0, 3, 2, NULL, S_UOWTRST0_RUN1, 2, NULL },
    [S_UOHTRST0_STND] = { SPR_UOHTRST0, 0, 1, -1, NULL, S_UOHTRST0_STND, 0, NULL },
    [S_UOHTRST0_RUN1] = { SPR_UOHTRST0, 0, 1, 2, NULL, S_UOHTRST0_RUN1, 2, NULL },
    [S_NFHQT1L0_STND] = { SPR_NFHQT1L0, 0, 1, -1, NULL, S_NFHQT1L0_STND, 0, NULL },
    [S_NFHQT2L0_STND] = { SPR_NFHQT2L0, 0, 1, -1, NULL, S_NFHQT2L0_STND, 0, NULL },
    [S_NFHQT3L0_STND] = { SPR_NFHQT3L0, 0, 1, -1, NULL, S_NFHQT3L0_STND, 0, NULL },
    [S_NFUTF1L0_STND] = { SPR_NFUTF1L0, 0, 1, -1, NULL, S_NFUTF1L0_STND, 0, NULL },
    [S_NFUTF2L0_STND] = { SPR_NFUTF2L0, 0, 1, -1, NULL, S_NFUTF2L0_STND, 0, NULL },
    [S_NFVCY1L0_STND] = { SPR_NFVCY1L0, 0, 1, -1, NULL, S_NFVCY1L0_STND, 0, NULL },
    [S_NFVCY2L0_STND] = { SPR_NFVCY2L0, 0, 1, -1, NULL, S_NFVCY2L0_STND, 0, NULL },
    [S_NFHSP1L0_STND] = { SPR_NFHSP1L0, 0, 1, -1, NULL, S_NFHSP1L0_STND, 0, NULL },
    [S_NFREP1L0_STND] = { SPR_NFREP1L0, 0, 1, -1, NULL, S_NFREP1L0_STND, 0, NULL },
    [S_NFPHF1L0_STND] = { SPR_NFPHF1L0, 0, 1, -1, NULL, S_NFPHF1L0_STND, 0, NULL },
    [S_NFPHF2L0_STND] = { SPR_NFPHF2L0, 0, 1, -1, NULL, S_NFPHF2L0_STND, 0, NULL },
    [S_NCCAM1L0_STND] = { SPR_NCCAM1L0, 0, 1, -1, NULL, S_NCCAM1L0_STND, 0, NULL },
    [S_NCLNC1L0_STND] = { SPR_NCLNC1L0, 0, 1, -1, NULL, S_NCLNC1L0_STND, 0, NULL },
    [S_NCPOW1L0_STND] = { SPR_NCPOW1L0, 0, 1, -1, NULL, S_NCPOW1L0_STND, 0, NULL },
    [S_NFRRM1L0_STND] = { SPR_NFRRM1L0, 0, 1, -1, NULL, S_NFRRM1L0_STND, 0, NULL },
    [S_NCSBH1L0_STND] = { SPR_NCSBH1L0, 0, 1, -1, NULL, S_NCSBH1L0_STND, 0, NULL },
    [S_NCSBV1L0_STND] = { SPR_NCSBV1L0, 0, 1, -1, NULL, S_NCSBV1L0_STND, 0, NULL },
    [S_NCSBC1L0_STND] = { SPR_NCSBC1L0, 0, 1, -1, NULL, S_NCSBC1L0_STND, 0, NULL },
    [S_NFGDT1L0_STND] = { SPR_NFGDT1L0, 0, 1, 20, A_Look, S_NFGDT1L0_STND, 0, NULL },
    [S_NFGDT1L0_FIRE] = { SPR_NFGDT1L0, 0, 1, 1, A_Attack, S_NFGDT1L0_STND, 3, NULL },
    [S_NFAGT1L0_STND] = { SPR_NFAGT1L0, 0, 1, 20, A_Look, S_NFAGT1L0_STND, 0, NULL },
    [S_NFAGT1L0_FIRE] = { SPR_NFAGT1L0, 0, 1, 1, A_Attack, S_NFAGT1L0_STND, 3, NULL },
    [S_NFAAR1L0_STND] = { SPR_NFAAR1L0, 0, 1, 20, A_Look, S_NFAAR1L0_STND, 0, NULL },
    [S_NFAAR1L0_FIRE] = { SPR_NFAAR1L0, 0, 1, 1, A_Attack, S_NFAAR1L0_STND, 3, NULL },
    [S_NIHQT1L0_STND] = { SPR_NIHQT1L0, 0, 1, -1, NULL, S_NIHQT1L0_STND, 0, NULL },
    [S_NIHQT2L0_STND] = { SPR_NIHQT2L0, 0, 1, -1, NULL, S_NIHQT2L0_STND, 0, NULL },
    [S_NIHQT3L0_STND] = { SPR_NIHQT3L0, 0, 1, -1, NULL, S_NIHQT3L0_STND, 0, NULL },
    [S_NIUTF1L0_STND] = { SPR_NIUTF1L0, 0, 1, -1, NULL, S_NIUTF1L0_STND, 0, NULL },
    [S_NIUTF2L0_STND] = { SPR_NIUTF2L0, 0, 1, -1, NULL, S_NIUTF2L0_STND, 0, NULL },
    [S_NIVCY1L0_STND] = { SPR_NIVCY1L0, 0, 1, -1, NULL, S_NIVCY1L0_STND, 0, NULL },
    [S_NIVCY2L0_STND] = { SPR_NIVCY2L0, 0, 1, -1, NULL, S_NIVCY2L0_STND, 0, NULL },
    [S_NIHSP1L0_STND] = { SPR_NIHSP1L0, 0, 1, -1, NULL, S_NIHSP1L0_STND, 0, NULL },
    [S_NIREP1L0_STND] = { SPR_NIREP1L0, 0, 1, -1, NULL, S_NIREP1L0_STND, 0, NULL },
    [S_NITGT1L0_STND] = { SPR_NITGT1L0, 0, 1, -1, NULL, S_NITGT1L0_STND, 0, NULL },
    [S_NIRRM1L0_STND] = { SPR_NIRRM1L0, 0, 1, -1, NULL, S_NIRRM1L0_STND, 0, NULL },
    [S_NITRC1L0_STND] = { SPR_NITRC1L0, 0, 1, -1, NULL, S_NITRC1L0_STND, 0, NULL },
    [S_NIGDT1L0_STND] = { SPR_NIGDT1L0, 0, 1, 20, A_Look, S_NIGDT1L0_STND, 0, NULL },
    [S_NIGDT1L0_FIRE] = { SPR_NIGDT1L0, 0, 1, 1, A_Attack, S_NIGDT1L0_STND, 3, NULL },
    [S_NIAGT1L0_STND] = { SPR_NIAGT1L0, 0, 1, 20, A_Look, S_NIAGT1L0_STND, 0, NULL },
    [S_NIAGT1L0_FIRE] = { SPR_NIAGT1L0, 0, 1, 1, A_Attack, S_NIAGT1L0_STND, 3, NULL },
    [S_NIAAR1L0_STND] = { SPR_NIAAR1L0, 0, 1, 20, A_Look, S_NIAAR1L0_STND, 0, NULL },
    [S_NIAAR1L0_FIRE] = { SPR_NIAAR1L0, 0, 1, 1, A_Attack, S_NIAAR1L0_STND, 3, NULL },
    [S_NCCAM1L0_IMP_STND] = { SPR_NCCAM1L0_IMP, 0, 1, -1, NULL, S_NCCAM1L0_IMP_STND, 0, NULL },
    [S_NCLNC1L0_IMP_STND] = { SPR_NCLNC1L0_IMP, 0, 1, -1, NULL, S_NCLNC1L0_IMP_STND, 0, NULL },
    [S_NCPOW1L0_IMP_STND] = { SPR_NCPOW1L0_IMP, 0, 1, -1, NULL, S_NCPOW1L0_IMP_STND, 0, NULL },
    [S_NCSBH1L0_IMP_STND] = { SPR_NCSBH1L0_IMP, 0, 1, -1, NULL, S_NCSBH1L0_IMP_STND, 0, NULL },
    [S_NCSBV1L0_IMP_STND] = { SPR_NCSBV1L0_IMP, 0, 1, -1, NULL, S_NCSBV1L0_IMP_STND, 0, NULL },
    [S_NCSBC1L0_IMP_STND] = { SPR_NCSBC1L0_IMP, 0, 1, -1, NULL, S_NCSBC1L0_IMP_STND, 0, NULL },
    [S_NCSWL1L0_STND] = { SPR_NCSWL1L0, 0, 1, -1, NULL, S_NCSWL1L0_STND, 0, NULL },
    [S_NCSWM1L0_STND] = { SPR_NCSWM1L0, 0, 1, -1, NULL, S_NCSWM1L0_STND, 0, NULL },
    [S_NCBWL1L0_STND] = { SPR_NCBWL1L0, 0, 1, -1, NULL, S_NCBWL1L0_STND, 0, NULL },
    [S_NCBWM1L0_STND] = { SPR_NCBWM1L0, 0, 1, -1, NULL, S_NCBWM1L0_STND, 0, NULL },
    [S_NFVCY1L0_D_STND] = { SPR_NFVCY1L0_D, 0, 1, -1, NULL, S_NFVCY1L0_D_STND, 0, NULL },
    [S_NFVCY2L0_D_STND] = { SPR_NFVCY2L0_D, 0, 1, -1, NULL, S_NFVCY2L0_D_STND, 0, NULL },
    [S_NFPHF1L0_D_STND] = { SPR_NFPHF1L0_D, 0, 1, -1, NULL, S_NFPHF1L0_D_STND, 0, NULL },
    [S_NFPHF2L0_D_STND] = { SPR_NFPHF2L0_D, 0, 1, -1, NULL, S_NFPHF2L0_D_STND, 0, NULL },
    [S_NFHQT1L0_D_STND] = { SPR_NFHQT1L0_D, 0, 1, -1, NULL, S_NFHQT1L0_D_STND, 0, NULL },
    [S_NFHQT2L0_D_STND] = { SPR_NFHQT2L0_D, 0, 1, -1, NULL, S_NFHQT2L0_D_STND, 0, NULL },
    [S_NFHQT3L0_D_STND] = { SPR_NFHQT3L0_D, 0, 1, -1, NULL, S_NFHQT3L0_D_STND, 0, NULL },
    [S_NFUTF2L0_D_STND] = { SPR_NFUTF2L0_D, 0, 1, -1, NULL, S_NFUTF2L0_D_STND, 0, NULL },
    [S_NFHSP1L0_D_STND] = { SPR_NFHSP1L0_D, 0, 1, -1, NULL, S_NFHSP1L0_D_STND, 0, NULL },
    [S_NFREP1L0_D_STND] = { SPR_NFREP1L0_D, 0, 1, -1, NULL, S_NFREP1L0_D_STND, 0, NULL },
    [S_NFRRM1L0_D_STND] = { SPR_NFRRM1L0_D, 0, 1, -1, NULL, S_NFRRM1L0_D_STND, 0, NULL },
    [S_NCPOW1L0_D_STND] = { SPR_NCPOW1L0_D, 0, 1, -1, NULL, S_NCPOW1L0_D_STND, 0, NULL },
    [S_NFUTF1L0_D_STND] = { SPR_NFUTF1L0_D, 0, 1, -1, NULL, S_NFUTF1L0_D_STND, 0, NULL },
    [S_NOCEN1L0_STND] = { SPR_NOCEN1L0, 0, 1, -1, NULL, S_NOCEN1L0_STND, 0, NULL },
    [S_NCWEL1L0_STND] = { SPR_NCWEL1L0, 0, 1, -1, NULL, S_NCWEL1L0_STND, 0, NULL },
    [S_NCMIN1L0_STND] = { SPR_NCMIN1L0, 0, 1, -1, NULL, S_NCMIN1L0_STND, 0, NULL },
    [S_NOWAT1L0_STND] = { SPR_NOWAT1L0, 0, 1, -1, NULL, S_NOWAT1L0_STND, 0, NULL },
    [S_NOHOV1L0_STND] = { SPR_NOHOV1L0, 0, 1, -1, NULL, S_NOHOV1L0_STND, 0, NULL },
    [S_NODES1L0_STND] = { SPR_NODES1L0, 0, 1, -1, NULL, S_NODES1L0_STND, 0, NULL },
    [S_NOMDR1L0_STND] = { SPR_NOMDR1L0, 0, 1, -1, NULL, S_NOMDR1L0_STND, 0, NULL },
    [S_NOSHL1L0_STND] = { SPR_NOSHL1L0, 0, 1, -1, NULL, S_NOSHL1L0_STND, 0, NULL },
    [S_NOSUB1L0_STND] = { SPR_NOSUB1L0, 0, 1, -1, NULL, S_NOSUB1L0_STND, 0, NULL },
    [S_NOTCN1L0_STND] = { SPR_NOTCN1L0, 0, 1, -1, NULL, S_NOTCN1L0_STND, 0, NULL },
    [S_NOTYH1L0_STND] = { SPR_NOTYH1L0, 0, 1, -1, NULL, S_NOTYH1L0_STND, 0, NULL },
    [S_NOTHQ1L0_STND] = { SPR_NOTHQ1L0, 0, 1, -1, NULL, S_NOTHQ1L0_STND, 0, NULL },
    [S_NOMLT1L0_STND] = { SPR_NOMLT1L0, 0, 1, -1, NULL, S_NOMLT1L0_STND, 0, NULL },
    [S_NOTDR1L0_STND] = { SPR_NOTDR1L0, 0, 1, -1, NULL, S_NOTDR1L0_STND, 0, NULL },
    [S_NORVP1L0_STND] = { SPR_NORVP1L0, 0, 1, -1, NULL, S_NORVP1L0_STND, 0, NULL },
    [S_NOPLD1L0_STND] = { SPR_NOPLD1L0, 0, 1, -1, NULL, S_NOPLD1L0_STND, 0, NULL },
    [S_NOCBS1L0_STND] = { SPR_NOCBS1L0, 0, 1, -1, NULL, S_NOCBS1L0_STND, 0, NULL },
    [S_NOWAR1L0_STND] = { SPR_NOWAR1L0, 0, 1, -1, NULL, S_NOWAR1L0_STND, 0, NULL },
    [S_NOPRI1L0_STND] = { SPR_NOPRI1L0, 0, 1, -1, NULL, S_NOPRI1L0_STND, 0, NULL },
    [S_NOCHM4L0_STND] = { SPR_NOCHM4L0, 0, 1, -1, NULL, S_NOCHM4L0_STND, 0, NULL },
    [S_NOFRM1L0_STND] = { SPR_NOFRM1L0, 0, 1, -1, NULL, S_NOFRM1L0_STND, 0, NULL },
    [S_NOFRM1L1_STND] = { SPR_NOFRM1L1, 0, 1, -1, NULL, S_NOFRM1L1_STND, 0, NULL },
    [S_NOFRM1L2_STND] = { SPR_NOFRM1L2, 0, 1, -1, NULL, S_NOFRM1L2_STND, 0, NULL },
    [S_NOBRD1L0_STND] = { SPR_NOBRD1L0, 0, 1, -1, NULL, S_NOBRD1L0_STND, 0, NULL },
    [S_NOBRD1L1_STND] = { SPR_NOBRD1L1, 0, 1, -1, NULL, S_NOBRD1L1_STND, 0, NULL },
    [S_NCSBH1L0_T_STND] = { SPR_NCSBH1L0_T, 0, 1, -1, NULL, S_NCSBH1L0_T_STND, 0, NULL },
    [S_NCSBV1L0_T_STND] = { SPR_NCSBV1L0_T, 0, 1, -1, NULL, S_NCSBV1L0_T_STND, 0, NULL },
    [S_NCSBC1L0_T_STND] = { SPR_NCSBC1L0_T, 0, 1, -1, NULL, S_NCSBC1L0_T_STND, 0, NULL },
};

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {
    { 0 },
    { // MT_FG_CONSTRUCTION_CREW
        .doomednum = ACTOR_FG_CONSTRUCTION_CREW, .spawnstate = S_UCFCNST0_STND, .spawnhealth = 100,
        .seestate = S_UCFCNST0_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_FREIGHTER
        .doomednum = ACTOR_FG_GROUND_TRANSPORTER, .spawnstate = S_UCFRGST0_STND, .spawnhealth = 750,
        .seestate = S_UCFRGST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_FG_HOVER_FREIGHTER
        .doomednum = ACTOR_FG_HOVER_TRANSPORTER, .spawnstate = S_UCHFRST0_STND, .spawnhealth = 500,
        .seestate = S_UCHFRST0_RUN1, .speed = 5,
        .missilestate = S_UCHFRST0_FIRE, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER|MF_ATTACK,
    },
    { // MT_FG_RAIDER
        .doomednum = ACTOR_FG_RAIDER, .spawnstate = S_UFRADST0_STND, .spawnhealth = 100,
        .seestate = S_UFRADST0_RUN1, .speed = 5,
        .missilestate = S_UFRADST0_SHOOT1, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_FG_MERCENARY
        .doomednum = ACTOR_FG_MERCENARY, .spawnstate = S_UFMRCST0_STND, .spawnhealth = 125,
        .seestate = S_UFMRCST0_RUN1, .speed = 5,
        .missilestate = S_UFMRCST0_SHOOT1, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_FG_SNIPER
        .doomednum = ACTOR_FG_SNIPER, .spawnstate = S_UFSNPST0_STND, .spawnhealth = 100,
        .seestate = S_UFSNPST0_RUN1, .speed = 5,
        .missilestate = S_UFSNPST0_SHOOT1, .damage = 150,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN|MF_NOAUTOTARGET,
    },
    { // MT_FG_SCOUT
        .doomednum = ACTOR_FG_SCOUT, .spawnstate = S_UFSCTST0_STND, .spawnhealth = 66,
        .seestate = S_UFSCTST0_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN,
    },
    { // MT_FG_MEDIC
        .doomednum = ACTOR_FG_MEDIC, .spawnstate = S_UFMEDST0_STND, .spawnhealth = 66,
        .seestate = S_UFMEDST0_RUN1, .speed = 5,
        .missilestate = S_UFMEDST0_SHOOT1, .damage = -20,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HEAL|MF_HUMAN,
    },
    { // MT_FG_SABOTEUR
        .doomednum = ACTOR_FG_SABOTEUR, .spawnstate = S_UFSABST0_STND, .spawnhealth = 100,
        .seestate = S_UFSABST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN,
    },
    { // MT_FG_MECHANIC
        .doomednum = ACTOR_FG_MECHANIC, .spawnstate = S_UFMECST0_STND, .spawnhealth = 66,
        .seestate = S_UFMECST0_RUN1, .speed = 5,
        .missilestate = S_UFMECST0_SHOOT1, .damage = -5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_REPAIR|MF_HUMAN,
    },
    { // MT_FG_MARTYR
        .doomednum = ACTOR_FG_SUICIDE_NUKER, .spawnstate = S_UFMTRST0_STND, .spawnhealth = 100,
        .seestate = S_UFMTRST0_RUN1, .speed = 5,
        .missilestate = S_UFMTRST0_SHOOT1, .damage = 180,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_FG_SPY
        .doomednum = ACTOR_FG_SPY, .spawnstate = S_UCINFST0_STND, .spawnhealth = 66,
        .seestate = S_UCINFST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN|MF_NOAUTOTARGET,
    },
    { // MT_FG_SPYDER_BIKE
        .doomednum = ACTOR_FG_SPYDER_BIKE, .spawnstate = S_UFSPBST0_STND, .spawnhealth = 133,
        .seestate = S_UFSPBST0_RUN1, .speed = 7,
        .missilestate = S_UFSPBST0_SHOOT1, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_IFV
        .doomednum = ACTOR_FG_IFV, .spawnstate = S_UFRATST0_STND, .spawnhealth = 200,
        .seestate = S_UFRATST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MEDIUM_TANK
        .doomednum = ACTOR_FG_MEDIUM_TANK, .spawnstate = S_UFSKTST0_STND, .spawnhealth = 133,
        .seestate = S_UFSKTST0_RUN1, .speed = 4,
        .missilestate = S_UFSKTST0_FIRE, .damage = 14,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_TANK_HUNTER
        .doomednum = ACTOR_FG_TANK_HUNTER, .spawnstate = S_UFTHNST0_STND, .spawnhealth = 150,
        .seestate = S_UFTHNST0_RUN1, .speed = 4,
        .missilestate = S_UFTHNST0_SHOOT1, .damage = 60,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_PHASE_TANK
        .doomednum = ACTOR_FG_PHASE_TANK, .spawnstate = S_UFPHTST0_STND, .spawnhealth = 166,
        .seestate = S_UFPHTST0_RUN1, .speed = 4,
        .missilestate = S_UFPHTST0_SHOOT1, .damage = 30,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_MAD
        .doomednum = ACTOR_FG_MAD, .spawnstate = S_UFFLKST0_STND, .spawnhealth = 100,
        .seestate = S_UFFLKST0_RUN1, .speed = 4,
        .missilestate = S_UFFLKST0_SHOOT1, .damage = 8,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_TRIPLE_RAIL_TANK
        .doomednum = ACTOR_FG_TRIPLE_RAIL_TANK, .spawnstate = S_UFTRTST0_STND, .spawnhealth = 200,
        .seestate = S_UFTRTST0_RUN1, .speed = 4,
        .missilestate = S_UFTRTST0_FIRE, .damage = 24,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SPA
        .doomednum = ACTOR_FG_SPA, .spawnstate = S_UFFARST0_STND, .spawnhealth = 133,
        .seestate = S_UFFARST0_RUN1, .speed = 4,
        .missilestate = S_UFFARST0_SHOOT1, .damage = 30,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SKY_BIKE
        .doomednum = ACTOR_FG_SKY_BIKE, .spawnstate = S_UFSKBST0_STND, .spawnhealth = 100,
        .seestate = S_UFSKBST0_RUN1, .speed = 6,
        .missilestate = S_UFSKBST0_FIRE, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY|MF_NOAUTOTARGET,
    },
    { // MT_FG_OUTRIDER
        .doomednum = ACTOR_FG_OUTRIDER, .spawnstate = S_UFOUTST0_STND, .spawnhealth = 200,
        .seestate = S_UFOUTST0_RUN1, .speed = 5,
        .missilestate = S_UFOUTST0_FIRE, .damage = 20,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY|MF_NOAUTOTARGET,
    },
    { // MT_FG_SHOCKWAVE
        .doomednum = ACTOR_FG_SHOCKWAVE, .spawnstate = S_UFSWVST0_STND, .spawnhealth = 166,
        .seestate = S_UFSWVST0_RUN1, .speed = 4,
        .missilestate = S_UFSWVST0_FIRE, .damage = 17,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_NOAUTOTARGET,
    },
    { // MT_FG_CONTAMINATOR
        .doomednum = ACTOR_FG_CONTAMINATOR, .spawnstate = S_UCWCOST0_STND, .spawnhealth = 166,
        .seestate = S_UCWCOST0_RUN1, .speed = 3,
        .missilestate = S_UCWCOST0_FIRE, .damage = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_NOAUTOTARGET,
    },
    { // MT_FG_UNDERGROUND_TUNNEL
        .doomednum = ACTOR_FG_UNDERGROUND_TUNNEL, .spawnstate = S_UFPHRST0_STND, .spawnhealth = 150,
        .seestate = S_UFPHRST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_BASE_MOVER
        .doomednum = ACTOR_FG_BASE_MOVER, .spawnstate = S_UFBAMST0_STND, .spawnhealth = 500,
        .seestate = S_UFBAMST0_RUN1, .speed = 3,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_GUARDIAN
        .doomednum = ACTOR_IMP_STRIKE_MARINE, .spawnstate = S_UIGRDST0_STND, .spawnhealth = 100,
        .seestate = S_UIGRDST0_RUN1, .speed = 5,
        .missilestate = S_UIGRDST0_SHOOT1, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_IMP_BION
        .doomednum = ACTOR_IMP_FIRE_SUPPORT_MARINE, .spawnstate = S_UIBONST0_STND, .spawnhealth = 150,
        .seestate = S_UIBONST0_RUN1, .speed = 5,
        .missilestate = S_UIBONST0_SHOOT1, .damage = 18,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_IMP_EXTERMINATOR
        .doomednum = ACTOR_IMP_HOVER_MARINE, .spawnstate = S_UIEXTST0_STND, .spawnhealth = 75,
        .seestate = S_UIEXTST0_RUN1, .speed = 5,
        .missilestate = S_UIEXTST0_SHOOT1, .damage = 15,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_IMP_SCOUT_TANK
        .doomednum = ACTOR_IMP_SCOUT_TANK, .spawnstate = S_UISTTST0_STND, .spawnhealth = 150,
        .seestate = S_UISTTST0_RUN1, .speed = 6,
        .missilestate = S_UISTTST0_FIRE, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_ASSAULT_VEHICLE
        .doomednum = ACTOR_IMP_ASSAULT_VEHICLE, .spawnstate = S_UIITTST0_STND, .spawnhealth = 150,
        .seestate = S_UIITTST0_RUN1, .speed = 5,
        .missilestate = S_UIITTST0_FIRE, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_PLASMA_TANK
        .doomednum = ACTOR_IMP_PLASMA_TANK, .spawnstate = S_UIPLTST0_STND, .spawnhealth = 250,
        .seestate = S_UIPLTST0_RUN1, .speed = 4,
        .missilestate = S_UIPLTST0_FIRE, .damage = 19,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_AMPER
        .doomednum = ACTOR_IMP_AMPER, .spawnstate = S_UIAMPST0_STND, .spawnhealth = 66,
        .seestate = S_UIAMPST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_MAD
        .doomednum = ACTOR_IMP_MAD, .spawnstate = S_UIMADST0_STND, .spawnhealth = 150,
        .seestate = S_UIMADST0_RUN1, .speed = 4,
        .missilestate = S_UIMADST0_FIRE, .damage = 48,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_RECON_SAUCER
        .doomednum = ACTOR_IMP_RECON_SAUCER, .spawnstate = S_UIRDRST0_STND, .spawnhealth = 66,
        .seestate = S_UIRDRST0_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_FLY,
    },
    { // MT_IMP_SHREDDER
        .doomednum = ACTOR_IMP_SHREDDER, .spawnstate = S_UISHRST0_STND, .spawnhealth = 100,
        .seestate = S_UISHRST0_RUN1, .speed = 5,
        .missilestate = S_UISHRST0_FIRE, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_HOSTAGE_TAKER
        .doomednum = ACTOR_IMP_HOSTAGE_TAKER, .spawnstate = S_UIHOSST0_STND, .spawnhealth = 450,
        .seestate = S_UIHOSST0_RUN1, .speed = 4,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_TACHYON_TANK
        .doomednum = ACTOR_IMP_TACHYON_TANK, .spawnstate = S_UITCTST0_STND, .spawnhealth = 410,
        .seestate = S_UITCTST0_RUN1, .speed = 4,
        .missilestate = S_UITCTST0_FIRE, .damage = 30,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_SCARAB
        .doomednum = ACTOR_IMP_SPA, .spawnstate = S_UIIARST0_STND, .spawnhealth = 133,
        .seestate = S_UIIARST0_RUN1, .speed = 4,
        .missilestate = S_UIIARST0_SHOOT1, .damage = 30,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_CYCLONE
        .doomednum = ACTOR_IMP_VTOL, .spawnstate = S_UICYCST0_STND, .spawnhealth = 150,
        .seestate = S_UICYCST0_RUN1, .speed = 6,
        .missilestate = S_UICYCST0_SHOOT1, .damage = 24,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY|MF_NOAUTOTARGET,
    },
    { // MT_IMP_SKY_FORTRESS
        .doomednum = ACTOR_IMP_SKY_FORTRESS, .spawnstate = S_UISKYST0_STND, .spawnhealth = 266,
        .seestate = S_UISKYST0_RUN1, .speed = 4,
        .missilestate = S_UISKYST0_SHOOT1, .damage = 650,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY|MF_NOAUTOTARGET,
    },
    { // MT_IMP_CONSTRUCTION_CREW
        .doomednum = ACTOR_IMP_CONSTRUCTION_CREW, .spawnstate = S_UCFNST0_IMP_STND, .spawnhealth = 100,
        .seestate = S_UCFNST0_IMP_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_GROUND_TRANSPORTER
        .doomednum = ACTOR_IMP_GROUND_TRANSPORTER, .spawnstate = S_UCFRGST0_IMP_STND, .spawnhealth = 750,
        .seestate = S_UCFRGST0_IMP_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_IMP_HOVER_TRANSPORTER
        .doomednum = ACTOR_IMP_HOVER_TRANSPORTER, .spawnstate = S_UCHFRST0_IMP_STND, .spawnhealth = 500,
        .seestate = S_UCHFRST0_IMP_RUN1, .speed = 5,
        .missilestate = S_UCHFRST0_IMP_FIRE, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER|MF_ATTACK,
    },
    { // MT_IMP_SPY
        .doomednum = ACTOR_IMP_SPY, .spawnstate = S_UCINFST0_IMP_STND, .spawnhealth = 66,
        .seestate = S_UCINFST0_IMP_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN|MF_NOAUTOTARGET,
    },
    { // MT_IMP_SUICIDE_ZOMBIE
        .doomednum = ACTOR_IMP_SUICIDE_ZOMBIE, .spawnstate = S_UFMTRST0_IMP_STND, .spawnhealth = 100,
        .seestate = S_UFMTRST0_IMP_RUN1, .speed = 5,
        .missilestate = S_UFMTRST0_IMP_SHOOT1, .damage = 180,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_IMP_CONTAMINATOR
        .doomednum = ACTOR_IMP_CONTAMINATOR, .spawnstate = S_UCWCOST0_IMP_STND, .spawnhealth = 166,
        .seestate = S_UCWCOST0_IMP_RUN1, .speed = 3,
        .missilestate = S_UCWCOST0_IMP_FIRE, .damage = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_NOAUTOTARGET,
    },
    { // MT_IMP_ASSAULT_VEHICLE_DECOY
        .doomednum = ACTOR_IMP_ASSAULT_VEHICLE_DECOY, .spawnstate = S_UIITTST0_D_STND, .spawnhealth = 75,
        .seestate = S_UIITTST0_D_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_PLASMA_TANK_DECOY
        .doomednum = ACTOR_IMP_PLASMA_TANK_DECOY, .spawnstate = S_UIPLTST0_D_STND, .spawnhealth = 75,
        .seestate = S_UIPLTST0_D_RUN1, .speed = 4,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_TACHYON_TANK_DECOY
        .doomednum = ACTOR_IMP_TACHYON_TANK_DECOY, .spawnstate = S_UITCTST0_D_STND, .spawnhealth = 100,
        .seestate = S_UITCTST0_D_RUN1, .speed = 4,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_MAD_DECOY
        .doomednum = ACTOR_IMP_MAD_DECOY, .spawnstate = S_UIMADST0_D_STND, .spawnhealth = 100,
        .seestate = S_UIMADST0_D_RUN1, .speed = 4,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_IMP_SHREDDER_DECOY
        .doomednum = ACTOR_IMP_SHREDDER_DECOY, .spawnstate = S_UISHRST0_D_STND, .spawnhealth = 100,
        .seestate = S_UISHRST0_D_RUN1, .speed = 5,
        .missilestate = S_UISHRST0_D_FIRE, .damage = 50,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_SPA_DECOY
        .doomednum = ACTOR_IMP_SPA_DECOY, .spawnstate = S_UIIARST0_D_STND, .spawnhealth = 100,
        .seestate = S_UIIARST0_D_RUN1, .speed = 4,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_CIV_MALE
        .doomednum = ACTOR_CIV_MALE, .spawnstate = S_UOCVMST0_STND, .spawnhealth = 30,
        .seestate = S_UOCVMST0_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN,
    },
    { // MT_CIV_ROWDY
        .doomednum = ACTOR_CIV_ROWDY, .spawnstate = S_UORCMST0_STND, .spawnhealth = 66,
        .seestate = S_UORCMST0_RUN1, .speed = 5,
        .missilestate = S_UORCMST0_SHOOT1, .damage = 2,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_CIV_SPY
        .doomednum = ACTOR_CIV_SPY, .spawnstate = S_UOCSPST0_STND, .spawnhealth = 66,
        .seestate = S_UOCSPST0_RUN1, .speed = 8,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN,
    },
    { // MT_CIV_PRISONER
        .doomednum = ACTOR_CIV_PRISONER, .spawnstate = S_UOCVMST0_CPR_STND, .spawnhealth = 30,
        .seestate = S_UOCVMST0_CPR_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN,
    },
    { // MT_CIV_JEBRAD
        .doomednum = ACTOR_CIV_JEB_RAD, .spawnstate = S_UORCMST0_CJR_STND, .spawnhealth = 500,
        .seestate = S_UORCMST0_CJR_RUN1, .speed = 8,
        .missilestate = S_UORCMST0_CJR_SHOOT1, .damage = 170,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_HUMAN,
    },
    { // MT_CIV_KAROCH
        .doomednum = ACTOR_CIV_KAROCH, .spawnstate = S_UOCSPST0_CK_STND, .spawnhealth = 250,
        .seestate = S_UOCSPST0_CK_RUN1, .speed = 5,
        .missilestate = S_UOCSPST0_CK_FIRE, .damage = -20,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HEAL|MF_HUMAN,
    },
    { // MT_CIV_COLONEL
        .doomednum = ACTOR_CIV_COLONEL_MARTEL, .spawnstate = S_UOCVMST0_CCM_STND, .spawnhealth = 100,
        .seestate = S_UOCVMST0_CCM_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HUMAN,
    },
    { // MT_CIV_WHEEL
        .doomednum = ACTOR_CIV_WHEEL_TRANSPORTER, .spawnstate = S_UOWTRST0_STND, .spawnhealth = 150,
        .seestate = S_UOWTRST0_RUN1, .speed = 4,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_CIV_HOVER
        .doomednum = ACTOR_CIV_HOVER_TRANSPORTER, .spawnstate = S_UOHTRST0_STND, .spawnhealth = 100,
        .seestate = S_UOHTRST0_RUN1, .speed = 7,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_HQ1
        .doomednum = ACTOR_FG_HEADQUARTERS_1, .spawnstate = S_NFHQT1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_FG_HQ2
        .doomednum = ACTOR_FG_HEADQUARTERS_2, .spawnstate = S_NFHQT2L0_STND, .spawnhealth = 2400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HQ3
        .doomednum = ACTOR_FG_HEADQUARTERS_3, .spawnstate = S_NFHQT3L0_STND, .spawnhealth = 3600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BARRACKS
        .doomednum = ACTOR_FG_TRAINING_FACILITY_1, .spawnstate = S_NFUTF1L0_STND, .spawnhealth = 750,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_ADV_BARRACKS
        .doomednum = ACTOR_FG_TRAINING_FACILITY_2, .spawnstate = S_NFUTF2L0_STND, .spawnhealth = 1500,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_VEHICLE_FACTORY
        .doomednum = ACTOR_FG_VEHICLE_FACTORY_1, .spawnstate = S_NFVCY1L0_STND, .spawnhealth = 1000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_ADV_VEHICLE_FACTORY
        .doomednum = ACTOR_FG_VEHICLE_FACTORY_2, .spawnstate = S_NFVCY2L0_STND, .spawnhealth = 2000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HOVER_FACTORY
        .doomednum = ACTOR_FG_HOVER_FACTORY, .spawnstate = S_NFHSP1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REPAIR_BAY
        .doomednum = ACTOR_FG_REPAIR_BAY, .spawnstate = S_NFREP1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_1
        .doomednum = ACTOR_FG_PHASE_FACTORY_1, .spawnstate = S_NFPHF1L0_STND, .spawnhealth = 1000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_2
        .doomednum = ACTOR_FG_PHASE_FACTORY_2, .spawnstate = S_NFPHF2L0_STND, .spawnhealth = 2000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_CAMERA_TOWER
        .doomednum = ACTOR_FG_CAMERA_TOWER, .spawnstate = S_NCCAM1L0_STND, .spawnhealth = 150,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_LIFE_PLANT
        .doomednum = ACTOR_FG_LIFE_PLANT, .spawnstate = S_NCLNC1L0_STND, .spawnhealth = 1300,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_FG_POWER_PLANT
        .doomednum = ACTOR_FG_POWER_PLANT, .spawnstate = S_NCPOW1L0_STND, .spawnhealth = 1450,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REFINERY
        .doomednum = ACTOR_FG_REFINERY, .spawnstate = S_NFRRM1L0_STND, .spawnhealth = 800,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_H
        .doomednum = ACTOR_FG_SMALL_HORIZONTAL_BRIDGE, .spawnstate = S_NCSBH1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_V
        .doomednum = ACTOR_FG_SMALL_VERTICAL_BRIDGE, .spawnstate = S_NCSBV1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_C
        .doomednum = ACTOR_FG_SMALL_CENTRE_BRIDGE, .spawnstate = S_NCSBC1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_GUARD_TOWER
        .doomednum = ACTOR_FG_GUARD_TOWER, .spawnstate = S_NFGDT1L0_STND, .spawnhealth = 400,
        .missilestate = S_NFGDT1L0_FIRE, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_ADV_GUARD_TOWER
        .doomednum = ACTOR_FG_ADVANCED_GUARD_TOWER, .spawnstate = S_NFAGT1L0_STND, .spawnhealth = 550,
        .missilestate = S_NFAGT1L0_FIRE, .damage = 13,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_AA_SITE
        .doomednum = ACTOR_FG_AA_SITE, .spawnstate = S_NFAAR1L0_STND, .spawnhealth = 600,
        .missilestate = S_NFAAR1L0_FIRE, .damage = 40,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_HQ1
        .doomednum = ACTOR_IMP_HEADQUARTERS_1, .spawnstate = S_NIHQT1L0_STND, .spawnhealth = 1440,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_IMP_HQ2
        .doomednum = ACTOR_IMP_HEADQUARTERS_2, .spawnstate = S_NIHQT2L0_STND, .spawnhealth = 2880,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_HQ3
        .doomednum = ACTOR_IMP_HEADQUARTERS_3, .spawnstate = S_NIHQT3L0_STND, .spawnhealth = 4330,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_BARRACKS
        .doomednum = ACTOR_IMP_TRAINING_FACILITY_1, .spawnstate = S_NIUTF1L0_STND, .spawnhealth = 900,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_ADV_BARRACKS
        .doomednum = ACTOR_IMP_TRAINING_FACILITY_2, .spawnstate = S_NIUTF2L0_STND, .spawnhealth = 1800,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_VEHICLE_FACTORY
        .doomednum = ACTOR_IMP_VEHICLE_FACTORY_1, .spawnstate = S_NIVCY1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_ADV_VEHICLE_FACTORY
        .doomednum = ACTOR_IMP_VEHICLE_FACTORY_2, .spawnstate = S_NIVCY2L0_STND, .spawnhealth = 2400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_HOVER_FACTORY
        .doomednum = ACTOR_IMP_HOVER_FACTORY, .spawnstate = S_NIHSP1L0_STND, .spawnhealth = 720,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_REPAIR_BAY
        .doomednum = ACTOR_IMP_REPAIR_BAY, .spawnstate = S_NIREP1L0_STND, .spawnhealth = 720,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_TACHYON_PLANT
        .doomednum = ACTOR_IMP_TACHYON_PLANT, .spawnstate = S_NITGT1L0_STND, .spawnhealth = 1000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_REFINERY
        .doomednum = ACTOR_IMP_REFINERY, .spawnstate = S_NIRRM1L0_STND, .spawnhealth = 960,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_RIFT_CREATOR
        .doomednum = ACTOR_IMP_RIFT_CREATOR, .spawnstate = S_NITRC1L0_STND, .spawnhealth = 1000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_GUARD_TOWER
        .doomednum = ACTOR_IMP_GUARD_TOWER, .spawnstate = S_NIGDT1L0_STND, .spawnhealth = 400,
        .missilestate = S_NIGDT1L0_FIRE, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_ADV_GUARD_TOWER
        .doomednum = ACTOR_IMP_ADVANCED_GUARD_TOWER, .spawnstate = S_NIAGT1L0_STND, .spawnhealth = 550,
        .missilestate = S_NIAGT1L0_FIRE, .damage = 180,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_AA_SITE
        .doomednum = ACTOR_IMP_AA_SITE, .spawnstate = S_NIAAR1L0_STND, .spawnhealth = 720,
        .missilestate = S_NIAAR1L0_FIRE, .damage = 14,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_IMP_CAMERA_TOWER
        .doomednum = ACTOR_IMP_CAMERA_TOWER, .spawnstate = S_NCCAM1L0_IMP_STND, .spawnhealth = 150,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_LIFE_PLANT
        .doomednum = ACTOR_IMP_LIFE_PLANT, .spawnstate = S_NCLNC1L0_IMP_STND, .spawnhealth = 1300,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_IMP_POWER_PLANT
        .doomednum = ACTOR_IMP_POWER_PLANT, .spawnstate = S_NCPOW1L0_IMP_STND, .spawnhealth = 1450,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_BRIDGE_H
        .doomednum = ACTOR_IMP_SMALL_HORIZONTAL_BRIDGE, .spawnstate = S_NCSBH1L0_IMP_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_BRIDGE_V
        .doomednum = ACTOR_IMP_SMALL_VERTICAL_BRIDGE, .spawnstate = S_NCSBV1L0_IMP_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_BRIDGE_C
        .doomednum = ACTOR_IMP_SMALL_CENTRE_BRIDGE, .spawnstate = S_NCSBC1L0_IMP_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_WALL_1
        .doomednum = ACTOR_IMP_SMALL_WALL_1, .spawnstate = S_NCSWL1L0_STND, .spawnhealth = 100,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_WALL_2
        .doomednum = ACTOR_IMP_SMALL_WALL_2, .spawnstate = S_NCSWM1L0_STND, .spawnhealth = 100,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_LARGE_WALL_1
        .doomednum = ACTOR_IMP_LARGE_WALL_1, .spawnstate = S_NCBWL1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_LARGE_WALL_2
        .doomednum = ACTOR_IMP_LARGE_WALL_2, .spawnstate = S_NCBWM1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_VEHICLE_FACTORY_1_DECOY
        .doomednum = ACTOR_FG_VEHICLE_FACTORY_1_DECOY, .spawnstate = S_NFVCY1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_VEHICLE_FACTORY_2_DECOY
        .doomednum = ACTOR_FG_VEHICLE_FACTORY_2_DECOY, .spawnstate = S_NFVCY2L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_1_DECOY
        .doomednum = ACTOR_FG_PHASE_FACTORY_1_DECOY, .spawnstate = S_NFPHF1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_2_DECOY
        .doomednum = ACTOR_FG_PHASE_FACTORY_2_DECOY, .spawnstate = S_NFPHF2L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HQ1_DECOY
        .doomednum = ACTOR_FG_HEADQUARTERS_1_DECOY, .spawnstate = S_NFHQT1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HQ2_DECOY
        .doomednum = ACTOR_FG_HEADQUARTERS_2_DECOY, .spawnstate = S_NFHQT2L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HQ3_DECOY
        .doomednum = ACTOR_FG_HEADQUARTERS_3_DECOY, .spawnstate = S_NFHQT3L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_ADV_BARRACKS_DECOY
        .doomednum = ACTOR_FG_TRAINING_FACILITY_2_DECOY, .spawnstate = S_NFUTF2L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HOVER_FACTORY_DECOY
        .doomednum = ACTOR_FG_HOVER_FACTORY_DECOY, .spawnstate = S_NFHSP1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REPAIR_BAY_DECOY
        .doomednum = ACTOR_FG_REPAIR_BAY_DECOY, .spawnstate = S_NFREP1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REFINERY_DECOY
        .doomednum = ACTOR_FG_REFINERY_DECOY, .spawnstate = S_NFRRM1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_POWER_PLANT_DECOY
        .doomednum = ACTOR_FG_POWER_PLANT_DECOY, .spawnstate = S_NCPOW1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BARRACKS_DECOY
        .doomednum = ACTOR_FG_TRAINING_FACILITY_1_DECOY, .spawnstate = S_NFUTF1L0_D_STND, .spawnhealth = 200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_ENTERTAINMENT
        .doomednum = ACTOR_CIV_ENTERTAINMENT, .spawnstate = S_NOCEN1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_WATER_EXTRACTOR
        .doomednum = ACTOR_WATER_EXTRACTOR, .spawnstate = S_NCWEL1L0_STND, .spawnhealth = 500,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_TAELON_EXTRACTOR
        .doomednum = ACTOR_TAELON_EXTRACTOR, .spawnstate = S_NCMIN1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_WATER_RESEARCH
        .doomednum = ACTOR_IMP_WATER_RESEARCH, .spawnstate = S_NOWAT1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_HOVER_RESEARCH
        .doomednum = ACTOR_IMP_HOVER_RESEARCH, .spawnstate = S_NOHOV1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_DESICATOR_RESEARCH
        .doomednum = ACTOR_IMP_DESICATOR_RESEARCH, .spawnstate = S_NODES1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_GENETIC_RESEARCH
        .doomednum = ACTOR_IMP_GENETIC_RESEARCH, .spawnstate = S_NOMDR1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_SHELTER
        .doomednum = ACTOR_CIV_SHELTER, .spawnstate = S_NOSHL1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_SUB_TRANSIT
        .doomednum = ACTOR_CIV_SUB_TRANSIT, .spawnstate = S_NOSUB1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_TRANSIT_CENTRE
        .doomednum = ACTOR_CIV_TRANSIT_CENTRE, .spawnstate = S_NOTCN1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_TREATY_HALL
        .doomednum = ACTOR_FG_TREATY_HALL, .spawnstate = S_NOTYH1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_TOGRAN_LANDING_VESSEL
        .doomednum = ACTOR_TOGRAN_LANDING_VESSEL, .spawnstate = S_NOTHQ1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_TOGRAN_MONOLITH
        .doomednum = ACTOR_TOGRAN_MONOLITH, .spawnstate = S_NOMLT1L0_STND, .spawnhealth = 92000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_TOGRAN_LABORATORY
        .doomednum = ACTOR_TOGRAN_LABORATORY, .spawnstate = S_NOTDR1L0_STND, .spawnhealth = 90000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_RENDEZVOUS_POINT
        .doomednum = ACTOR_RENDEZVOUS_POINT, .spawnstate = S_NORVP1L0_STND, .spawnhealth = 1000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PLANETARY_DEFENSE
        .doomednum = ACTOR_FG_PLANETARY_DEFENSE, .spawnstate = S_NOPLD1L0_STND, .spawnhealth = 2500,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_COMMERCIAL
        .doomednum = ACTOR_CIV_COMMERCIAL, .spawnstate = S_NOCBS1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_FACTORY
        .doomednum = ACTOR_CIV_FACTORY, .spawnstate = S_NOWAR1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_IMP_PRISON
        .doomednum = ACTOR_IMP_PRISON, .spawnstate = S_NOPRI1L0_STND, .spawnhealth = 2500,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_RURAL
        .doomednum = ACTOR_CIV_RURAL, .spawnstate = S_NOCHM4L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_GRAIN_FARM
        .doomednum = ACTOR_CIV_GRAIN_FARM, .spawnstate = S_NOFRM1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_HYDRO_FARM
        .doomednum = ACTOR_CIV_HYDRO_FARM, .spawnstate = S_NOFRM1L1_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIV_FARMHOUSE
        .doomednum = ACTOR_CIV_FARMHOUSE, .spawnstate = S_NOFRM1L2_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIVILIAN_BRIDGE
        .doomednum = ACTOR_CIVILIAN_BRIDGE, .spawnstate = S_NOBRD1L0_STND, .spawnhealth = 4000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_CIVILIAN_VERTICAL_BRIDGE
        .doomednum = ACTOR_CIVILIAN_VERTICAL_BRIDGE, .spawnstate = S_NOBRD1L1_STND, .spawnhealth = 4000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_TOGRAN_BRIDGE_H
        .doomednum = ACTOR_TOGRAN_SMALL_HORIZONTAL_BRIDGE, .spawnstate = S_NCSBH1L0_T_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_TOGRAN_BRIDGE_V
        .doomednum = ACTOR_TOGRAN_SMALL_VERTICAL_BRIDGE, .spawnstate = S_NCSBV1L0_T_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_TOGRAN_BRIDGE_C
        .doomednum = ACTOR_TOGRAN_SMALL_CENTRE_BRIDGE, .spawnstate = S_NCSBC1L0_T_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
};

const gameinfo_t game_info = {
    sprnames, NUMSPRITES, states, NUMSTATES, mobjinfo, NUMMOBJTYPES,
    S_NULL, RTS_STATE_COORDS_GROUND_OFFSET,
    { .style = SELECTION_STYLE_BRACKETS },
    NULL,
    .harvest_dropoff_matches = DR_HarvestDropoffMatches,
};
