#include "engine.h"
#include "dr_types.h"
#include "info.h"

const char *const sprnames[NUMSPRITES] = {
    /* Support */
    "ucfcnst0.spr", "ucfrgst0.spr", "uchfrst0.spr",
    /* Infantry */
    "ufradst0.spr", "ufmrcst0.spr", "ufsnpst0.spr", "ufsctst0.spr",
    "ufmedst0.spr", "ufsabst0.spr", "ufmecst0.spr", "ufmtrst0.spr", "ucinfst0.spr",
    /* Vehicles */
    "ufspbst0.spr", "ufratst0.spr", "ufsktst0.spr", "ufthnst0.spr",
    "ufphtst0.spr", "ufflkst0.spr", "uftrtst0.spr", "uffarst0.spr",
    /* Air */
    "ufskbst0.spr", "ufoutst0.spr",
    /* Experimental */
    "ufswvst0.spr", "ucwcost0.spr", "ucphrst0.spr", "ucbmvst0.spr",
    /* Buildings */
    "nfhqt1l0.spr", "nfhqt2l0.spr", "nfhqt3l0.spr",
    "nfutf1l0.spr", "nfutf2l0.spr",
    "nfvcy1l0.spr", "nfvcy2l0.spr",
    "nfhsp1l0.spr", "nfrep1l0.spr",
    "nfphf1l0.spr", "nfphf2l0.spr",
    "nccam1l0.spr", "nclnc1l0.spr", "ncpow1l0.spr",
    "nfrrm1l0.spr",
    "ncsbh1l0.spr", "ncsbv1l0.spr", "ncsbc1l0.spr",
    "nfgdt1l0.spr", "nfagt1l0.spr", "nfaar1l0.spr",
};

const state_t states[NUMSTATES] = {
    { 0, 0, -1, NULL, S_NULL, 0 },
    /* Support */
    { SPR_UCFCNST0, 0, -1, NULL, S_UCFCNST0_STND, 0 },
    { SPR_UCFRGST0, 0, -1, NULL, S_UCFRGST0_STND, 0 },
    { SPR_UCHFRST0, 0, -1, NULL, S_UCHFRST0_STND, 0 },
    /* Infantry */
    { SPR_UFRADST0, 0, -1, NULL, S_UFRADST0_STND, 0 },
    { SPR_UFMRCST0, 0, -1, NULL, S_UFMRCST0_STND, 0 },
    { SPR_UFSNPST0, 0, -1, NULL, S_UFSNPST0_STND, 0 },
    { SPR_UFSCTST0, 0, -1, NULL, S_UFSCTST0_STND, 0 },
    { SPR_UFMEDST0, 0, -1, NULL, S_UFMEDST0_STND, 0 },
    { SPR_UFSABST0, 0, -1, NULL, S_UFSABST0_STND, 0 },
    { SPR_UFMECST0, 0, -1, NULL, S_UFMECST0_STND, 0 },
    { SPR_UFMTRST0, 0, -1, NULL, S_UFMTRST0_STND, 0 },
    { SPR_UCINFST0, 0, -1, NULL, S_UCINFST0_STND, 0 },
    /* Vehicles */
    { SPR_UFSPBST0, 0, -1, NULL, S_UFSPBST0_STND, 0 },
    { SPR_UFRATST0, 0, -1, NULL, S_UFRATST0_STND, 0 },
    { SPR_UFSKTST0, 0, -1, NULL, S_UFSKTST0_STND, 0 },
    { SPR_UFTHNST0, 0, -1, NULL, S_UFTHNST0_STND, 0 },
    { SPR_UFPHTST0, 0, -1, NULL, S_UFPHTST0_STND, 0 },
    { SPR_UFFLKST0, 0, -1, NULL, S_UFFLKST0_STND, 0 },
    { SPR_UFTRTST0, 0, -1, NULL, S_UFTRTST0_STND, 0 },
    { SPR_UFFARST0, 0, -1, NULL, S_UFFARST0_STND, 0 },
    /* Air */
    { SPR_UFSKBST0, 0, -1, NULL, S_UFSKBST0_STND, 0 },
    { SPR_UFOUTST0, 0, -1, NULL, S_UFOUTST0_STND, 0 },
    /* Experimental */
    { SPR_UFSWVST0, 0, -1, NULL, S_UFSWVST0_STND, 0 },
    { SPR_UCWCOST0, 0, -1, NULL, S_UCWCOST0_STND, 0 },
    { SPR_UCPHRST0, 0, -1, NULL, S_UCPHRST0_STND, 0 },
    { SPR_UCBMVST0, 0, -1, NULL, S_UCBMVST0_STND, 0 },
    /* Buildings */
    { SPR_NFHQT1L0, 0, -1, NULL, S_NFHQT1L0_STND, 0 },
    { SPR_NFHQT2L0, 0, -1, NULL, S_NFHQT2L0_STND, 0 },
    { SPR_NFHQT3L0, 0, -1, NULL, S_NFHQT3L0_STND, 0 },
    { SPR_NFUTF1L0, 0, -1, NULL, S_NFUTF1L0_STND, 0 },
    { SPR_NFUTF2L0, 0, -1, NULL, S_NFUTF2L0_STND, 0 },
    { SPR_NFVCY1L0, 0, -1, NULL, S_NFVCY1L0_STND, 0 },
    { SPR_NFVCY2L0, 0, -1, NULL, S_NFVCY2L0_STND, 0 },
    { SPR_NFHSP1L0, 0, -1, NULL, S_NFHSP1L0_STND, 0 },
    { SPR_NFREP1L0, 0, -1, NULL, S_NFREP1L0_STND, 0 },
    { SPR_NFPHF1L0, 0, -1, NULL, S_NFPHF1L0_STND, 0 },
    { SPR_NFPHF2L0, 0, -1, NULL, S_NFPHF2L0_STND, 0 },
    { SPR_NCCAM1L0, 0, -1, NULL, S_NCCAM1L0_STND, 0 },
    { SPR_NCLNC1L0, 0, -1, NULL, S_NCLNC1L0_STND, 0 },
    { SPR_NCPOW1L0, 0, -1, NULL, S_NCPOW1L0_STND, 0 },
    { SPR_NFRRM1L0, 0, -1, NULL, S_NFRRM1L0_STND, 0 },
    { SPR_NCSBH1L0, 0, -1, NULL, S_NCSBH1L0_STND, 0 },
    { SPR_NCSBV1L0, 0, -1, NULL, S_NCSBV1L0_STND, 0 },
    { SPR_NCSBC1L0, 0, -1, NULL, S_NCSBC1L0_STND, 0 },
    { SPR_NFGDT1L0, 0, -1, NULL, S_NFGDT1L0_STND, 0 },
    { SPR_NFAGT1L0, 0, -1, NULL, S_NFAGT1L0_STND, 0 },
    { SPR_NFAAR1L0, 0, -1, NULL, S_NFAAR1L0_STND, 0 },
};

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {
    { // MT_NULL
        0,
    },
    { // MT_FG_CONSTRUCTION_CREW
        .doomednum    = ACTOR_FG_CONSTRUCTION_CREW,
        .spawnstate   = S_UCFCNST0_STND,
        .spawnhealth  = 100,
        .seestate     = S_UCFCNST0_STND,
        .missilestate = S_UCFCNST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 6,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 20,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_FREIGHTER
        .doomednum    = ACTOR_FG_GROUND_TRANSPORTER,
        .spawnstate   = S_UCFRGST0_STND,
        .spawnhealth  = 750,
        .seestate     = S_UCFRGST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_FG_HOVER_FREIGHTER
        .doomednum    = ACTOR_FG_HOVER_TRANSPORTER,
        .spawnstate   = S_UCHFRST0_STND,
        .spawnhealth  = 500,
        .seestate     = S_UCHFRST0_STND,
        .missilestate = S_UCHFRST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 11,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER|MF_ATTACK,
    },
    { // MT_FG_RAIDER
        .doomednum    = ACTOR_FG_RAIDER,
        .spawnstate   = S_UFRADST0_STND,
        .spawnhealth  = 100,
        .seestate     = S_UFRADST0_STND,
        .missilestate = S_UFRADST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 11,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_MERCENARY
        .doomednum    = ACTOR_FG_MERCENARY,
        .spawnstate   = S_UFMRCST0_STND,
        .spawnhealth  = 125,
        .seestate     = S_UFMRCST0_STND,
        .missilestate = S_UFMRCST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 11,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SNIPER
        .doomednum    = ACTOR_FG_SNIPER,
        .spawnstate   = S_UFSNPST0_STND,
        .spawnhealth  = 100,
        .seestate     = S_UFSNPST0_STND,
        .missilestate = S_UFSNPST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 150,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SCOUT
        .doomednum    = ACTOR_FG_SCOUT,
        .spawnstate   = S_UFSCTST0_STND,
        .spawnhealth  = 66,
        .seestate     = S_UFSCTST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 6,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MEDIC
        .doomednum    = ACTOR_FG_MEDIC,
        .spawnstate   = S_UFMEDST0_STND,
        .spawnhealth  = 66,
        .seestate     = S_UFMEDST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_SABOTEUR
        .doomednum    = ACTOR_FG_SABOTEUR,
        .spawnstate   = S_UFSABST0_STND,
        .spawnhealth  = 100,
        .seestate     = S_UFSABST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MECHANIC
        .doomednum    = ACTOR_FG_MECHANIC,
        .spawnstate   = S_UFMECST0_STND,
        .spawnhealth  = 66,
        .seestate     = S_UFMECST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MARTYR
        .doomednum    = ACTOR_FG_SUICIDE_NUKER,
        .spawnstate   = S_UFMTRST0_STND,
        .spawnhealth  = 100,
        .seestate     = S_UFMTRST0_STND,
        .missilestate = S_UFMTRST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 180,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SPY
        .doomednum    = ACTOR_FG_SPY,
        .spawnstate   = S_UCINFST0_STND,
        .spawnhealth  = 66,
        .seestate     = S_UCINFST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_SPYDER_BIKE
        .doomednum    = ACTOR_FG_SPYDER_BIKE,
        .spawnstate   = S_UFSPBST0_STND,
        .spawnhealth  = 133,
        .seestate     = S_UFSPBST0_STND,
        .missilestate = S_UFSPBST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 7,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 10,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_IFV
        .doomednum    = ACTOR_FG_IFV,
        .spawnstate   = S_UFRATST0_STND,
        .spawnhealth  = 200,
        .seestate     = S_UFRATST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MEDIUM_TANK
        .doomednum    = ACTOR_FG_MEDIUM_TANK,
        .spawnstate   = S_UFSKTST0_STND,
        .spawnhealth  = 133,
        .seestate     = S_UFSKTST0_STND,
        .missilestate = S_UFSKTST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 4,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 14,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_TANK_HUNTER
        .doomednum    = ACTOR_FG_TANK_HUNTER,
        .spawnstate   = S_UFTHNST0_STND,
        .spawnhealth  = 150,
        .seestate     = S_UFTHNST0_STND,
        .missilestate = S_UFTHNST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 4,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 60,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_PHASE_TANK
        .doomednum    = ACTOR_FG_PHASE_TANK,
        .spawnstate   = S_UFPHTST0_STND,
        .spawnhealth  = 166,
        .seestate     = S_UFPHTST0_STND,
        .missilestate = S_UFPHTST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 4,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 30,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_MAD
        .doomednum    = ACTOR_FG_MAD,
        .spawnstate   = S_UFFLKST0_STND,
        .spawnhealth  = 100,
        .seestate     = S_UFFLKST0_STND,
        .missilestate = S_UFFLKST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 4,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 8,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_TRIPLE_RAIL_TANK
        .doomednum    = ACTOR_FG_TRIPLE_RAIL_TANK,
        .spawnstate   = S_UFTRTST0_STND,
        .spawnhealth  = 200,
        .seestate     = S_UFTRTST0_STND,
        .missilestate = S_UFTRTST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 4,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 24,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SPA
        .doomednum    = ACTOR_FG_SPA,
        .spawnstate   = S_UFFARST0_STND,
        .spawnhealth  = 133,
        .seestate     = S_UFFARST0_STND,
        .missilestate = S_UFFARST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 4,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 30,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SKY_BIKE
        .doomednum    = ACTOR_FG_SKY_BIKE,
        .spawnstate   = S_UFSKBST0_STND,
        .spawnhealth  = 100,
        .seestate     = S_UFSKBST0_STND,
        .missilestate = S_UFSKBST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 6,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 10,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY,
    },
    { // MT_FG_OUTRIDER
        .doomednum    = ACTOR_FG_OUTRIDER,
        .spawnstate   = S_UFOUTST0_STND,
        .spawnhealth  = 200,
        .seestate     = S_UFOUTST0_STND,
        .missilestate = S_UFOUTST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 20,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY,
    },
    { // MT_FG_SHOCKWAVE
        .doomednum    = ACTOR_FG_SHOCKWAVE,
        .spawnstate   = S_UFSWVST0_STND,
        .spawnhealth  = 166,
        .seestate     = S_UFSWVST0_STND,
        .missilestate = S_UFSWVST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 4,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 17,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_CONTAMINATOR
        .doomednum    = ACTOR_FG_CONTAMINATOR,
        .spawnstate   = S_UCWCOST0_STND,
        .spawnhealth  = 166,
        .seestate     = S_UCWCOST0_STND,
        .missilestate = S_UCWCOST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 3,
        .radius = 16, .height = 32, .mass = 100,
        .damage = 5,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_UNDERGROUND_TUNNEL
        .doomednum    = ACTOR_FG_UNDERGROUND_TUNNEL,
        .spawnstate   = S_UCPHRST0_STND,
        .spawnhealth  = 150,
        .seestate     = S_UCPHRST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 5,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_BASE_MOVER
        .doomednum    = ACTOR_FG_BASE_MOVER,
        .spawnstate   = S_UCBMVST0_STND,
        .spawnhealth  = 500,
        .seestate     = S_UCBMVST0_STND,
        .deathstate   = S_NULL,
        .xdeathstate  = S_NULL,
        .speed = 3,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_HQ1
        .doomednum   = ACTOR_FG_HEADQUARTERS_1,
        .spawnstate  = S_NFHQT1L0_STND,
        .spawnhealth = 1200,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_FG_HQ2
        .doomednum   = ACTOR_FG_HEADQUARTERS_2,
        .spawnstate  = S_NFHQT2L0_STND,
        .spawnhealth = 2400,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HQ3
        .doomednum   = ACTOR_FG_HEADQUARTERS_3,
        .spawnstate  = S_NFHQT3L0_STND,
        .spawnhealth = 3600,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BARRACKS
        .doomednum   = ACTOR_FG_TRAINING_FACILITY_1,
        .spawnstate  = S_NFUTF1L0_STND,
        .spawnhealth = 750,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_ADV_BARRACKS
        .doomednum   = ACTOR_FG_TRAINING_FACILITY_2,
        .spawnstate  = S_NFUTF2L0_STND,
        .spawnhealth = 1500,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_VEHICLE_FACTORY
        .doomednum   = ACTOR_FG_VEHICLE_FACTORY_1,
        .spawnstate  = S_NFVCY1L0_STND,
        .spawnhealth = 1000,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_ADV_VEHICLE_FACTORY
        .doomednum   = ACTOR_FG_VEHICLE_FACTORY_2,
        .spawnstate  = S_NFVCY2L0_STND,
        .spawnhealth = 2000,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HOVER_FACTORY
        .doomednum   = ACTOR_FG_HOVER_FACTORY,
        .spawnstate  = S_NFHSP1L0_STND,
        .spawnhealth = 600,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REPAIR_BAY
        .doomednum   = ACTOR_FG_REPAIR_BAY,
        .spawnstate  = S_NFREP1L0_STND,
        .spawnhealth = 600,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_1
        .doomednum   = ACTOR_FG_PHASE_FACTORY_1,
        .spawnstate  = S_NFPHF1L0_STND,
        .spawnhealth = 1000,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_2
        .doomednum   = ACTOR_FG_PHASE_FACTORY_2,
        .spawnstate  = S_NFPHF2L0_STND,
        .spawnhealth = 2000,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_CAMERA_TOWER
        .doomednum   = ACTOR_FG_CAMERA_TOWER,
        .spawnstate  = S_NCCAM1L0_STND,
        .spawnhealth = 150,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_LIFE_PLANT
        .doomednum   = ACTOR_FG_LIFE_PLANT,
        .spawnstate  = S_NCLNC1L0_STND,
        .spawnhealth = 1300,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_POWER_PLANT
        .doomednum   = ACTOR_FG_POWER_PLANT,
        .spawnstate  = S_NCPOW1L0_STND,
        .spawnhealth = 1450,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REFINERY
        .doomednum   = ACTOR_FG_REFINERY,
        .spawnstate  = S_NFRRM1L0_STND,
        .spawnhealth = 800,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_H
        .doomednum   = ACTOR_FG_SMALL_HORIZONTAL_BRIDGE,
        .spawnstate  = S_NCSBH1L0_STND,
        .spawnhealth = 400,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_V
        .doomednum   = ACTOR_FG_SMALL_VERTICAL_BRIDGE,
        .spawnstate  = S_NCSBV1L0_STND,
        .spawnhealth = 400,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_C
        .doomednum   = ACTOR_FG_SMALL_CENTRE_BRIDGE,
        .spawnstate  = S_NCSBC1L0_STND,
        .spawnhealth = 400,
        .deathstate  = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_GUARD_TOWER
        .doomednum    = ACTOR_FG_GUARD_TOWER,
        .spawnstate   = S_NFGDT1L0_STND,
        .spawnhealth  = 400,
        .missilestate = S_NFGDT1L0_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 10,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_ADV_GUARD_TOWER
        .doomednum    = ACTOR_FG_ADVANCED_GUARD_TOWER,
        .spawnstate   = S_NFAGT1L0_STND,
        .spawnhealth  = 550,
        .missilestate = S_NFAGT1L0_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 13,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_AA_SITE
        .doomednum    = ACTOR_FG_AA_SITE,
        .spawnstate   = S_NFAAR1L0_STND,
        .spawnhealth  = 600,
        .missilestate = S_NFAAR1L0_STND,
        .deathstate   = S_NULL, .xdeathstate = S_NULL,
        .damage = 40,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
};

const gameinfo_t game_info = {
    sprnames,
    NUMSPRITES,
    states,
    NUMSTATES,
    mobjinfo,
    NUMMOBJTYPES,
    S_NULL,
    RTS_STATE_COORDS_GROUND_OFFSET,
    { .style = SELECTION_STYLE_BRACKETS },
    NULL,
};
