/* Generated from retail DEFTXT and the OpenDR sprite catalog. Do not edit by hand. */
#include "engine.h"
#include "dr_types.h"
#include "info.h"

const char *const sprnames[NUMSPRITES] = {
    "ucfcnst0.spr",
    "ucfrgst0.spr",
    "uchfrst0.spr",
    "ufradst0.spr",
    "ufmrcst0.spr",
    "ufsnpst0.spr",
    "ufsctst0.spr",
    "ufmedst0.spr",
    "ufsabst0.spr",
    "ufmecst0.spr",
    "ufmtrst0.spr",
    "ucinfst0.spr",
    "ufspbst0.spr",
    "ufratst0.spr",
    "ufsktst0.spr",
    "ufthnst0.spr",
    "ufphtst0.spr",
    "ufflkst0.spr",
    "uftrtst0.spr",
    "uffarst0.spr",
    "ufskbst0.spr",
    "ufoutst0.spr",
    "ufswvst0.spr",
    "ucwcost0.spr",
    "ufphrst0.spr",
    "ufbamst0.spr",
    "nfhqt1l0.spr",
    "nfhqt2l0.spr",
    "nfhqt3l0.spr",
    "nfutf1l0.spr",
    "nfutf2l0.spr",
    "nfvcy1l0.spr",
    "nfvcy2l0.spr",
    "nfhsp1l0.spr",
    "nfrep1l0.spr",
    "nfphf1l0.spr",
    "nfphf2l0.spr",
    "nccam1l0.spr",
    "nclnc1l0.spr",
    "ncpow1l0.spr",
    "nfrrm1l0.spr",
    "ncsbh1l0.spr",
    "ncsbv1l0.spr",
    "ncsbc1l0.spr",
    "nfgdt1l0.spr",
    "nfagt1l0.spr",
    "nfaar1l0.spr",
};

const state_t states[NUMSTATES] = {
    { 0, 0, -1, NULL, S_NULL, 0 },
    { SPR_UCFCNST0, 6, 20, A_Look, S_UCFCNST0_STND, 0 },
    { SPR_UCFCNST0, 0, 4, A_Chase, S_UCFCNST0_RUN2, 2 },
    { SPR_UCFCNST0, 1, 4, NULL, S_UCFCNST0_RUN3, 2 },
    { SPR_UCFCNST0, 2, 4, NULL, S_UCFCNST0_RUN4, 2 },
    { SPR_UCFCNST0, 3, 4, NULL, S_UCFCNST0_RUN5, 2 },
    { SPR_UCFCNST0, 4, 4, NULL, S_UCFCNST0_RUN6, 2 },
    { SPR_UCFCNST0, 5, 4, NULL, S_UCFCNST0_RUN1, 2 },
    { SPR_UCFRGST0, 0, -1, NULL, S_UCFRGST0_STND, 0 },
    { SPR_UCFRGST0, 0, 6, NULL, S_UCFRGST0_RUN2, 2 },
    { SPR_UCFRGST0, 1, 6, NULL, S_UCFRGST0_RUN3, 2 },
    { SPR_UCFRGST0, 2, 6, NULL, S_UCFRGST0_RUN1, 2 },
    { SPR_UCHFRST0, 0, 20, A_Look, S_UCHFRST0_STND, 0 },
    { SPR_UCHFRST0, 0, 6, A_Chase, S_UCHFRST0_RUN1, 2 },
    { SPR_UFRADST0, 15, 20, A_Look, S_UFRADST0_STND, 0 },
    { SPR_UFRADST0, 0, 2, A_Chase, S_UFRADST0_RUN2, 2 },
    { SPR_UFRADST0, 1, 2, NULL, S_UFRADST0_RUN3, 2 },
    { SPR_UFRADST0, 2, 2, NULL, S_UFRADST0_RUN4, 2 },
    { SPR_UFRADST0, 3, 2, NULL, S_UFRADST0_RUN5, 2 },
    { SPR_UFRADST0, 4, 2, NULL, S_UFRADST0_RUN6, 2 },
    { SPR_UFRADST0, 5, 2, NULL, S_UFRADST0_RUN1, 2 },
    { SPR_UFRADST0, 6, 2, A_Attack, S_UFRADST0_SHOOT2, 3 },
    { SPR_UFRADST0, 7, 2, NULL, S_UFRADST0_STND, 3 },
    { SPR_UFRADST0, 8, 10, NULL, S_UFRADST0_IDLE2, 0 },
    { SPR_UFRADST0, 9, 10, NULL, S_UFRADST0_IDLE3, 0 },
    { SPR_UFRADST0, 10, 10, NULL, S_UFRADST0_IDLE4, 0 },
    { SPR_UFRADST0, 11, 10, NULL, S_UFRADST0_IDLE5, 0 },
    { SPR_UFRADST0, 12, 10, NULL, S_UFRADST0_IDLE6, 0 },
    { SPR_UFRADST0, 13, 10, NULL, S_UFRADST0_IDLE7, 0 },
    { SPR_UFRADST0, 14, 10, NULL, S_UFRADST0_IDLE1, 0 },
    { SPR_UFMRCST0, 18, 20, A_Look, S_UFMRCST0_STND, 0 },
    { SPR_UFMRCST0, 0, 2, A_Chase, S_UFMRCST0_RUN2, 2 },
    { SPR_UFMRCST0, 1, 2, NULL, S_UFMRCST0_RUN3, 2 },
    { SPR_UFMRCST0, 2, 2, NULL, S_UFMRCST0_RUN4, 2 },
    { SPR_UFMRCST0, 3, 2, NULL, S_UFMRCST0_RUN5, 2 },
    { SPR_UFMRCST0, 4, 2, NULL, S_UFMRCST0_RUN6, 2 },
    { SPR_UFMRCST0, 5, 2, NULL, S_UFMRCST0_RUN1, 2 },
    { SPR_UFMRCST0, 6, 2, A_Attack, S_UFMRCST0_SHOOT2, 3 },
    { SPR_UFMRCST0, 7, 2, NULL, S_UFMRCST0_STND, 3 },
    { SPR_UFMRCST0, 8, 10, NULL, S_UFMRCST0_IDLE2, 0 },
    { SPR_UFMRCST0, 9, 10, NULL, S_UFMRCST0_IDLE3, 0 },
    { SPR_UFMRCST0, 10, 10, NULL, S_UFMRCST0_IDLE4, 0 },
    { SPR_UFMRCST0, 11, 10, NULL, S_UFMRCST0_IDLE5, 0 },
    { SPR_UFMRCST0, 12, 10, NULL, S_UFMRCST0_IDLE1, 0 },
    { SPR_UFSNPST0, 30, 20, A_Look, S_UFSNPST0_STND, 0 },
    { SPR_UFSNPST0, 0, 6, A_Chase, S_UFSNPST0_RUN2, 2 },
    { SPR_UFSNPST0, 1, 6, NULL, S_UFSNPST0_RUN3, 2 },
    { SPR_UFSNPST0, 2, 6, NULL, S_UFSNPST0_RUN4, 2 },
    { SPR_UFSNPST0, 3, 6, NULL, S_UFSNPST0_RUN5, 2 },
    { SPR_UFSNPST0, 4, 6, NULL, S_UFSNPST0_RUN6, 2 },
    { SPR_UFSNPST0, 5, 6, NULL, S_UFSNPST0_RUN1, 2 },
    { SPR_UFSNPST0, 9, 6, A_Attack, S_UFSNPST0_SHOOT2, 3 },
    { SPR_UFSNPST0, 10, 6, NULL, S_UFSNPST0_SHOOT3, 3 },
    { SPR_UFSNPST0, 11, 6, NULL, S_UFSNPST0_SHOOT4, 3 },
    { SPR_UFSNPST0, 12, 6, NULL, S_UFSNPST0_STND, 3 },
    { SPR_UFSNPST0, 30, 10, NULL, S_UFSNPST0_IDLE1, 0 },
    { SPR_UFSCTST0, 19, -1, NULL, S_UFSCTST0_STND, 0 },
    { SPR_UFSCTST0, 0, 6, NULL, S_UFSCTST0_RUN2, 2 },
    { SPR_UFSCTST0, 1, 6, NULL, S_UFSCTST0_RUN3, 2 },
    { SPR_UFSCTST0, 2, 6, NULL, S_UFSCTST0_RUN4, 2 },
    { SPR_UFSCTST0, 3, 6, NULL, S_UFSCTST0_RUN5, 2 },
    { SPR_UFSCTST0, 4, 6, NULL, S_UFSCTST0_RUN6, 2 },
    { SPR_UFSCTST0, 5, 6, NULL, S_UFSCTST0_RUN7, 2 },
    { SPR_UFSCTST0, 6, 6, NULL, S_UFSCTST0_RUN8, 2 },
    { SPR_UFSCTST0, 7, 6, NULL, S_UFSCTST0_RUN1, 2 },
    { SPR_UFSCTST0, 8, 6, NULL, S_UFSCTST0_SHOOT2, 3 },
    { SPR_UFSCTST0, 9, 6, NULL, S_UFSCTST0_SHOOT3, 3 },
    { SPR_UFSCTST0, 10, 6, NULL, S_UFSCTST0_STND, 3 },
    { SPR_UFSCTST0, 19, 10, NULL, S_UFSCTST0_IDLE1, 0 },
    { SPR_UFMEDST0, 22, -1, NULL, S_UFMEDST0_STND, 0 },
    { SPR_UFMEDST0, 0, 6, NULL, S_UFMEDST0_RUN2, 2 },
    { SPR_UFMEDST0, 1, 6, NULL, S_UFMEDST0_RUN3, 2 },
    { SPR_UFMEDST0, 2, 6, NULL, S_UFMEDST0_RUN4, 2 },
    { SPR_UFMEDST0, 3, 6, NULL, S_UFMEDST0_RUN5, 2 },
    { SPR_UFMEDST0, 4, 6, NULL, S_UFMEDST0_RUN6, 2 },
    { SPR_UFMEDST0, 5, 6, NULL, S_UFMEDST0_RUN1, 2 },
    { SPR_UFMEDST0, 6, 6, NULL, S_UFMEDST0_SHOOT2, 3 },
    { SPR_UFMEDST0, 7, 6, NULL, S_UFMEDST0_SHOOT3, 3 },
    { SPR_UFMEDST0, 8, 6, NULL, S_UFMEDST0_SHOOT4, 3 },
    { SPR_UFMEDST0, 9, 6, NULL, S_UFMEDST0_SHOOT5, 3 },
    { SPR_UFMEDST0, 10, 6, NULL, S_UFMEDST0_SHOOT6, 3 },
    { SPR_UFMEDST0, 11, 6, NULL, S_UFMEDST0_SHOOT7, 3 },
    { SPR_UFMEDST0, 12, 6, NULL, S_UFMEDST0_SHOOT8, 3 },
    { SPR_UFMEDST0, 13, 6, NULL, S_UFMEDST0_SHOOT9, 3 },
    { SPR_UFMEDST0, 14, 6, NULL, S_UFMEDST0_SHOOT10, 3 },
    { SPR_UFMEDST0, 15, 6, NULL, S_UFMEDST0_STND, 3 },
    { SPR_UFMEDST0, 16, 10, NULL, S_UFMEDST0_IDLE2, 0 },
    { SPR_UFMEDST0, 17, 10, NULL, S_UFMEDST0_IDLE3, 0 },
    { SPR_UFMEDST0, 18, 10, NULL, S_UFMEDST0_IDLE4, 0 },
    { SPR_UFMEDST0, 19, 10, NULL, S_UFMEDST0_IDLE5, 0 },
    { SPR_UFMEDST0, 20, 10, NULL, S_UFMEDST0_IDLE6, 0 },
    { SPR_UFMEDST0, 21, 10, NULL, S_UFMEDST0_IDLE1, 0 },
    { SPR_UFSABST0, 8, -1, NULL, S_UFSABST0_STND, 0 },
    { SPR_UFSABST0, 0, 6, NULL, S_UFSABST0_RUN2, 2 },
    { SPR_UFSABST0, 1, 6, NULL, S_UFSABST0_RUN3, 2 },
    { SPR_UFSABST0, 2, 6, NULL, S_UFSABST0_RUN4, 2 },
    { SPR_UFSABST0, 3, 6, NULL, S_UFSABST0_RUN5, 2 },
    { SPR_UFSABST0, 4, 6, NULL, S_UFSABST0_RUN6, 2 },
    { SPR_UFSABST0, 5, 6, NULL, S_UFSABST0_RUN7, 2 },
    { SPR_UFSABST0, 6, 6, NULL, S_UFSABST0_RUN8, 2 },
    { SPR_UFSABST0, 7, 6, NULL, S_UFSABST0_RUN1, 2 },
    { SPR_UFMECST0, 24, -1, NULL, S_UFMECST0_STND, 0 },
    { SPR_UFMECST0, 0, 6, NULL, S_UFMECST0_RUN2, 2 },
    { SPR_UFMECST0, 1, 6, NULL, S_UFMECST0_RUN3, 2 },
    { SPR_UFMECST0, 2, 6, NULL, S_UFMECST0_RUN4, 2 },
    { SPR_UFMECST0, 3, 6, NULL, S_UFMECST0_RUN5, 2 },
    { SPR_UFMECST0, 4, 6, NULL, S_UFMECST0_RUN6, 2 },
    { SPR_UFMECST0, 5, 6, NULL, S_UFMECST0_RUN7, 2 },
    { SPR_UFMECST0, 6, 6, NULL, S_UFMECST0_RUN8, 2 },
    { SPR_UFMECST0, 7, 6, NULL, S_UFMECST0_RUN1, 2 },
    { SPR_UFMECST0, 8, 6, NULL, S_UFMECST0_SHOOT2, 3 },
    { SPR_UFMECST0, 9, 6, NULL, S_UFMECST0_SHOOT3, 3 },
    { SPR_UFMECST0, 10, 6, NULL, S_UFMECST0_SHOOT4, 3 },
    { SPR_UFMECST0, 11, 6, NULL, S_UFMECST0_SHOOT5, 3 },
    { SPR_UFMECST0, 12, 6, NULL, S_UFMECST0_SHOOT6, 3 },
    { SPR_UFMECST0, 13, 6, NULL, S_UFMECST0_SHOOT7, 3 },
    { SPR_UFMECST0, 14, 6, NULL, S_UFMECST0_SHOOT8, 3 },
    { SPR_UFMECST0, 15, 6, NULL, S_UFMECST0_STND, 3 },
    { SPR_UFMTRST0, 25, 20, A_Look, S_UFMTRST0_STND, 0 },
    { SPR_UFMTRST0, 0, 6, A_Chase, S_UFMTRST0_RUN2, 2 },
    { SPR_UFMTRST0, 1, 6, NULL, S_UFMTRST0_RUN3, 2 },
    { SPR_UFMTRST0, 2, 6, NULL, S_UFMTRST0_RUN4, 2 },
    { SPR_UFMTRST0, 3, 6, NULL, S_UFMTRST0_RUN5, 2 },
    { SPR_UFMTRST0, 4, 6, NULL, S_UFMTRST0_RUN6, 2 },
    { SPR_UFMTRST0, 5, 6, NULL, S_UFMTRST0_RUN1, 2 },
    { SPR_UFMTRST0, 6, 6, A_Attack, S_UFMTRST0_SHOOT2, 3 },
    { SPR_UFMTRST0, 7, 6, NULL, S_UFMTRST0_SHOOT3, 3 },
    { SPR_UFMTRST0, 8, 6, NULL, S_UFMTRST0_SHOOT4, 3 },
    { SPR_UFMTRST0, 9, 6, NULL, S_UFMTRST0_SHOOT5, 3 },
    { SPR_UFMTRST0, 10, 6, NULL, S_UFMTRST0_SHOOT6, 3 },
    { SPR_UFMTRST0, 11, 6, NULL, S_UFMTRST0_SHOOT7, 3 },
    { SPR_UFMTRST0, 12, 6, NULL, S_UFMTRST0_SHOOT8, 3 },
    { SPR_UFMTRST0, 13, 6, NULL, S_UFMTRST0_SHOOT9, 3 },
    { SPR_UFMTRST0, 14, 6, NULL, S_UFMTRST0_SHOOT10, 3 },
    { SPR_UFMTRST0, 15, 6, NULL, S_UFMTRST0_SHOOT11, 3 },
    { SPR_UFMTRST0, 16, 6, NULL, S_UFMTRST0_SHOOT12, 3 },
    { SPR_UFMTRST0, 17, 6, NULL, S_UFMTRST0_SHOOT13, 3 },
    { SPR_UFMTRST0, 18, 6, NULL, S_UFMTRST0_SHOOT14, 3 },
    { SPR_UFMTRST0, 19, 6, NULL, S_UFMTRST0_SHOOT15, 3 },
    { SPR_UFMTRST0, 20, 6, NULL, S_UFMTRST0_SHOOT16, 3 },
    { SPR_UFMTRST0, 21, 6, NULL, S_UFMTRST0_STND, 3 },
    { SPR_UFMTRST0, 22, 10, NULL, S_UFMTRST0_IDLE2, 0 },
    { SPR_UFMTRST0, 23, 10, NULL, S_UFMTRST0_IDLE3, 0 },
    { SPR_UFMTRST0, 24, 10, NULL, S_UFMTRST0_IDLE4, 0 },
    { SPR_UFMTRST0, 25, 10, NULL, S_UFMTRST0_IDLE1, 0 },
    { SPR_UCINFST0, 8, -1, NULL, S_UCINFST0_STND, 0 },
    { SPR_UCINFST0, 0, 6, NULL, S_UCINFST0_RUN2, 2 },
    { SPR_UCINFST0, 1, 6, NULL, S_UCINFST0_RUN3, 2 },
    { SPR_UCINFST0, 2, 6, NULL, S_UCINFST0_RUN4, 2 },
    { SPR_UCINFST0, 3, 6, NULL, S_UCINFST0_RUN5, 2 },
    { SPR_UCINFST0, 4, 6, NULL, S_UCINFST0_RUN6, 2 },
    { SPR_UCINFST0, 5, 6, NULL, S_UCINFST0_RUN7, 2 },
    { SPR_UCINFST0, 6, 6, NULL, S_UCINFST0_RUN8, 2 },
    { SPR_UCINFST0, 7, 6, NULL, S_UCINFST0_RUN1, 2 },
    { SPR_UCINFST0, 8, 10, NULL, S_UCINFST0_IDLE2, 0 },
    { SPR_UCINFST0, 9, 10, NULL, S_UCINFST0_IDLE3, 0 },
    { SPR_UCINFST0, 10, 10, NULL, S_UCINFST0_IDLE1, 0 },
    { SPR_UFSPBST0, 4, 20, A_Look, S_UFSPBST0_STND, 0 },
    { SPR_UFSPBST0, 0, 6, A_Chase, S_UFSPBST0_RUN2, 2 },
    { SPR_UFSPBST0, 1, 6, NULL, S_UFSPBST0_RUN3, 2 },
    { SPR_UFSPBST0, 2, 6, NULL, S_UFSPBST0_RUN1, 2 },
    { SPR_UFSPBST0, 3, 6, A_Attack, S_UFSPBST0_STND, 3 },
    { SPR_UFRATST0, 0, -1, NULL, S_UFRATST0_STND, 0 },
    { SPR_UFRATST0, 0, 6, NULL, S_UFRATST0_RUN2, 2 },
    { SPR_UFRATST0, 1, 6, NULL, S_UFRATST0_RUN3, 2 },
    { SPR_UFRATST0, 2, 6, NULL, S_UFRATST0_RUN1, 2 },
    { SPR_UFSKTST0, 0, 20, A_Look, S_UFSKTST0_STND, 0 },
    { SPR_UFSKTST0, 0, 6, A_Chase, S_UFSKTST0_RUN2, 2 },
    { SPR_UFSKTST0, 1, 6, NULL, S_UFSKTST0_RUN3, 2 },
    { SPR_UFSKTST0, 2, 6, NULL, S_UFSKTST0_RUN1, 2 },
    { SPR_UFTHNST0, 0, 20, A_Look, S_UFTHNST0_STND, 0 },
    { SPR_UFTHNST0, 0, 6, A_Chase, S_UFTHNST0_RUN2, 2 },
    { SPR_UFTHNST0, 1, 6, NULL, S_UFTHNST0_RUN3, 2 },
    { SPR_UFTHNST0, 2, 6, NULL, S_UFTHNST0_RUN1, 2 },
    { SPR_UFTHNST0, 3, 6, A_Attack, S_UFTHNST0_SHOOT2, 3 },
    { SPR_UFTHNST0, 4, 6, NULL, S_UFTHNST0_SHOOT3, 3 },
    { SPR_UFTHNST0, 5, 6, NULL, S_UFTHNST0_SHOOT4, 3 },
    { SPR_UFTHNST0, 6, 6, NULL, S_UFTHNST0_STND, 3 },
    { SPR_UFPHTST0, 0, 20, A_Look, S_UFPHTST0_STND, 0 },
    { SPR_UFPHTST0, 0, 6, A_Chase, S_UFPHTST0_RUN2, 2 },
    { SPR_UFPHTST0, 1, 6, NULL, S_UFPHTST0_RUN3, 2 },
    { SPR_UFPHTST0, 2, 6, NULL, S_UFPHTST0_RUN1, 2 },
    { SPR_UFPHTST0, 3, 6, A_Attack, S_UFPHTST0_STND, 3 },
    { SPR_UFFLKST0, 0, 20, A_Look, S_UFFLKST0_STND, 0 },
    { SPR_UFFLKST0, 0, 3, A_Chase, S_UFFLKST0_RUN2, 2 },
    { SPR_UFFLKST0, 1, 3, NULL, S_UFFLKST0_RUN3, 2 },
    { SPR_UFFLKST0, 2, 3, NULL, S_UFFLKST0_RUN4, 2 },
    { SPR_UFFLKST0, 3, 3, NULL, S_UFFLKST0_RUN5, 2 },
    { SPR_UFFLKST0, 4, 3, NULL, S_UFFLKST0_RUN6, 2 },
    { SPR_UFFLKST0, 5, 3, NULL, S_UFFLKST0_RUN7, 2 },
    { SPR_UFFLKST0, 6, 3, NULL, S_UFFLKST0_RUN8, 2 },
    { SPR_UFFLKST0, 7, 3, NULL, S_UFFLKST0_RUN1, 2 },
    { SPR_UFFLKST0, 8, 6, A_Attack, S_UFFLKST0_SHOOT2, 3 },
    { SPR_UFFLKST0, 9, 6, NULL, S_UFFLKST0_SHOOT3, 3 },
    { SPR_UFFLKST0, 10, 6, NULL, S_UFFLKST0_STND, 3 },
    { SPR_UFTRTST0, 0, 20, A_Look, S_UFTRTST0_STND, 0 },
    { SPR_UFTRTST0, 0, 6, A_Chase, S_UFTRTST0_RUN1, 2 },
    { SPR_UFFARST0, 0, 20, A_Look, S_UFFARST0_STND, 0 },
    { SPR_UFFARST0, 0, 6, A_Chase, S_UFFARST0_RUN2, 2 },
    { SPR_UFFARST0, 1, 6, NULL, S_UFFARST0_RUN3, 2 },
    { SPR_UFFARST0, 2, 6, NULL, S_UFFARST0_RUN1, 2 },
    { SPR_UFFARST0, 3, 6, A_Attack, S_UFFARST0_SHOOT2, 3 },
    { SPR_UFFARST0, 4, 6, NULL, S_UFFARST0_STND, 3 },
    { SPR_UFSKBST0, 0, 20, A_Look, S_UFSKBST0_STND, 0 },
    { SPR_UFSKBST0, 0, 6, A_Chase, S_UFSKBST0_RUN1, 2 },
    { SPR_UFOUTST0, 0, 20, A_Look, S_UFOUTST0_STND, 0 },
    { SPR_UFOUTST0, 0, 6, A_Chase, S_UFOUTST0_RUN1, 2 },
    { SPR_UFSWVST0, 0, 20, A_Look, S_UFSWVST0_STND, 0 },
    { SPR_UFSWVST0, 0, 6, A_Chase, S_UFSWVST0_RUN2, 2 },
    { SPR_UFSWVST0, 1, 6, NULL, S_UFSWVST0_RUN3, 2 },
    { SPR_UFSWVST0, 2, 6, NULL, S_UFSWVST0_RUN1, 2 },
    { SPR_UCWCOST0, 0, 20, A_Look, S_UCWCOST0_STND, 0 },
    { SPR_UCWCOST0, 0, 6, A_Chase, S_UCWCOST0_RUN2, 2 },
    { SPR_UCWCOST0, 1, 6, NULL, S_UCWCOST0_RUN3, 2 },
    { SPR_UCWCOST0, 2, 6, NULL, S_UCWCOST0_RUN4, 2 },
    { SPR_UCWCOST0, 3, 6, NULL, S_UCWCOST0_RUN1, 2 },
    { SPR_UFPHRST0, 0, -1, NULL, S_UFPHRST0_STND, 0 },
    { SPR_UFPHRST0, 0, 6, NULL, S_UFPHRST0_RUN2, 2 },
    { SPR_UFPHRST0, 1, 6, NULL, S_UFPHRST0_RUN3, 2 },
    { SPR_UFPHRST0, 2, 6, NULL, S_UFPHRST0_RUN1, 2 },
    { SPR_UFBAMST0, 0, -1, NULL, S_UFBAMST0_STND, 0 },
    { SPR_UFBAMST0, 0, 6, NULL, S_UFBAMST0_RUN1, 2 },
    { SPR_NFHQT1L0, 0, -1, NULL, S_NFHQT1L0_STND, 0 },
    { SPR_NFHQT2L0, 0, -1, NULL, S_NFHQT2L0_STND, 0 },
    { SPR_NFHQT3L0, 0, -1, NULL, S_NFHQT3L0_STND, 0 },
    { SPR_NFUTF1L0, 0, -1, NULL, S_NFUTF1L0_STND, 0 },
    { SPR_NFUTF2L0, 0, -1, NULL, S_NFUTF2L0_STND, 0 },
    { SPR_NFVCY1L0, 0, -1, NULL, S_NFVCY1L0_STND, 0 },
    { SPR_NFVCY2L0, 0, -1, NULL, S_NFVCY2L0_STND, 0 },
    { SPR_NFHSP1L0, 0, -1, NULL, S_NFHSP1L0_STND, 0 },
    { SPR_NFREP1L0, 0, -1, NULL, S_NFREP1L0_STND, 0 },
    { SPR_NFPHF1L0, 0, -1, NULL, S_NFPHF1L0_STND, 0 },
    { SPR_NFPHF2L0, 0, -1, NULL, S_NFPHF2L0_STND, 0 },
    { SPR_NCCAM1L0, 0, -1, NULL, S_NCCAM1L0_STND, 0 },
    { SPR_NCLNC1L0, 0, -1, NULL, S_NCLNC1L0_STND, 0 },
    { SPR_NCPOW1L0, 0, -1, NULL, S_NCPOW1L0_STND, 0 },
    { SPR_NFRRM1L0, 0, -1, NULL, S_NFRRM1L0_STND, 0 },
    { SPR_NCSBH1L0, 0, -1, NULL, S_NCSBH1L0_STND, 0 },
    { SPR_NCSBV1L0, 0, -1, NULL, S_NCSBV1L0_STND, 0 },
    { SPR_NCSBC1L0, 0, -1, NULL, S_NCSBC1L0_STND, 0 },
    { SPR_NFGDT1L0, 0, 20, A_Look, S_NFGDT1L0_STND, 0 },
    { SPR_NFAGT1L0, 0, 20, A_Look, S_NFAGT1L0_STND, 0 },
    { SPR_NFAAR1L0, 0, 20, A_Look, S_NFAAR1L0_STND, 0 },
    { SPR_UCFCNST0, 6, 1, A_Attack, S_UCFCNST0_STND, 3 },
    { SPR_UCHFRST0, 0, 1, A_Attack, S_UCHFRST0_STND, 3 },
    { SPR_UFSKTST0, 0, 1, A_Attack, S_UFSKTST0_STND, 3 },
    { SPR_UFTRTST0, 0, 1, A_Attack, S_UFTRTST0_STND, 3 },
    { SPR_UFSKBST0, 0, 1, A_Attack, S_UFSKBST0_STND, 3 },
    { SPR_UFOUTST0, 0, 1, A_Attack, S_UFOUTST0_STND, 3 },
    { SPR_UFSWVST0, 0, 1, A_Attack, S_UFSWVST0_STND, 3 },
    { SPR_UCWCOST0, 0, 1, A_Attack, S_UCWCOST0_STND, 3 },
    { SPR_NFGDT1L0, 0, 1, A_Attack, S_NFGDT1L0_STND, 3 },
    { SPR_NFAGT1L0, 0, 1, A_Attack, S_NFAGT1L0_STND, 3 },
    { SPR_NFAAR1L0, 0, 1, A_Attack, S_NFAAR1L0_STND, 3 },
};

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {
    { 0 },
    { // MT_FG_CONSTRUCTION_CREW
        .doomednum = ACTOR_FG_CONSTRUCTION_CREW, .spawnstate = S_UCFCNST0_STND, .spawnhealth = 100,
        .seestate = S_UCFCNST0_RUN1, .speed = 6,
        .missilestate = S_UCFCNST0_FIRE, .damage = 20,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_FREIGHTER
        .doomednum = ACTOR_FG_GROUND_TRANSPORTER, .spawnstate = S_UCFRGST0_STND, .spawnhealth = 750,
        .seestate = S_UCFRGST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER,
    },
    { // MT_FG_HOVER_FREIGHTER
        .doomednum = ACTOR_FG_HOVER_TRANSPORTER, .spawnstate = S_UCHFRST0_STND, .spawnhealth = 500,
        .seestate = S_UCHFRST0_RUN1, .speed = 5,
        .missilestate = S_UCHFRST0_FIRE, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_HARVESTER|MF_ATTACK,
    },
    { // MT_FG_RAIDER
        .doomednum = ACTOR_FG_RAIDER, .spawnstate = S_UFRADST0_STND, .spawnhealth = 100,
        .seestate = S_UFRADST0_RUN1, .speed = 5,
        .missilestate = S_UFRADST0_SHOOT1, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_MERCENARY
        .doomednum = ACTOR_FG_MERCENARY, .spawnstate = S_UFMRCST0_STND, .spawnhealth = 125,
        .seestate = S_UFMRCST0_RUN1, .speed = 5,
        .missilestate = S_UFMRCST0_SHOOT1, .damage = 11,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SNIPER
        .doomednum = ACTOR_FG_SNIPER, .spawnstate = S_UFSNPST0_STND, .spawnhealth = 100,
        .seestate = S_UFSNPST0_RUN1, .speed = 5,
        .missilestate = S_UFSNPST0_SHOOT1, .damage = 150,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SCOUT
        .doomednum = ACTOR_FG_SCOUT, .spawnstate = S_UFSCTST0_STND, .spawnhealth = 66,
        .seestate = S_UFSCTST0_RUN1, .speed = 6,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MEDIC
        .doomednum = ACTOR_FG_MEDIC, .spawnstate = S_UFMEDST0_STND, .spawnhealth = 66,
        .seestate = S_UFMEDST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_SABOTEUR
        .doomednum = ACTOR_FG_SABOTEUR, .spawnstate = S_UFSABST0_STND, .spawnhealth = 100,
        .seestate = S_UFSABST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MECHANIC
        .doomednum = ACTOR_FG_MECHANIC, .spawnstate = S_UFMECST0_STND, .spawnhealth = 66,
        .seestate = S_UFMECST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MARTYR
        .doomednum = ACTOR_FG_SUICIDE_NUKER, .spawnstate = S_UFMTRST0_STND, .spawnhealth = 100,
        .seestate = S_UFMTRST0_RUN1, .speed = 5,
        .missilestate = S_UFMTRST0_SHOOT1, .damage = 180,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SPY
        .doomednum = ACTOR_FG_SPY, .spawnstate = S_UCINFST0_STND, .spawnhealth = 66,
        .seestate = S_UCINFST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_SPYDER_BIKE
        .doomednum = ACTOR_FG_SPYDER_BIKE, .spawnstate = S_UFSPBST0_STND, .spawnhealth = 133,
        .seestate = S_UFSPBST0_RUN1, .speed = 7,
        .missilestate = S_UFSPBST0_SHOOT1, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_IFV
        .doomednum = ACTOR_FG_IFV, .spawnstate = S_UFRATST0_STND, .spawnhealth = 200,
        .seestate = S_UFRATST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_MEDIUM_TANK
        .doomednum = ACTOR_FG_MEDIUM_TANK, .spawnstate = S_UFSKTST0_STND, .spawnhealth = 133,
        .seestate = S_UFSKTST0_RUN1, .speed = 4,
        .missilestate = S_UFSKTST0_FIRE, .damage = 14,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_TANK_HUNTER
        .doomednum = ACTOR_FG_TANK_HUNTER, .spawnstate = S_UFTHNST0_STND, .spawnhealth = 150,
        .seestate = S_UFTHNST0_RUN1, .speed = 4,
        .missilestate = S_UFTHNST0_SHOOT1, .damage = 60,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_PHASE_TANK
        .doomednum = ACTOR_FG_PHASE_TANK, .spawnstate = S_UFPHTST0_STND, .spawnhealth = 166,
        .seestate = S_UFPHTST0_RUN1, .speed = 4,
        .missilestate = S_UFPHTST0_SHOOT1, .damage = 30,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_MAD
        .doomednum = ACTOR_FG_MAD, .spawnstate = S_UFFLKST0_STND, .spawnhealth = 100,
        .seestate = S_UFFLKST0_RUN1, .speed = 4,
        .missilestate = S_UFFLKST0_SHOOT1, .damage = 8,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_TRIPLE_RAIL_TANK
        .doomednum = ACTOR_FG_TRIPLE_RAIL_TANK, .spawnstate = S_UFTRTST0_STND, .spawnhealth = 200,
        .seestate = S_UFTRTST0_RUN1, .speed = 4,
        .missilestate = S_UFTRTST0_FIRE, .damage = 24,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SPA
        .doomednum = ACTOR_FG_SPA, .spawnstate = S_UFFARST0_STND, .spawnhealth = 133,
        .seestate = S_UFFARST0_RUN1, .speed = 4,
        .missilestate = S_UFFARST0_SHOOT1, .damage = 30,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_SKY_BIKE
        .doomednum = ACTOR_FG_SKY_BIKE, .spawnstate = S_UFSKBST0_STND, .spawnhealth = 100,
        .seestate = S_UFSKBST0_RUN1, .speed = 6,
        .missilestate = S_UFSKBST0_FIRE, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY,
    },
    { // MT_FG_OUTRIDER
        .doomednum = ACTOR_FG_OUTRIDER, .spawnstate = S_UFOUTST0_STND, .spawnhealth = 200,
        .seestate = S_UFOUTST0_RUN1, .speed = 5,
        .missilestate = S_UFOUTST0_FIRE, .damage = 20,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK|MF_FLY,
    },
    { // MT_FG_SHOCKWAVE
        .doomednum = ACTOR_FG_SHOCKWAVE, .spawnstate = S_UFSWVST0_STND, .spawnhealth = 166,
        .seestate = S_UFSWVST0_RUN1, .speed = 4,
        .missilestate = S_UFSWVST0_FIRE, .damage = 17,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_CONTAMINATOR
        .doomednum = ACTOR_FG_CONTAMINATOR, .spawnstate = S_UCWCOST0_STND, .spawnhealth = 166,
        .seestate = S_UCWCOST0_RUN1, .speed = 3,
        .missilestate = S_UCWCOST0_FIRE, .damage = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_UNDERGROUND_TUNNEL
        .doomednum = ACTOR_FG_UNDERGROUND_TUNNEL, .spawnstate = S_UFPHRST0_STND, .spawnhealth = 150,
        .seestate = S_UFPHRST0_RUN1, .speed = 5,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_BASE_MOVER
        .doomednum = ACTOR_FG_BASE_MOVER, .spawnstate = S_UFBAMST0_STND, .spawnhealth = 500,
        .seestate = S_UFBAMST0_RUN1, .speed = 3,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .radius = 16, .height = 32, .mass = 100,
        .flags = MF_SELECTABLE|MF_MOBILE|MF_RENDERABLE,
    },
    { // MT_FG_HQ1
        .doomednum = ACTOR_FG_HEADQUARTERS_1, .spawnstate = S_NFHQT1L0_STND, .spawnhealth = 1200,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_RESOURCE_BASE,
    },
    { // MT_FG_HQ2
        .doomednum = ACTOR_FG_HEADQUARTERS_2, .spawnstate = S_NFHQT2L0_STND, .spawnhealth = 2400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HQ3
        .doomednum = ACTOR_FG_HEADQUARTERS_3, .spawnstate = S_NFHQT3L0_STND, .spawnhealth = 3600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BARRACKS
        .doomednum = ACTOR_FG_TRAINING_FACILITY_1, .spawnstate = S_NFUTF1L0_STND, .spawnhealth = 750,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_ADV_BARRACKS
        .doomednum = ACTOR_FG_TRAINING_FACILITY_2, .spawnstate = S_NFUTF2L0_STND, .spawnhealth = 1500,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_VEHICLE_FACTORY
        .doomednum = ACTOR_FG_VEHICLE_FACTORY_1, .spawnstate = S_NFVCY1L0_STND, .spawnhealth = 1000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_ADV_VEHICLE_FACTORY
        .doomednum = ACTOR_FG_VEHICLE_FACTORY_2, .spawnstate = S_NFVCY2L0_STND, .spawnhealth = 2000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_HOVER_FACTORY
        .doomednum = ACTOR_FG_HOVER_FACTORY, .spawnstate = S_NFHSP1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REPAIR_BAY
        .doomednum = ACTOR_FG_REPAIR_BAY, .spawnstate = S_NFREP1L0_STND, .spawnhealth = 600,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_1
        .doomednum = ACTOR_FG_PHASE_FACTORY_1, .spawnstate = S_NFPHF1L0_STND, .spawnhealth = 1000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_PHASE_FACTORY_2
        .doomednum = ACTOR_FG_PHASE_FACTORY_2, .spawnstate = S_NFPHF2L0_STND, .spawnhealth = 2000,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_CAMERA_TOWER
        .doomednum = ACTOR_FG_CAMERA_TOWER, .spawnstate = S_NCCAM1L0_STND, .spawnhealth = 150,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_LIFE_PLANT
        .doomednum = ACTOR_FG_LIFE_PLANT, .spawnstate = S_NCLNC1L0_STND, .spawnhealth = 1300,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_POWER_PLANT
        .doomednum = ACTOR_FG_POWER_PLANT, .spawnstate = S_NCPOW1L0_STND, .spawnhealth = 1450,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_REFINERY
        .doomednum = ACTOR_FG_REFINERY, .spawnstate = S_NFRRM1L0_STND, .spawnhealth = 800,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_H
        .doomednum = ACTOR_FG_SMALL_HORIZONTAL_BRIDGE, .spawnstate = S_NCSBH1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_V
        .doomednum = ACTOR_FG_SMALL_VERTICAL_BRIDGE, .spawnstate = S_NCSBV1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_BRIDGE_C
        .doomednum = ACTOR_FG_SMALL_CENTRE_BRIDGE, .spawnstate = S_NCSBC1L0_STND, .spawnhealth = 400,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE,
    },
    { // MT_FG_GUARD_TOWER
        .doomednum = ACTOR_FG_GUARD_TOWER, .spawnstate = S_NFGDT1L0_STND, .spawnhealth = 400,
        .missilestate = S_NFGDT1L0_FIRE, .damage = 10,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_ADV_GUARD_TOWER
        .doomednum = ACTOR_FG_ADVANCED_GUARD_TOWER, .spawnstate = S_NFAGT1L0_STND, .spawnhealth = 550,
        .missilestate = S_NFAGT1L0_FIRE, .damage = 13,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
    { // MT_FG_AA_SITE
        .doomednum = ACTOR_FG_AA_SITE, .spawnstate = S_NFAAR1L0_STND, .spawnhealth = 600,
        .missilestate = S_NFAAR1L0_FIRE, .damage = 40,
        .deathstate = S_NULL, .xdeathstate = S_NULL,
        .flags = MF_SELECTABLE|MF_RENDERABLE|MF_ATTACK,
    },
};

const gameinfo_t game_info = {
    sprnames, NUMSPRITES, states, NUMSTATES, mobjinfo, NUMMOBJTYPES,
    S_NULL, RTS_STATE_COORDS_GROUND_OFFSET,
    { .style = SELECTION_STYLE_BRACKETS },
    NULL,
    .right_click_orders = false,
};
