/* Extract the retail sight trees, retaining traversal and subtree boundaries. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static uint8_t exe[566272];
static struct { int x, y, depth, end, parent; } nodes[2048];
static int count;

static int32_t word(uint32_t address) {
    if (address < 0x46d000 || address > 0x484dfc) {
        fprintf(stderr, "invalid DC.EXE data address %08x\n", address);
        exit(1);
    }
    const uint8_t *p = exe + address - 0x46d000 + 0x6aa00;
    return (int32_t)((uint32_t)p[0] | (uint32_t)p[1] << 8 |
                     (uint32_t)p[2] << 16 | (uint32_t)p[3] << 24);
}

static void walk(uint32_t address, int depth, int parent) {
    if (count == 2048 || depth > 10) exit(1);
    int i = count++;
    nodes[i].x = word(address);
    nodes[i].y = word(address + 4);
    nodes[i].depth = depth;
    nodes[i].parent = parent;
    int children = word(address + 8) / 4 + 1;
    if (children < 0 || children > 8 || abs(nodes[i].x) > 10 || abs(nodes[i].y) > 10)
        exit(1);
    for (int child = children - 1; child >= 0; --child)
        walk((uint32_t)word(address + 12 + child * 4), depth + 1, i);
    nodes[i].end = count;
}

int main(int argc, char **argv) {
    if (argc != 2) return 1;
    FILE *file = fopen(argv[1], "rb");
    if (!file) return 1;
    size_t size = fread(exe, 1, sizeof(exe), file);
    int extra = fgetc(file);
    fclose(file);
    if (size != sizeof(exe) || extra != EOF || word(0x483fc0) != 0x477128) return 1;
    int roots[11] = {0};
    for (int radius = 1; radius <= 10; ++radius) {
        roots[radius - 1] = count;
        walk((uint32_t)word(0x483fbc + radius * 4), 0, -1);
        fprintf(stderr, "DC sight radius %d: %d cells\n", radius, count - roots[radius - 1]);
    }
    roots[10] = count;
    /* Verify whether the ten authored trees can share their largest tree. */
    for (int radius = 1; radius <= 10; ++radius) {
        int matched = 0;
        for (int j = roots[9]; j < roots[10]; ++j) {
            int distance = nodes[j].x * nodes[j].x + nodes[j].y * nodes[j].y;
            int parent = nodes[j].parent;
            if (parent >= 0 && distance <= nodes[parent].x * nodes[parent].x + nodes[parent].y * nodes[parent].y)
                return 1;
            if (distance > radius * radius) continue;
            int i;
            for (i = roots[radius - 1]; i < roots[radius]; ++i)
                if (nodes[i].x == nodes[j].x && nodes[i].y == nodes[j].y) break;
            if (i == roots[radius] || nodes[i].depth != nodes[j].depth) return 1;
            int p = nodes[i].parent;
            if (p >= 0 && (parent < 0 || nodes[p].x != nodes[parent].x || nodes[p].y != nodes[parent].y)) {
                fprintf(stderr, "radius %d has a different parent at (%d,%d)\n", radius, nodes[i].x, nodes[i].y);
                return 1;
            }
            matched++;
        }
        if (matched != roots[radius] - roots[radius - 1]) return 1;
    }
    puts("/* Generated by tools/dc_sight_gen from DC.EXE table 0x483fbc. */\n#ifndef __P_SIGHT_DATA__\n#define __P_SIGHT_DATA__\n");
    puts("static const struct {\n    ivec2_t offset;\n    uint8_t depth;\n    uint16_t end;\n} sightnodes[] = {");
    for (int i = roots[9]; i < count; ++i)
        printf("    {{%d, %d}, %d, %d},\n", nodes[i].x, nodes[i].y, nodes[i].depth, nodes[i].end - roots[9]);
    puts("};\n\n#endif");
    return ferror(stdout) ? 1 : 0;
}
