/* Offline DAT balance importer. Runtime balance remains committed C literals. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned u16(const unsigned char *p) { return p[0] | p[1]<<8; }
static unsigned u32(const unsigned char *p) { return u16(p) | u16(p+2)<<16; }
static unsigned char *load(const char *root, const char *name, long *size) {
    char path[2048]; snprintf(path,sizeof(path),"%s/%s",root,name);
    FILE *f=fopen(path,"rb"); if(!f) { perror(path); exit(1); }
    fseek(f,0,SEEK_END); *size=ftell(f); rewind(f);
    unsigned char *p=malloc((size_t)*size+1);
    if(!p || fread(p,1,(size_t)*size,f)!=(size_t)*size) exit(1);
    fclose(f); p[*size]=0; return p;
}
int main(int argc,char **argv) {
    if(argc!=2&&argc!=3) { fprintf(stderr,"usage: %s native-directory [upgrades]\n",argv[0]); return 2; }
    long n,tn; unsigned char *d=load(argv[1],"arr/units.dat",&n);
    unsigned char *t=load(argv[1],"rez/stat_txt.tbl",&tn);
    long wn; unsigned char *weapons=load(argv[1],"arr/weapons.dat",&wn);
    if (wn % 42) return 1;
    int nw=(int)wn/42;
    if((n!=19192 && n!=19876) || tn<458 || u16(t)<228) return 1;
    int bw=n==19876;
    if(argc==3) {
        /* upgrades.dat: nine u16 columns, then race and repeats (u8), 46 rows. */
        long un; unsigned char *g=load(argv[1],"arr/upgrades.dat",&un);
        if(un!=920) return 1;
        puts("/* Generated by tools/sc_catalog from retail upgrades.dat + stat_txt.tbl. */");
        for(int i=0;i<46;i++) {
            unsigned label=u16(g+8*92+2*i);
            if(!label) continue;
            unsigned off=u16(t+label*2); if(label>u16(t)||off>=(unsigned)tn) return 1;
            printf("SC_UPGRADE(%d, \"%s\", %u, %u, %u, %u, %u, %u, %u, %u, %u)\n",i,(const char *)t+off,
                u16(g+2*i),u16(g+92+2*i),u16(g+184+2*i),u16(g+276+2*i),u16(g+368+2*i),u16(g+460+2*i),
                u16(g+644+2*i),g[828+i],g[874+i]);
        }
        free(g); free(d); free(t); free(weapons); return 0;
    }
    /* Parallel columns in Stargus's units_dat.ksy, in disk order. */
    const int widths[]={1,2,2,2,4,1,1,2,4,1,1,1,1,1,1,1,1,1,bw,1,bw,1,4,1,1,1,1,1,1,2,2,2,2,2,2,2,4,4,8,2,2,2,2,2,1,1,1,1,1,2,2,2,bw,2};
    int offsets[54],at=0;
    for(int f=0;f<54;f++) { offsets[f]=at; int c=(f==3||f==37)?96:(f==29||(f>=32&&f<=35))?106:228; at+=widths[f]*c; }
    if(at!=n) { fprintf(stderr,"DAT span %d != %ld\n",at,n); return 1; }
    puts("/* Generated by tools/sc_catalog from retail units.dat + weapons.dat + stat_txt.tbl. */");
    for(int i=0;i<228;i++) {
        unsigned off=u16(t+2+i*2); if(off>=(unsigned)tn) return 1;
        printf("SC_UNIT(%d, \"",i);
        for(unsigned p=off;p<(unsigned)tn && t[p];p++) {
            unsigned c=t[p]; if(c<32) continue;
            if(c=='"'||c=='\\') putchar('\\');
            if(c>=127) printf("\\%03o",c); else putchar((int)c);
        }
        unsigned weapon=d[offsets[17]+i];
        unsigned damage=0,range=0,cooldown=0,upgrade=255,bonus=0;
        if (weapon < (unsigned)nw) {
            range=u32(weapons+13*nw+4*weapon);
            upgrade=weapons[17*nw+weapon];
            damage=u16(weapons+28*nw+2*weapon);
            bonus=u16(weapons+30*nw+2*weapon);
            cooldown=weapons[32*nw+weapon];
        }
        printf("\", %u, 0x%08xu, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u)\n",
            u32(d+offsets[8]+4*i)>>8, u32(d+offsets[22]+4*i),
            u16(d+offsets[36]+4*i),u16(d+offsets[36]+4*i+2),
            d[offsets[24]+i],d[offsets[28]+i],d[offsets[44]+i],
            u16(d+offsets[40]+2*i),u16(d+offsets[41]+2*i),u16(d+offsets[39]+2*i),
            u16(d+offsets[42]+2*i),damage,range,cooldown,
            d[offsets[45]+i],d[offsets[46]+i],
            d[offsets[27]+i],d[offsets[25]+i],upgrade,bonus,u16(d+offsets[49]+2*i),u16(d+offsets[50]+2*i));
    }
    free(d); free(t); free(weapons); return 0;
}
