/* Offline DAT balance importer. Runtime balance remains committed C literals. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned u16(const unsigned char *p) { return p[0] | p[1]<<8; }
static unsigned u32(const unsigned char *p) { return u16(p) | u16(p+2)<<16; }
static unsigned char *load(const char *root, const char *name, long *size) {
    char path[2048]; snprintf(path,sizeof(path),"%s/%s",root,name);
    FILE *f=fopen(path,"rb"); if(!f) { perror(path); exit(1); }
    fseek(f,0,SEEK_END); *size=ftell(f); rewind(f);
    unsigned char *p=malloc((size_t)*size+1);
    if(!p || fread(p,1,(size_t)*size,f)!=(size_t)*size) exit(1);
    fclose(f); p[*size]=0; return p;
}
/* A stat_txt.tbl string (1-based label) as a C literal; "" for none. */
static void put_label(const unsigned char *t,long tn,unsigned label) {
    unsigned off=label&&label<=u16(t)?u16(t+label*2):(unsigned)tn;
    putchar('"');
    for(unsigned p=off;p<(unsigned)tn && t[p];p++) {
        unsigned c=t[p]; if(c<32) continue;
        if(c=='"'||c=='\\') putchar('\\');
        if(c>=127) printf("\\%03o",c); else putchar((int)c);
    }
    putchar('"');
}
/* PyMS IScriptBIN.py opcode argument lengths; 255 is a counted list. */
static const unsigned char oplen[69]={
    2,2,1,1,2,1,2,2,4,4,2,2,0,4,4,4,4,4,2,4,4,3,0,1,2,255,4,0,255,0,3,1,
    1,0,1,1,1,1,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,2,0,2,1,2,4,6,6,2,0,2,2,1,4,0,0
};
/* One pass of an IScript animation (header entry `anim`): pixels of move
 * (0x29) and frames of wait (0x05) until the path repeats or ends. */
typedef struct { unsigned moved, waited; } pass_t;
static pass_t script_pass(const unsigned char *s,long size,unsigned id,unsigned anim) {
    pass_t out={0,0};
    long at=size>=6&&u32(s+2)==0?u16(s):0;
    for(;at+4<=size;at+=4) {
        unsigned key=u16(s+at),off=u16(s+at+2);
        if(key==65535) return out;
        if(key!=id) continue;
        unsigned type=off+8<size?s[off+4]:0,count=type<=1?2:type==2?4:type<=13?14:type<=15?16:type<=21?22:
                       type==23?24:type==24?26:type<=29?28:0;
        if(anim>=count||off+8+count*2>size||memcmp(s+off,"SCPE",4)) return out;
        long pc=u16(s+off+8+anim*2),seen[256],stack[16]; int n=0,sp=0;
        while(pc>0&&pc<size&&n<256) {
            for(int i=0;i<n;i++) if(seen[i]==pc) return out;
            seen[n++]=pc;
            unsigned op=s[pc++]; if(op>=sizeof(oplen)) return out;
            long len=oplen[op];
            if(len==255) len=pc<size?1+s[pc]*2:size;
            if(pc+len>size) return out;
            const unsigned char *arg=s+pc; pc+=len;
            if(op==0x29) out.moved+=arg[0];
            else if(op==0x05) out.waited+=arg[0];
            else if(op==0x07) pc=u16(arg);
            else if(op==0x35&&sp<16) { stack[sp++]=pc; pc=u16(arg); }
            else if(op==0x36&&sp) pc=stack[--sp];
            else if(op==0x16) return out;
        }
        return out;
    }
    return out;
}
int main(int argc,char **argv) {
    if(argc!=2&&argc!=3) { fprintf(stderr,"usage: %s native-directory [upgrades|weapons|techs]\n",argv[0]); return 2; }
    long n,tn; unsigned char *d=load(argv[1],"arr/units.dat",&n);
    unsigned char *t=load(argv[1],"rez/stat_txt.tbl",&tn);
    if((n!=19192 && n!=19876) || tn<458 || u16(t)<228) return 1;
    int bw=n==19876;
    const char *mode=argc==3?argv[2]:"units";
    if(!strcmp(mode,"upgrades")) {
        /* upgrades.dat: nine u16 columns, then race and repeats (u8), 46 rows. */
        long un; unsigned char *g=load(argv[1],"arr/upgrades.dat",&un);
        if(un!=920) return 1;
        puts("/* Generated by tools/sc_catalog from retail upgrades.dat + stat_txt.tbl. */");
        for(int i=0;i<46;i++) {
            unsigned label=u16(g+8*92+2*i);
            if(!label) continue;
            printf("SC_UPGRADE(%d, ",i); put_label(t,tn,label);
            printf(", %u, %u, %u, %u, %u, %u, %u, %u, %u)\n",
                u16(g+2*i),u16(g+92+2*i),u16(g+184+2*i),u16(g+276+2*i),u16(g+368+2*i),u16(g+460+2*i),
                u16(g+644+2*i),g[828+i],g[874+i]);
        }
        return 0;
    }
    if(!strcmp(mode,"weapons")) {
        /* PyMS weapons.dat: parallel columns at byte offset x N. Target flags 7,
         * ranges 9/13 (pixels), damage upgrade 17, damage type 18, behavior 19,
         * explosion 21, splash radii 22/24/26, damage 28, bonus 30, cooldown 32
         * (frames) and damage factor 33, the hits of one attack. */
        long wn; unsigned char *w=load(argv[1],"arr/weapons.dat",&wn);
        if(wn%42) return 1;
        int nw=(int)wn/42;
        puts("/* Generated by tools/sc_catalog from retail weapons.dat + stat_txt.tbl. */");
        for(int i=0;i<nw;i++) {
            printf("SC_WEAPON(%d, ",i); put_label(t,tn,u16(w+2*i));
            printf(", %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, 0x%03xu)\n",
                u16(w+28*nw+2*i),u16(w+30*nw+2*i),w[32*nw+i],w[33*nw+i],
                w[17*nw+i],w[18*nw+i],w[21*nw+i],w[19*nw+i],
                u32(w+9*nw+4*i),u32(w+13*nw+4*i),
                u16(w+22*nw+2*i),u16(w+24*nw+2*i),u16(w+26*nw+2*i),u16(w+7*nw+2*i));
        }
        return 0;
    }
    if(!strcmp(mode,"techs")) {
        /* techdata.dat, 24 rows: minerals, gas, time, energy (u16), an unknown
         * u32, icon and label (u16), race and an unused byte. */
        long cn; unsigned char *c=load(argv[1],"arr/techdata.dat",&cn);
        if(cn!=432) return 1;
        puts("/* Generated by tools/sc_catalog from retail techdata.dat + stat_txt.tbl. */");
        for(int i=0;i<24;i++) {
            printf("SC_TECH(%d, ",i); put_label(t,tn,u16(c+336+2*i));
            printf(", %u, %u, %u, %u, %u, %u)\n",u16(c+2*i),u16(c+48+2*i),u16(c+96+2*i),u16(c+144+2*i),c[384+i],
                u16(c+288+2*i));
        }
        return 0;
    }
    if(strcmp(mode,"units")) return 2;
    long fn; unsigned char *flingy=load(argv[1],"arr/flingy.dat",&fn);
    long sn,in,cn; unsigned char *sprites=load(argv[1],"arr/sprites.dat",&sn);
    unsigned char *images=load(argv[1],"arr/images.dat",&in),*script=load(argv[1],"scripts/iscript.bin",&cn);
    if(fn%15||in%38||sn<772) return 1;
    int nf=(int)fn/15,ni=(int)in/38;
    /* Parallel columns in Stargus's units_dat.ksy, in disk order. */
    const int widths[]={1,2,2,2,4,1,1,2,4,1,1,1,1,1,1,1,1,1,bw,1,bw,1,4,1,1,1,1,1,1,2,2,2,2,2,2,2,4,4,8,2,2,2,2,2,1,1,1,1,1,2,2,2,bw,2};
    int offsets[54],at=0;
    for(int f=0;f<54;f++) { offsets[f]=at; int c=(f==3||f==37)?96:(f==29||(f>=32&&f<=35))?106:228; at+=widths[f]*c; }
    if(at!=n) { fprintf(stderr,"DAT span %d != %ld\n",at,n); return 1; }
    puts("/* Generated by tools/sc_catalog from retail units.dat, flingy.dat, iscript.bin and stat_txt.tbl. */");
    for(int i=0;i<228;i++) {
        printf("SC_UNIT(%d, ",i); put_label(t,tn,(unsigned)i+1);
        /* Weapons are weapons.dat rows; size is units.dat 26; speed is the
         * flingy.dat top speed in 1/256 pixel per frame, or the walking
         * script's when the flingy's movement control (14N) is iscript (2). */
        unsigned f=d[offsets[0]+i],speed=0;
        if(f<(unsigned)nf) {
            unsigned s=u16(flingy+2*f),image=s<386?u16(sprites+2*s):(unsigned)ni;
            unsigned id=image<(unsigned)ni?u32(images+10*ni+4*image):65535;
            pass_t walk=script_pass(script,cn,id,11);
            speed=flingy[14*nf+f]==2?(walk.waited?walk.moved*256/walk.waited:0):u32(flingy+2*nf+4*f);
        }
        /* Transport space required and provided (47, 48); an add-on's place
         * (37, buildings 106..201 only) is its top-left beside its parent's. */
        unsigned addon_x=i>=106&&i<202?u16(d+offsets[37]+4*(i-106)):0,addon_y=i>=106&&i<202?u16(d+offsets[37]+4*(i-106)+2):0;
        printf(", %u, 0x%08xu, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u)\n",
            u32(d+offsets[8]+4*i)>>8, u32(d+offsets[22]+4*i),
            u16(d+offsets[36]+4*i),u16(d+offsets[36]+4*i+2),
            d[offsets[24]+i],d[offsets[28]+i],d[offsets[44]+i],
            u16(d+offsets[40]+2*i),u16(d+offsets[41]+2*i),u16(d+offsets[39]+2*i),
            u16(d+offsets[42]+2*i),
            d[offsets[45]+i],d[offsets[46]+i],
            d[offsets[27]+i],d[offsets[25]+i],u16(d+offsets[49]+2*i),u16(d+offsets[50]+2*i),
            d[offsets[6]+i]?u16(d+offsets[7]+2*i):0,u16(d+offsets[1]+2*i),
            d[offsets[17]+i],d[offsets[19]+i],d[offsets[26]+i],speed,
            d[offsets[47]+i],d[offsets[48]+i],addon_x,addon_y);
    }
    return 0;
}
