#ifndef OPEN_RTS_DARK_COLONY_TYPES_H
#define OPEN_RTS_DARK_COLONY_TYPES_H

enum {
    MT_DC_BUILDING_BASE = 1000,
    MT_DC_EXCOPOD = MT_DC_BUILDING_BASE,
    MT_DC_BRRKPOD,
    MT_DC_ROBOPOD,
    MT_DC_ROBOPOD2,
    MT_DC_SCNCPOD,
    MT_DC_SCNCPOD2,
    MT_DC_RSCHPOD,
    MT_DC_ALIEN_MINDHIVE,
    MT_DC_ALIEN_WARHIVE,
    MT_DC_ALIEN_BRDRHIVE,
    MT_DC_ALIEN_BRDRHIVE2,
    MT_DC_ALIEN_MINDHIVE2,
    MT_DC_ALIEN_MINDHIVE3,
    MT_DC_ALIEN_RSCHIVE,
    MT_DC_COMMS_DISH,
    MT_DC_CITY_TOWER,
};

#endif
