#ifndef OPEN_RTS_DARK_COLONY_TYPES_H
#define OPEN_RTS_DARK_COLONY_TYPES_H

enum {
    MT_DC_BUILDING_BASE = 1000,
    MT_DC_EXCOPOD = MT_DC_BUILDING_BASE,
    MT_DC_BRRKPOD,
    MT_DC_ROBOPOD,
    MT_DC_ROBOPOD2,
    MT_DC_SCNCPOD,
    MT_DC_SCNCPOD2,
    MT_DC_RSCHPOD,
};

#endif
