#!/usr/bin/env python3
"""Export human city state references from the retail ANIM.DAT load list.

Run after make dc-info-conv:
python3 tools/dc_building_states.py > games/dark-colony/building_states.inc
"""
import json
from pathlib import Path
import subprocess

root = Path('data/DCOLONY')
prefixes = ('EXCOPOD', 'BRRKPOD', 'ROBOPOD', 'ROBOPOD2', 'SCNCPOD', 'SCNCPOD2', 'RSCHPOD')
wanted = {prefix + action + '0' for prefix in prefixes for action in ('SCRCH', 'BURN', 'DIE')}
labels = {}
for name in (root / 'ANIM.DAT').read_text().splitlines():
    path = root / 'ANIMATE' / name.upper()
    if not path.is_file():
        continue
    result = subprocess.run(['build/dc_info_conv', '--labels', str(path)], capture_output=True)
    if result.returncode:
        continue
    for label in json.loads(result.stdout)['labels']:
        if label['name'] in wanted:
            assert label['name'] not in labels, label['name']
            labels[label['name']] = (path, label)
assert labels.keys() == wanted, wanted - labels.keys()
print('/* Generated by tools/dc_building_states.py; pixels and layers remain in FIN. */')
for prefix in prefixes:
    for action in ('SCRCH', 'BURN', 'DIE'):
        name = prefix + action + '0'
        path, label = labels[name]
        data = json.loads(subprocess.check_output(['build/dc_info_conv', '--label', name, str(path)]))
        spr = root / 'SPRITES' / (path.stem + '.SPR')
        cells = int.from_bytes(spr.read_bytes()[2:4], 'little') if spr.exists() else 0
        first, last = label['start'], label['end']
        print(f'DC_BUILDING_LABEL({prefix}, {action}, S_{name}_{first}, S_{name}_{last})')
        elapsed = total = 0
        for frame in data['frames']:
            f = frame['index']
            raw = frame['ticks']
            ticks = (((raw or 15) + 3) * 15 // 100) & 255
            # Main channel is selected after its tick: frame zero is visible
            # for one 66 ms tick before the zero timer advances to frame one.
            total += 1 if action == 'DIE' and f == first else (ticks or 256)
            boundary = (total * 66 * 30 + 500) // 1000
            nextstate = f'S_{name}_{f + 1}' if f < last else ('S_NULL' if action == 'DIE' else f'S_{name}_{first}')
            callback = 'A_None' if action == 'DIE' else 'A_DC_BuildingStand'
            group = 4 if action == 'DIE' else 1
            print(f'DC_BUILDING_STATE(S_{name}_{f}, SPR_{path.stem}, {cells + f}, {boundary - elapsed}, {callback}, {nextstate}, {group})')
            elapsed = boundary
