#include <ctype.h>
#include <dirent.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    char path[256];
    char symbol[128];
    int frames;
} SpriteEntry;

static uint16_t read_u16_le(const unsigned char *p) {
    return (uint16_t)p[0] | ((uint16_t)p[1] << 8);
}

static void die(const char *msg, const char *path) {
    if (path) fprintf(stderr, "dc_info_gen: %s: %s\n", path, msg);
    else fprintf(stderr, "dc_info_gen: %s\n", msg);
    exit(1);
}

static unsigned char *read_file(const char *path, size_t *size_out) {
    FILE *f = fopen(path, "rb");
    if (!f) die(strerror(errno), path);
    if (fseek(f, 0, SEEK_END) != 0) die("seek failed", path);
    long size = ftell(f);
    if (size < 0) die("ftell failed", path);
    if (fseek(f, 0, SEEK_SET) != 0) die("rewind failed", path);
    unsigned char *data = malloc((size_t)size);
    if (!data) die("out of memory", NULL);
    if (size > 0 && fread(data, 1, (size_t)size, f) != (size_t)size) die("read failed", path);
    fclose(f);
    *size_out = (size_t)size;
    return data;
}

static bool ends_with_ci(const char *s, const char *suffix) {
    size_t n = strlen(s), m = strlen(suffix);
    if (n < m) return false;
    for (size_t i = 0; i < m; ++i) {
        if (tolower((unsigned char)s[n - m + i]) != tolower((unsigned char)suffix[i]))
            return false;
    }
    return true;
}

static void sprite_symbol(const char *path, char *out, size_t out_size) {
    const char *base = strrchr(path, '/');
    base = base ? base + 1 : path;
    size_t len = 0;
    snprintf(out, out_size, "SPR_DC_");
    len = strlen(out);
    for (const char *p = base; *p && *p != '.' && len + 1 < out_size; ++p) {
        unsigned char ch = (unsigned char)*p;
        out[len++] = (char)(isalnum(ch) ? toupper(ch) : '_');
    }
    out[len] = '\0';
}

static int compare_sprite_entry(const void *a, const void *b) {
    const SpriteEntry *sa = (const SpriteEntry *)a;
    const SpriteEntry *sb = (const SpriteEntry *)b;
    return strcmp(sa->path, sb->path);
}

static int spr_frame_count(const char *path) {
    size_t size = 0;
    unsigned char *data = read_file(path, &size);
    if (size < 8 + 256 * 3) die("SPR too small", path);
    int count = read_u16_le(data + 2);
    free(data);
    return count;
}

static int find_sprite(const SpriteEntry *sprites, int count, const char *path) {
    for (int i = 0; i < count; ++i) {
        if (strcmp(sprites[i].path, path) == 0) return i;
    }
    fprintf(stderr, "dc_info_gen: missing sprite %s\n", path);
    exit(1);
}

static bool fin_has_label(const char *path, const char *label, int *start_out, int *end_out) {
    size_t size = 0;
    unsigned char *data = read_file(path, &size);
    if (size < 8) die("FIN too small", path);
    int entries = read_u16_le(data + 2);
    int deps = read_u16_le(data + 6);
    size_t off = 8 + (size_t)deps * 8;
    bool found = false;
    for (int i = 0; i < entries && off + 20 <= size; ++i, off += 20) {
        char name[17];
        memcpy(name, data + off, 16);
        name[16] = '\0';
        if (strcmp(name, label) == 0) {
            if (start_out) *start_out = read_u16_le(data + off + 16);
            if (end_out) *end_out = read_u16_le(data + off + 18);
            found = true;
            break;
        }
    }
    free(data);
    return found;
}

static void validate_dark_colony_data(const char *root, const SpriteEntry *sprites, int sprite_count) {
    int gray = find_sprite(sprites, sprite_count, "SPRITES/GRAY.SPR");
    int trsc = find_sprite(sprites, sprite_count, "SPRITES/TRSC.SPR");
    int muza = find_sprite(sprites, sprite_count, "SPRITES/MUZA.SPR");
    if (sprites[gray].frames <= 291) die("GRAY.SPR does not contain expected corpse frames", sprites[gray].path);
    if (sprites[trsc].frames <= 208) die("TRSC.SPR does not contain expected death frames", sprites[trsc].path);
    if (sprites[muza].frames <= 3) die("MUZA.SPR does not contain expected flash frames", sprites[muza].path);

    char fin_path[1024];
    snprintf(fin_path, sizeof(fin_path), "%s/ANIMATE/GRAY.FIN", root);
    int start = 0, end = 0;
    if (!fin_has_label(fin_path, "GRAYDIEA14", &start, &end) || start != 254 || end != 265)
        die("GRAY.FIN missing expected GRAYDIEA14 range", fin_path);
    if (!fin_has_label(fin_path, "GRAYDIE210", &start, &end) || start != 266 || end != 277)
        die("GRAY.FIN missing expected GRAYDIE210 range", fin_path);
}

static void write_header(FILE *out, const SpriteEntry *sprites, int sprite_count) {
    fprintf(out, "/* Generated by tools/dc_info_gen.c. Do not edit by hand. */\n");
    fprintf(out, "#ifndef OPEN_RTS_DARK_COLONY_INFO_H\n#define OPEN_RTS_DARK_COLONY_INFO_H\n\n");
    fprintf(out, "#include \"engine.h\"\n\n");
    fprintf(out, "typedef enum {\n");
    for (int i = 0; i < sprite_count; ++i) fprintf(out, "    %s,\n", sprites[i].symbol);
    fprintf(out, "    NUMSPRITES\n} spritenum_t;\n\n");
    fprintf(out, "typedef enum {\n");
    fprintf(out, "    S_NULL,\n");
    fprintf(out, "    S_DC_TRSC_STND, S_DC_TRSC_RUN1, S_DC_TRSC_RUN2, S_DC_TRSC_RUN3, S_DC_TRSC_RUN4, S_DC_TRSC_RUN5, S_DC_TRSC_RUN6, S_DC_TRSC_RUN7, S_DC_TRSC_RUN8,\n");
    fprintf(out, "    S_DC_TRSC_ATK1, S_DC_TRSC_ATK2, S_DC_TRSC_ATK3, S_DC_TRSC_ATK4, S_DC_TRSC_ATK5, S_DC_TRSC_ATK6, S_DC_TRSC_ATK7, S_DC_TRSC_ATK8,\n");
    fprintf(out, "    S_DC_TRSC_DIE1, S_DC_TRSC_DIE2, S_DC_TRSC_DIE3, S_DC_TRSC_DIE4, S_DC_TRSC_DIE5, S_DC_TRSC_DIE6, S_DC_TRSC_DIE7, S_DC_TRSC_DIE8, S_DC_TRSC_DIE9, S_DC_TRSC_DIE10, S_DC_TRSC_CORPSE,\n");
    fprintf(out, "    S_DC_GRAY_STND, S_DC_GRAY_RUN1, S_DC_GRAY_RUN2, S_DC_GRAY_RUN3, S_DC_GRAY_RUN4, S_DC_GRAY_RUN5, S_DC_GRAY_RUN6, S_DC_GRAY_RUN7,\n");
    fprintf(out, "    S_DC_GRAY_ATK1, S_DC_GRAY_ATK2, S_DC_GRAY_ATK3, S_DC_GRAY_ATK4, S_DC_GRAY_ATK5, S_DC_GRAY_ATK6, S_DC_GRAY_ATK7, S_DC_GRAY_ATK8,\n");
    fprintf(out, "    S_DC_GRAY_DIE1, S_DC_GRAY_DIE2, S_DC_GRAY_DIE3, S_DC_GRAY_DIE4, S_DC_GRAY_DIE5, S_DC_GRAY_DIE6, S_DC_GRAY_DIE7, S_DC_GRAY_DIE8, S_DC_GRAY_DIE9, S_DC_GRAY_ROT1, S_DC_GRAY_ROT2, S_DC_GRAY_ROT3, S_DC_GRAY_CORPSE,\n");
    fprintf(out, "    S_DC_EXPL_STND,\n");
    fprintf(out, "    S_DC_MUZA1, S_DC_MUZA2, S_DC_MUZA3,\n");
    fprintf(out, "    NUMSTATES\n} statenum_t;\n\n");
    fprintf(out, "typedef enum { MT_NULL, MT_DC_TROOPER, MT_DC_GREY, MT_DC_EXPLOITER, NUMMOBJTYPES } mobjtype_t;\n\n");
    fprintf(out, "extern const char *const sprnames[NUMSPRITES];\n");
    fprintf(out, "extern const RtsState states[NUMSTATES];\n");
    fprintf(out, "extern const RtsMobjInfo mobjinfo[NUMMOBJTYPES];\n");
    fprintf(out, "extern const RtsGameInfo dark_colony_game_info;\n\n");
    fprintf(out, "void A_DC_MuzzleFlash(RtsStateContext *ctx, Unit *unit);\n");
    fprintf(out, "void A_DC_Attack(RtsStateContext *ctx, Unit *unit);\n");
    fprintf(out, "void A_DC_Fall(RtsStateContext *ctx, Unit *unit);\n");
    fprintf(out, "void A_DC_Corpse(RtsStateContext *ctx, Unit *unit);\n\n");
    fprintf(out, "#endif\n");
}

static void f8_frame_major_abs(FILE *out, const char *spr, int tics, const char *action,
                               const char *next, int group, int frame_base) {
    static const int dirs[8] = {0,1,2,3,4,5,6,7};
    fprintf(out, "    { %s, %d, %d, %s, %s, 0, %d, 0, 8, {",
            spr, frame_base, tics, action, next, group);
    for (int i = 0; i < 8; ++i) fprintf(out, "%s%d", i ? "," : "", dirs[i]);
    fprintf(out, "}, {");
    for (int i = 0; i < 8; ++i) fprintf(out, "%s%d", i ? "," : "", frame_base + i);
    fprintf(out, "}, {0} },\n");
}

static void f8_frame_major(FILE *out, const char *spr, int tics, const char *action,
                           const char *next, int group, int base, int offset) {
    f8_frame_major_abs(out, spr, tics, action, next, group, base + offset * 8);
}

static void f6(FILE *out, const char *spr, int tics, const char *action, const char *next,
               int group, const int starts[6], int offset) {
    static const int dirs[6] = {2,1,7,5,4,3};
    fprintf(out, "    { %s, %d, %d, %s, %s, 0, %d, 0, 6, {", spr, starts[0] + offset, tics, action, next, group);
    for (int i = 0; i < 6; ++i) fprintf(out, "%s%d", i ? "," : "", dirs[i]);
    fprintf(out, "}, {");
    for (int i = 0; i < 6; ++i) fprintf(out, "%s%d", i ? "," : "", starts[i] + offset);
    fprintf(out, "}, {0} },\n");
}

static void fabs_state(FILE *out, const char *spr, int frame, int tics, const char *action,
                       const char *next, int group) {
    fprintf(out, "    { %s, %d, %d, %s, %s, 0, %d, 0, 0, {0}, {0}, {0} },\n",
            spr, frame, tics, action, next, group);
}

static void gray_die(FILE *out, const char *next, int n, const char *action) {
    int frame_a = n < 9 ? 262 + n : 286 + (n - 9);
    int frame_b = n < 9 ? 271 + n : 289 + (n - 9);
    fprintf(out, "    { SPR_DC_GRAY, %d, 3, %s, %s, 0, 4, 0, 4, {1,3,7,5}, {%d,%d,%d,%d}, {0,0,RTS_FRAME_FLIP_X,RTS_FRAME_FLIP_X} },\n",
            frame_a, action, next, frame_a, frame_b, frame_a, frame_b);
}

static void write_source(FILE *out, const SpriteEntry *sprites, int sprite_count) {
    int trsc = find_sprite(sprites, sprite_count, "SPRITES/TRSC.SPR");
    int gray = find_sprite(sprites, sprite_count, "SPRITES/GRAY.SPR");
    int expl = find_sprite(sprites, sprite_count, "SPRITES/EXPL.SPR");
    int muza = find_sprite(sprites, sprite_count, "SPRITES/MUZA.SPR");
    fprintf(out, "/* Generated by tools/dc_info_gen.c. Do not edit by hand. */\n");
    fprintf(out, "#include \"info.h\"\n\n");
    fprintf(out, "const char *const sprnames[NUMSPRITES] = {\n");
    for (int i = 0; i < sprite_count; ++i) fprintf(out, "    \"%s\",\n", sprites[i].path);
    fprintf(out, "};\n\n");
    fprintf(out, "#define NOACTION NULL\n\n");
    fprintf(out, "const RtsState states[NUMSTATES] = {\n");
    fprintf(out, "    { 0, 0, -1, NOACTION, S_NULL, 0, 0, 0, 0, {0}, {0}, {0} },\n");

    int trsc_die[6] = {128,138,149,159,179,195};
    f8_frame_major(out, sprites[trsc].symbol, -1, "NOACTION", "S_DC_TRSC_STND", 1, 0, 0);
    const char *trsc_run_next[8] = {"S_DC_TRSC_RUN2","S_DC_TRSC_RUN3","S_DC_TRSC_RUN4","S_DC_TRSC_RUN5","S_DC_TRSC_RUN6","S_DC_TRSC_RUN7","S_DC_TRSC_RUN8","S_DC_TRSC_RUN1"};
    for (int i = 0; i < 8; ++i) f8_frame_major(out, sprites[trsc].symbol, 3, "NOACTION", trsc_run_next[i], 2, 16, i);
    const int trsc_atk_frames[8] = {80,88,96,104,112,120,120,120};
    const char *trsc_atk_next[8] = {"S_DC_TRSC_ATK2","S_DC_TRSC_ATK3","S_DC_TRSC_ATK4","S_DC_TRSC_ATK5","S_DC_TRSC_ATK6","S_DC_TRSC_STND","S_DC_TRSC_STND","S_DC_TRSC_STND"};
    const char *trsc_atk_action[8] = {"NOACTION","A_DC_MuzzleFlash","A_DC_Attack","NOACTION","NOACTION","NOACTION","NOACTION","NOACTION"};
    for (int i = 0; i < 8; ++i) f8_frame_major_abs(out, sprites[trsc].symbol, 2, trsc_atk_action[i], trsc_atk_next[i], 3, trsc_atk_frames[i]);
    const char *trsc_die_next[11] = {"S_DC_TRSC_DIE2","S_DC_TRSC_DIE3","S_DC_TRSC_DIE4","S_DC_TRSC_DIE5","S_DC_TRSC_DIE6","S_DC_TRSC_DIE7","S_DC_TRSC_DIE8","S_DC_TRSC_DIE9","S_DC_TRSC_DIE10","S_DC_TRSC_CORPSE","S_NULL"};
    for (int i = 0; i < 10; ++i) f6(out, sprites[trsc].symbol, 3, i == 0 ? "A_DC_Fall" : "NOACTION", trsc_die_next[i], 4, trsc_die, i);
    f6(out, sprites[trsc].symbol, 1, "A_DC_Corpse", trsc_die_next[10], 4, trsc_die, 9);

    f8_frame_major(out, sprites[gray].symbol, -1, "NOACTION", "S_DC_GRAY_STND", 1, 0, 0);
    const char *gray_run_next[7] = {"S_DC_GRAY_RUN2","S_DC_GRAY_RUN3","S_DC_GRAY_RUN4","S_DC_GRAY_RUN5","S_DC_GRAY_RUN6","S_DC_GRAY_RUN7","S_DC_GRAY_RUN1"};
    for (int i = 0; i < 7; ++i) f8_frame_major(out, sprites[gray].symbol, 3, "NOACTION", gray_run_next[i], 2, 16, i);
    const int gray_atk_frames[8] = {78,86,94,102,110,118,118,118};
    const char *gray_atk_next[8] = {"S_DC_GRAY_ATK2","S_DC_GRAY_ATK3","S_DC_GRAY_ATK4","S_DC_GRAY_ATK5","S_DC_GRAY_ATK6","S_DC_GRAY_STND","S_DC_GRAY_STND","S_DC_GRAY_STND"};
    const char *gray_atk_action[8] = {"NOACTION","A_DC_MuzzleFlash","A_DC_Attack","NOACTION","NOACTION","NOACTION","NOACTION","NOACTION"};
    for (int i = 0; i < 8; ++i) f8_frame_major_abs(out, sprites[gray].symbol, 2, gray_atk_action[i], gray_atk_next[i], 3, gray_atk_frames[i]);
    const char *gray_die_next[13] = {"S_DC_GRAY_DIE2","S_DC_GRAY_DIE3","S_DC_GRAY_DIE4","S_DC_GRAY_DIE5","S_DC_GRAY_DIE6","S_DC_GRAY_DIE7","S_DC_GRAY_DIE8","S_DC_GRAY_DIE9","S_DC_GRAY_ROT1","S_DC_GRAY_ROT2","S_DC_GRAY_ROT3","S_DC_GRAY_CORPSE","S_NULL"};
    for (int i = 0; i < 12; ++i) gray_die(out, gray_die_next[i], i, i == 0 ? "A_DC_Fall" : "NOACTION");
    gray_die(out, gray_die_next[12], 11, "A_DC_Corpse");

    fabs_state(out, sprites[expl].symbol, 0, -1, "NOACTION", "S_DC_EXPL_STND", 1);
    fabs_state(out, sprites[muza].symbol, 1, 1, "NOACTION", "S_DC_MUZA2", 0);
    fabs_state(out, sprites[muza].symbol, 2, 1, "NOACTION", "S_DC_MUZA3", 0);
    fabs_state(out, sprites[muza].symbol, 3, 1, "NOACTION", "S_NULL", 0);
    fprintf(out, "};\n\n");

    fprintf(out, "const RtsMobjInfo mobjinfo[NUMMOBJTYPES] = {\n");
    fprintf(out, "    {0},\n");
    fprintf(out, "    { 1, S_DC_TRSC_STND, 800, S_DC_TRSC_RUN1, 0, 0, 0, S_NULL, 0, 0, 0, S_DC_TRSC_ATK1, S_DC_TRSC_DIE1, S_DC_TRSC_DIE1, 0, 5, 16, 32, 100, 100, 0, RTS_TRAIT_SELECTABLE|RTS_TRAIT_MOBILE|RTS_TRAIT_RENDERABLE|RTS_TRAIT_ATTACK, S_NULL },\n");
    fprintf(out, "    { 2, S_DC_GRAY_STND, 800, S_DC_GRAY_RUN1, 0, 0, 0, S_NULL, 0, 0, 0, S_DC_GRAY_ATK1, S_DC_GRAY_DIE1, S_DC_GRAY_DIE1, 0, 5, 16, 32, 100, 100, 0, RTS_TRAIT_SELECTABLE|RTS_TRAIT_MOBILE|RTS_TRAIT_RENDERABLE|RTS_TRAIT_ATTACK, S_NULL },\n");
    fprintf(out, "    { 3, S_DC_EXPL_STND, 800, S_DC_EXPL_STND, 0, 0, 0, S_NULL, 0, 0, 0, S_NULL, S_DC_EXPL_STND, S_DC_EXPL_STND, 0, 5, 16, 32, 100, 0, 0, RTS_TRAIT_SELECTABLE|RTS_TRAIT_MOBILE|RTS_TRAIT_RENDERABLE, S_NULL },\n");
    fprintf(out, "};\n\n");
    fprintf(out, "const RtsGameInfo dark_colony_game_info = { sprnames, NUMSPRITES, states, NUMSTATES, mobjinfo, NUMMOBJTYPES, S_NULL, RTS_DIRECTION_DARK_COLONY_8 };\n");
}

int main(int argc, char **argv) {
    if (argc != 4) die("usage: dc_info_gen DATA/DCOLONY plugins/DarkColony/info.h plugins/DarkColony/info.c", NULL);
    const char *root = argv[1];
    char sprite_dir[1024];
    snprintf(sprite_dir, sizeof(sprite_dir), "%s/SPRITES", root);
    DIR *dir = opendir(sprite_dir);
    if (!dir) die(strerror(errno), sprite_dir);

    SpriteEntry *sprites = NULL;
    int count = 0, cap = 0;
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (!ends_with_ci(ent->d_name, ".SPR")) continue;
        if (count >= cap) {
            cap = cap ? cap * 2 : 128;
            sprites = realloc(sprites, (size_t)cap * sizeof(*sprites));
            if (!sprites) die("out of memory", NULL);
        }
        snprintf(sprites[count].path, sizeof(sprites[count].path), "SPRITES/%s", ent->d_name);
        for (char *p = sprites[count].path; *p; ++p) *p = (char)toupper((unsigned char)*p);
        sprite_symbol(sprites[count].path, sprites[count].symbol, sizeof(sprites[count].symbol));
        char full[1024];
        snprintf(full, sizeof(full), "%s/%s", root, sprites[count].path);
        sprites[count].frames = spr_frame_count(full);
        count++;
    }
    closedir(dir);
    qsort(sprites, (size_t)count, sizeof(*sprites), compare_sprite_entry);
    validate_dark_colony_data(root, sprites, count);

    FILE *h = fopen(argv[2], "w");
    if (!h) die(strerror(errno), argv[2]);
    write_header(h, sprites, count);
    fclose(h);

    FILE *c = fopen(argv[3], "w");
    if (!c) die(strerror(errno), argv[3]);
    write_source(c, sprites, count);
    fclose(c);

    free(sprites);
    return 0;
}
