#define OWNER_PRODUCER MT_MUTE_CLANHALL
#define PLAYER_PRODUCER MT_SURV_OUTPOST
#define PLAYER_PRODUCT 20
#define AI_FIRST_UNIT MT_MUTE_BEAST_ENCLOSURE
#define AI_FIRST_COUNT 1
#define AI_ADVANCED_UNIT MT_MUTE_WAR_MASTADONT
#define AI_ADVANCED_COUNT 1
#include "../production_regression.h"
